hmcts/azure-platform-terraform

environments/demo/backend_lb_config.yaml
=> move to second gw

environments/stg/stg.tfvars
Reverts hmcts/azure-platform-terraform#1025 following rebuild of aat-01
=> Revert "DTSPO-7038 - AAT - Removed aat-01 from AGW pool for rebuild"

environments/prod/backend_lb_config.yaml, environments/prod/prod.tfvars
https://tools.hmcts.net/jira/browse/LAU-310
Add LAU prod config
```
[ ] Yes
[x] No
```
=> LAU-310 Add LAU Prod

environments/sbox/backend_lb_config.yaml, environments/sbox/sbox.tfvars
=> Golden Path walkthrough

environments/demo/backend_lb_config.yaml
Add camunda BPM demo
```
[ ] Yes
[X] No
```
=> Add camunda BPM demo

azure_pipeline.yaml, components/apim/local.tf
add apim to demo environment
```
[ ] Yes
[X] No
```
=> add apim to demo environment

environments/demo/demo.tfvars
add cft-api-mgmt to demo frontdoor
```
[ ] Yes
[X] No
```
=> add cft-api-mgmt to demo frontdoor

environments/stg/stg.tfvars
https://tools.hmcts.net/jira/browse/ADOP-669
Added rf query param to adoption-web global_exclusions list
```
[ ] Yes
[x] No
```
=> Added rf query param to adoption-web global_exclusions list

environments/sbox/sbox.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-3187
Switch plum to use and test multi-az agw
```
[ ] Yes
[x ] No
```
=> DTSPO-3187 - SBOX - Switch Plum to Test Multi-AZ AGW

environments/demo/backend_lb_config.yaml
Fix
Move product rd to second app gateway to reduce the number of connections below a hard limit of 100.
Environment demo.
```
[ ] Yes
[x] No
```
=> Move product rd to second application gateway.

environments/prod/backend_lb_config.yaml, environments/prod/prod.tfvars
https://tools.hmcts.net/jira/browse/SIDM-7239
- Added WAF rules for idam-user-dashboard in PROD
**DO NOT MERGE UNTIL RELEASE WINDOW**
```
[ ] Yes
[x] No
```
=> SIDM-7239 - Added WAF rules for idam-user-dashboard in PROD

azure_pipeline.yaml, environments/stg/stg.tfvars
add apim to aat environment
```
[ ] Yes
[X] No
```
=> add apim to aat environment

environments/demo/demo.tfvars
Swap to demo-00 AKS 1.21.7 rebuild
```
[ ] Yes
[x] No
```
=> swap to demo-00 AKS 1.21.7 rebuild

environments/stg/stg.tfvars
add et-sya aat dns
```
[ ] Yes
[x] No
```
=> add et-sya aat dns

environments/prod/prod.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-7269
Added Payment-Outcome prod config.
```
[ ] Yes
[X] No
```
=> Added Payment-Outcome prod config.

environments/stg/stg.tfvars
add cft-api-mgmt to aat frontdoor
```
[ ] Yes
[X] No
```
=> add cft-api-mgmt to aat frontdoor

azure_pipeline.yaml, environments/sbox/sbox.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-3187
Removed pipeline stages for old app gateways
Removed old app gateways and repointed to old Az Firewall DNS which is now pointing to new frontend appgateway private IP address (following merging of this [Az Firewall/Palo PR](https://github.com/hmcts/rdo-terraform-hub-dmz/pull/553))
```
[ ] Yes
[ x] No
```
=> DTSPO-3187 - SBOX - Multi-AZ AGW Post Switchover Cleanup

environments/prod/prod.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-6659
Remove Prod-00 from AGW load balancer pool prior to rebuild.
```
[ ] Yes
[ x] No
```
=> DTSPO-6659 - PROD - AKS Upgrade - Remove prod-00 from AGW

environments/stg/stg.tfvars
=> az front door config for ds-ui

environments/ithc/backend_lb_config.yaml, environments/ithc/ithc.tfvars, environments/stg/backend_lb_config.yaml, environments/stg/stg.tfvars
https://tools.hmcts.net/jira/browse/FACT-1142
Add rpts to aat
```
[ ] Yes
[x ] No
```
=> Add rpts to aat

environments/ithc/backend_lb_config.yaml, environments/ithc/ithc.tfvars
(https://tools.hmcts.net/jira/browse/FACT-1142)
adding rpts to ithc environment
```
[ ] Yes
[ X] No
```
=> adding rpts to ithc environment

environments/stg/backend_lb_config.yaml
add et-sya backend api to aat
```
[ ] Yes
[x] No
```
=> add et sya backend api to aat

environments/prod/prod.tfvars
- Add dtCookie 
- Add pcq-cookie-preferences
```
[ ] Yes
[x] No
```
=> Add PCQ cookie exclusions

environments/prod/prod.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-6659
Remove Prod-01 from AGW load balancer pool prior to rebuild.
```
[ ] Yes
[x] No
```
=> DTSPO-6659 - PROD - AKS Upgrade - Remove prod-01 from AGW

environments/prod/prod.tfvars
Reverts hmcts/azure-platform-terraform#1021 following rebuild completion.
=> Revert "DTSPO-6659 - PROD - AKS Upgrade - Remove prod-01 from AGW"

environments/demo/backend_lb_config.yaml
=> Add HMC backend lb conf to Demo

environments/stg/backend_lb_config.yaml, environments/test/backend_lb_config.yaml
fix stg test backend appgws due to BackendAddressPools maxmium
```
[ ] Yes
[X] No
```
=> fix stg test backend appgws due to BackendAddressPools maxmium

environments/ithc/backend_lb_config.yaml, environments/test/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/PRL-957
Perf test deployment
```
[ ] Yes
[x] No
```
=> prl changes for iths and perftest

environments/ithc/ithc.tfvars
routing to ithc-01 only as rebuilding ithc-00
```
[ ] Yes
[x] No
```
=> routing to ithc-01 only as rebuilding ithc-00

environments/ithc/ithc.tfvars
Reverts hmcts/azure-platform-terraform#1065
=> Revert "routing to ithc-01 only as rebuilding ithc-00"

environments/ithc/ithc.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-5415
Routing ITHC to ITHC00 as rebuilding ITHC01
```
[ ] Yes
[x] No
```
=> removed ITHC01 from agw for rebuild

environments/stg/stg.tfvars
removed aat00 cluster from agw while upgrading flux
```
[ ] Yes
[x] No
```
=> removed aat00 cluster from agw while upgrading flux

azure_pipeline.yaml, environments/ithc/ithc.tfvars
add cft-apim ithc
```
[ ] Yes
[X] No
```
=> add cft-apim ithc

environments/stg/stg.tfvars
Added aat00 cluster back into agw.
```
[ ] Yes
[x] No
```
=> added aat00 back into agw

environments/stg/stg.tfvars
removed aat01 cluster from agw while upgrading flux
```
[ ] Yes
[x] No
```
=> removed aat01 cluster from agw while upgrading flux

environments/stg/stg.tfvars
adding aat01 back into AGW after flux upgrade
```
[ ] Yes
[x] No
```
=> added aat01 back into agw

environments/ithc/ithc.tfvars, environments/test/test.tfvars
=> Paymentoutcomeweb

environments/ithc/ithc.tfvars
https://tools.hmcts.net/jira/browse/FACT-1142
correcting custom domain for rpts
```
[ ] Yes
[ x] No
```
=> correcting custom domain for rpts

environments/prod/prod.tfvars
[RIA-4974](https://tools.hmcts.net/jira/browse/RIA-4974)
[APM-859](https://tools.hmcts.net/jira/browse/APM-859)
Global exclusions to enable cookie banner in production environment.
```
[ ] Yes
[x] No
```
=> RIA-4974 global exclusions for cookie banner

environments/prod/prod.tfvars
[RIA-4974](https://tools.hmcts.net/jira/browse/RIA-4974)
Additional exclusions for iac cookie banner in prod
```
[ ] Yes
[x] No
```
=> RIA-4974 additional exclusions for iac prod

environments/prod/prod.tfvars
- Use rules for disabling similar to what is configured for divorce 1.
- Added IP whitelisting
=> Added front door config for nfdiv civil partnership

environments/prod/prod.tfvars
[RIA-4974](https://tools.hmcts.net/jira/browse/RIA-4974)
Additional exclusion similar to that used by Probate and SSCS.
```
[ ] Yes
[x] No
```
=> RIA-4974 additional exclusion for QueryStringArgName

environments/prod/prod.tfvars
[RIA-4974](https://tools.hmcts.net/jira/browse/RIA-4974)
N/A
```
[ ] Yes
[x] No
```
=> RIA-4974 exclusions for IAC

environments/stg/stg.tfvars
=> Added new app DNS name in front door

environments/demo/backend_lb_config.yaml, environments/ithc/backend_lb_config.yaml, environments/prod/backend_lb_config.yaml, environments/stg/backend_lb_config.yaml, environments/test/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/RWA-1255
Deprecating wa-task-configuration-api
```
[ ] Yes
[x] No
```
=> RWA-1255 [SH] Deprecating wa-task-configuration-api

environments/ithc/ithc.tfvars
(https://tools.hmcts.net/jira/browse/FACT-1142)
restricting rpts for vpn access only
```
[ ] Yes
[ x] No
```
=> restricting rpts for vpn access only

azure_pipeline.yaml, environments/ithc/ithc.tfvars
=> DTSPO-4682 - ITHC - app gws

environments/demo/backend_lb_config.yaml, environments/ithc/backend_lb_config.yaml, environments/prod/backend_lb_config.yaml, environments/stg/backend_lb_config.yaml, environments/test/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/EUI-5593
Add lb config for XUI Activity Tracker API 
```
[ ] Yes
[x] No
```
=> Add lb config for XUI Activity Tracker API

environments/prod/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/ADOP-374
Added adoption load balancer config
```
[X] Yes
[ ] No
```
=> Added adoption load balancer config

environments/prod/prod.tfvars
https://tools.hmcts.net/jira/browse/ADOP-373
Added adoption front-door configuration for prod
_Public DNS PR has been merged before this one_
https://github.com/hmcts/azure-public-dns/pull/823
https://github.com/hmcts/azure-public-dns/pull/824
```
[ ] Yes
[x] No
```
=> adoption frontdoor configuration for prod

environments/stg/backend_lb_config.yaml
=> Adding load balancer config for new components

environments/prod/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/PRL-963
Added Backend repositories
```
[ ] Yes
[x] No
```
=> Adding private law backend repositories

components/apim-appgw/main.tf, environments/variables.tf
=> APIM App GW module

environments/ithc/ithc.tfvars
=> DSTPO-4682 ithc app gw: switch plum for testing

environments/stg/backend_lb_config.yaml
adding civil service
```
[ ] Yes
[ ] No
```
=> add civil service to general app helm

environments/ithc/backend_lb_config.yaml, environments/ithc/ithc.tfvars
=> Ithc - switch to new ha app gw

azure_pipeline.yaml, environments/ithc/ithc.tfvars
=> ITHC - old app gw cleanup

environments/demo/backend_lb_config.yaml, environments/ithc/backend_lb_config.yaml, environments/sbox/backend_lb_config.yaml, environments/stg/backend_lb_config.yaml, environments/test/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/RIA-5741
This PR is to include a new component under IA (Immigration & Asylum), which is being developed.
```
[ ] Yes
[ X] No
```
=> Updates to add new component for IAC bails

environments/stg/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/SIDM-7279
Add idam-testing-support-api to AAT
```
[ ] Yes
[X] No
```
=> SIDM-7279 Update backend_lb_config.yaml

environments/prod/prod.tfvars
[DFR-885](https://tools.hmcts.net/jira/browse/DFR-885)
Added new entry for old divorce PFE amend application
```
[ ] Yes
[ x] No
```
=> DFR-885: Added new entry for manage-application domain

azure_pipeline.yaml, components/apim/local.tf, environments/prod/prod.tfvars
add apim prod
```
[ ] Yes
[X] No
```
=> add apim prod

environments/ithc/backend_lb_config.yaml, environments/prod/backend_lb_config.yaml, environments/stg/backend_lb_config.yaml, environments/test/backend_lb_config.yaml
HMC go live for CHG5008211
(Note: Demo has already been done previously)
```
[ ] Yes
[x] No
```
=> Add HMC LB config to all remaining envs for go live

environments/stg/stg.tfvars
Exclude Dynatrace RUM post calls
```
[ ] Yes
[x] No
```
=> PCQ - Exclude Dynatrace RUM post calls

environments/ithc/ithc.tfvars, environments/test/test.tfvars
=> Private law citizen journey perftest and ithc env setup

environments/stg/stg.tfvars
https://tools.hmcts.net/jira/browse/DTSPB-2751
Added custom rule for RUM Beacon POST calls.
```
[ ] Yes
[x] No
```
=> Update stg.tfvars to Exclude Dynatrace RUM By custom Rule

components/compliance/provider.tf
https://tools.hmcts.net/jira/browse/DTSPO-8837
Use azurerm v3 provider for compliance
No infrastructure changes related to this component
```
[ ] Yes
[x] No
```
=> DTSPO-8837 - Azurerm v3 provider compliance

components/dynatrace_activegate/provider.tf
https://tools.hmcts.net/jira//browse/DTSPO-8837
Use azurerm v3 provider for dynatrace
No infrastructure changes related to this component
```
[ ] Yes
[x] No
```
=> DTSPO-8837 - Azurerm v3 provider dynatrace

components/shutter/provider.tf, environments/ithc/ithc.tfvars, environments/prod/prod.tfvars, environments/sbox/sbox.tfvars, environments/stg/stg.tfvars, environments/test/test.tfvars, modules/shutter_page/storage_account.tf
https://tools.hmcts.net/jira/browse/DTSPO-8837
Use azurerm v3 provider for shutter
```
[ ] Yes
[x] No
```
=> DTSPO-8837 - Azurerm v3 provider shutter

environments/prod/prod.tfvars
add cft-api-mgmt to production frontdoor
- This PR needs merged prior https://github.com/hmcts/rdo-terraform-hub-dmz/pull/606 
```
[ ] Yes
[X] No
```
=> add cft-api-mgmt to production frontdoor

components/apim/main.tf
https://tools.hmcts.net/jira/browse/DTSPO-8837
Use main branch for apim module
Depends on https://github.com/hmcts/cnp-module-api-mgmt-private/pull/35 being merged first
No infrastructure changes to apim are taking place
```
[ ] Yes
[x] No
```
=> DTSPO-8837 - Use main branch for apim module

azure_pipeline.yaml, environments/test/test.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-4683
Add new AppGw IP's for enabling multi-zone
```
[ ] Yes
[X] No
```
=> Add new AppGw IP's for enabling multi-zone

environments/test/test.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-4683
testing plum on new AppGW
```
[ ] Yes
[X] No
```
=> Change backend domain for plum to test new AppGW

environments/test/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/RET-2082
Add Employment Tribunals Submit Your Application (SYA) Java API to the 'perftest' Load Balancer config.
```
[ ] Yes
[ x] No
```
=> Add Employment Tribs SYA Java API to 'perftest' LB

environments/prod/prod.tfvars
Update stg.tfvars to Exclude Dynatrace RUM By custom Rule On PROD
https://tools.hmcts.net/jira/browse/DTSPB-2751
Update stg.tfvars to Exclude Dynatrace RUM By custom Rule On PROD
```
[ ] Yes
[x] No
```
=> Update stg.tfvars to Exclude Dynatrace RUM By custom Rule On PROD

environments/test/test.tfvars
https://tools.hmcts.net/jira/browse/RET-2082
Add Node 'et-sya' app to 'perftest' Azure Front Door config as part of path to live tasks.
```
[ ] Yes
[x ] No
```
=> Add 'et-sya' to perftest Front Door config.

azure_pipeline-global.yaml
https://tools.hmcts.net/jira/browse/DTSPO-9050
Update dependsOn conditions so that sbox must pass before other environments are targeted
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[x] No
=> DTSPO-9050 - Update dependsOn to sbox

environments/test/test.tfvars
https://tools.hmcts.net/jira/browse/RET-2082
Updated incorrect Azure Front Door config for 'et-sya' custom domain.
```
[ ] Yes
[x ] No
```
=> Updated incorrect Azure FD config for custom domain

environments/sbox/sbox.tfvars
DTSPO-8141 Traefik-v2 migration 
Re-add SBOX 00 cluster so Paul Verity can run some some tests.
```
[ ] Yes
[x] No
```
=> re-add sbox 00

environments/sbox/sbox.tfvars
DTSPO-8141 Traefik v2 upgrade on sbox 01
Removing sbox 01 cluster to upgrade traefik-v2.
```
[ ] Yes
[ x] No
```
=> Remove sbox01 to upgrade traefik

environments/sbox/sbox.tfvars
update sbox00 private IP for app gw traefikv2
```
[ ] Yes
[X] No
```
=> update sbox00 private IP for app gw traefikv2

environments/sbox/sbox.tfvars
Reverts hmcts/azure-platform-terraform#1184
=> Revert "update sbox00 private IP for app gw traefikv2"

environments/sbox/sbox.tfvars
DTSPO-7909 AKS upgrade 
Switching cluster brining back sbox01 and taking 00 out, sbox 01 is now running als 1.23.5.
```
[ ] Yes
[x] No
```
=> add sbox01 back in

environments/sbox/sbox.tfvars
DTSPO-7909 - AKS upgrade sbox 
Adding sbox 00 back in to the cluster.
```
[ ] Yes
[x] No
```
=> add sbox 00 back

environments/ithc/backend_lb_config.yaml, environments/test/backend_lb_config.yaml
=> SSCS-10742 Add hearings api lb configs

.pre-commit-config.yaml, README.md
update pre commit config for terraform_fmt & added app_gateway_backend_check 
```
[ ] Yes
[X] No
```
=> update pre commit config for terraform_fmt & added app_gateway_backend_check 

environments/prod/prod.tfvars
To include RUM in the WAF rules
```
[ ] Yes
[x] No
```
=> Adding WAF rules to include RUM

.github/workflows/pre-commit.yml, .pre-commit-config.yaml, environments/ithc/ithc.tfvars, environments/prod/prod.tfvars, environments/test/backend_lb_config.yaml
This runs our pre-commit hooks in CI
(This shows our existing tests weren't running on some tfvars files before, and I've fixed the issues in this PR)
=> Run pre-commit in CI

.github/workflows/pre-commit.yml
update pre-commit.yml to reference master
```
[ ] Yes
[X] No
```
=> update pre-commit.yml to reference master

environments/prod/prod.tfvars
=> fix adding of new prod appgw

environments/ithc/ithc.tfvars
=> Take out ithc-01 from app gw

environments/ithc/ithc.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-8027
Rebuilding ITHC-00, removing from appgw so we can destroy
```
[ ] Yes
[ ] No
```
=> Remove 00 from appgw

environments/demo/backend_lb_config.yaml, environments/ithc/backend_lb_config.yaml, environments/prod/backend_lb_config.yaml, environments/stg/backend_lb_config.yaml, environments/test/backend_lb_config.yaml
In preparation for CHG5008835.
```
[ ] Yes
[x] No
```
=> Add Translation Service LB config to all envs

environments/prod/backend_lb_config.yaml, environments/stg/backend_lb_config.yaml, environments/test/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/RIA-5878
Updates to include bail service in prod LB, as part of bails private beta release preparation
```
[ ] Yes
[X ] No
```
=> Updates to include bails in prod LB

environments/test/test.tfvars
=> new cookie in paybubble

environments/demo/backend_lb_config.yaml
=> Update backend_lb_config.yaml for fis backend services

environments/test/test.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-8033
Removes cft-perftest-01-aks from AppGw for upgrading
```
[ ] Yes
[x] No
```
=> Remove perftest-01 from AppGw

environments/test/test.tfvars
Reverts hmcts/azure-platform-terraform#1224
=> Revert "Remove perftest-01 from AppGw"

environments/test/test.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-8033
Removes cluster 00 from AppGw for upgrade
```
[ ] Yes
[ ] No
```
=> Removes perftest cluster 00 from AppGw

environments/test/test.tfvars
Reverts hmcts/azure-platform-terraform#1225
=> Revert "Removes perftest cluster 00 from AppGw"

environments/demo/backend_lb_config.yaml, environments/ithc/backend_lb_config.yaml, environments/test/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/SIDM-7929
https://tools.hmcts.net/jira/browse/SIDM-7930
https://tools.hmcts.net/jira/browse/SIDM-7931
Add backend LB config for idam-testing-support-api in perftest, demo, and ithc.
```
[ ] Yes
[x] No
```
=> Add idam-testing-support-api to Perftest/Demo/ITHC backend gateways

environments/ithc/ithc.tfvars
add backend appgw private ip address for ithc new appgw1
```
[ ] Yes
[X] No
```
=> add backend appgw private ip address for ithc new appgw1

environments/stg/stg.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-8031
```
[ ] Yes
[ ] No
```
=> Remove 01 cluster from appgw

environments/stg/backend_lb_config.yaml
Adds plum to backend lb config
```
[ ] Yes
[ ] No
```
=> Adds plum to backend lb config

environments/stg/stg.tfvars
=> Add 01 to appgw and remove 00

environments/stg/stg.tfvars
=> Add 00 cluster back to appgw

environments/prod/prod.tfvars
=> Removing for AKS  node restarts

environments/prod/prod.tfvars
Reverts hmcts/azure-platform-terraform#1252
=> Revert "Removing for AKS  node restarts"

environments/prod/prod.tfvars
=> Remove 01 for restart

environments/prod/prod.tfvars
Reverts hmcts/azure-platform-terraform#1254
=> Revert "Remove 01 for restart"

environments/stg/backend_lb_config.yaml
IP needed updating, removing from here to avoid resource conflict when recreating from https://github.com/hmcts/azure-private-dns/pull/436.
```
[ ] Yes
[ ] No
```
=> Remove dns entries to avoid resource conflict when readding

environments/test/test.tfvars
=> correct backend urls perftest

environments/stg/backend_lb_config.yaml
removing ccd and camunda from load balancer
```
[ ] Yes
[x ] No
```
=> removing ccd and camunda from load balancer

environments/ithc/ithc.tfvars
https://tools.hmcts.net/jira/browse/HMIS-1095
Added ITHC environment for HMI
```
[ ] Yes
[ X] No
```
=> Added ITHC env for HMI

environments/ithc/ithc.tfvars
HMIS-1095
Correct ITHC Firewall URL for HMI
```
[ ] Yes
[ x ] No
```
=> HMIS-1095 - Correct ITHC Firewall URL for HMI

environments/demo/backend_lb_config.yaml, environments/ithc/backend_lb_config.yaml, environments/ithc/ithc.tfvars, environments/test/test.tfvars
https://tools.hmcts.net/jira/browse/RET-2536
Azure Front Door config and small change for backend on demo
```
[ ] Yes
[X] No
```
=> Change mode for ET WAF

environments/prod/prod.tfvars
Removes IP restrictions on prod for plum
```
[ ] Yes
[X] No
```
=> Removes IP restrictions on prod for plum

environments/ithc/ithc.tfvars
add cft-api-mgmt ithc frontdoor
```
[ ] Yes
[X] No
```
=> add cft-api-mgmt ithc frontdoor

environments/prod/backend_lb_config.yaml
Removes Plum from prod current AppGw config
```
[ ] Yes
[ ] No
```
=> Removes entry in LB for plum prod

environments/stg/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/EM-4597
Added in em-ped-api
```
[ ] Yes
[X] No
```
=> Added in em-ped-api

components/cftapps_cluster_lb_backend_arm_tf/dns.tf, environments/prod/backend_lb_config.yaml, environments/prod/backend_lb_config_arm_to_tf.yaml
Adds DNS for new config & adds second BE AppGw
```
[ ] Yes
[X] No
```
=> Adds DNS for new config & adds second BE AppGw

components/cftapps_cluster_lb_backend_arm_tf/dns.tf, components/cftapps_cluster_lb_backend_arm_tf/provider.tf
=> ADD DNS for new config

components/cftapps_cluster_lb_backend_arm_tf/dns.tf
=> DNS zone_record_update

environments/prod/backend_lb_config_arm_to_tf.yaml
=> PRod upgrade: Create a app gateway

environments/prod/backend_lb_config_arm_to_tf.yaml
=> Prod_upgrade Prod_upgrade_testing

environments/prod/backend_lb_config_arm_to_tf.yaml
=> prod upgrade :: max limit on appgw

environments/prod/prod.tfvars
=> Update custom domain

migrate-appgateway.md
Update video to working link for another KT session - this will demonstrate how to commit and push changes to panormas
```
[ ] Yes
[x] No
```
=> Update video to working link for another KT session

environments/prod/prod.tfvars
https://tools.hmcts.net/jira/browse/RET-2081
Update Cert
```
[ ] Yes
[ ] No
```
=> Update ET SYA certificate

environments/demo/demo.tfvars
Send traffic only to demo 00 cluster
```
[ ] Yes
[x] No
```
=> Update Cluster IPS

environments/demo/backend_lb_config.yaml
=> updated config for fis

environments/stg/stg.tfvars
=> DTSPO-4684. switch plum to new FW appgwupdate

environments/stg/stg.tfvars
=> DTSPO-4684 update plum backend 

azure_pipeline.yaml, environments/stg/stg.tfvars
=> DTSPO-4685  AAT::  Clean up

environments/prod/prod.tfvars
=> DTSPO-4685 ::  PROD:: Change plum backend

environments/prod/prod.tfvars
=> DTSPO-4865 updating IP address for new app gw

environments/demo/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/LAU-472
Adding LB for Log and Audit demo int backend
```
[ ] Yes
[x] No
```
=> LAU-472: Update to add demo int backends

environments/prod/prod.tfvars
https://tools.hmcts.net/jira/browse/RET-2081
Delete et-sya from Prod config. Re-adding with custom domain amendment on separate PR to get Terraform to first apply delete.
```
[ ] Yes
[x ] No
```
=> Delete et-sya from Prod config

environments/prod/prod.tfvars
https://tools.hmcts.net/jira/browse/RET-2081
After first deleting previously incorrect ET SYA Azure Front Door config, re-add with amended config settings.
```
[ ] Yes
[ x] No
```
=> Re-add ET SYA Azure Front Door config

environments/prod/prod.tfvars
Added www. to custom domain
```
[ ] Yes
[ ] No
```
=> Update ET Custom Domain

environments/demo/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/PCQ-1471
PCQ Backend Demo Int LB
```
[ ] Yes
[x] No
```
=> PCQ-1471: Adding LB for PCQ Backend Demo Int

environments/demo/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/PCQ-1471
Retriggering update
```
[ ] Yes
[x] No
```
=> PCQ-1471: Retriggering update

components/backendappgateway/local.tf, components/frontendappgateway/local.tf
https://tools.hmcts.net/jira/browse/DTSPO-4686
update to add demo to frontend / backend app gw.
```
[ ] Yes
[x] No
```
=> update to locals for demo env for frontend / backend

environments/demo/demo.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-4686
Updated backend agw ip addresses due to original ip's being reserved addresses.
```
[ ] Yes
[x] No
```
=> updated backend agw ips for demo backend agw

environments/demo/demo.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-4686
updated frontend agw ip
```
[ ] Yes
[x] No
```
=> updated demo frontend agw ip

environments/demo/demo.tfvars
Value coming from https://github.com/hmcts/cnp-flux-config/blob/master/apps/admin/traefik2/demo/01-auth-proxy.yaml#L15
```
[ ] Yes
[ ] No
```
=> Update to use 01 cluster IP

environments/prod/backend_lb_config_arm_to_tf.yaml
=> SSCS-10958 : Added SSCS hearings API to LB prod

environments/stg/stg.tfvars
- [ Y] commit messages are meaningful and follow good commit message guidelines
```
[ ] Yes
[X ] No
```
=> Added Fees-Register cookie to aat exclusion list

azure_pipeline.yaml
=> Remove old stages

environments/demo/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/DTSPO-4686
Update private dns to new backend app gateway
```
[ ] Yes
[x] No
```
=> DTSPO4686 - DEMO AGW Switchover - Update Private DNS

environments/stg/stg.tfvars
https://tools.hmcts.net/jira/browse/PCQ-1597
Match PCQ AAT rules with Production
```
[ ] Yes
[x] No
```
=> PCQ-1597 Match PCQ AAT rules with Production

components/backendappgateway/main.tf, components/backendappgateway/provider.tf
Upgrade azurerm provider in backend appgw component to 3.34
```
[ ] Yes
[x] No
```
=> DTSPO-10835 - AzureRM 3.34 Backend AppGW

azure_pipeline.yaml, components/cftapps_private_dns/provider.tf
Upgrade azurerm provider in Private DNS component to 3.34
Update pipeline dependsOn and add tests to more stages
```
[ ] Yes
[x] No
```
=> DTSPO-10835 - AzureRM 3.34 Private DNS

azure_pipeline.yaml, components/apim/init.tf
Upgrade azurerm provider in apim component to 3.34
```
[ ] Yes
[x] No
```
=> DTSPO-10835 - AzureRM 3.34 APIM

modules/dynatrace-activegate/cloudconfig-private.tpl, modules/dynatrace-activegate/cloudconfig.tpl
=> Update umask setting on Dynatrace Active Gates

components/apim-appgw/init.tf, components/apim-appgw/main.tf
Upgrade azurerm provider to 3.34 on apim appgw component
```
[ ] Yes
[x] No
```
=> DTSPO-10835 - AzureRM 3.34 APIM AppGW

README.md, modules/dynatrace-activegate/vm.tf
=> README Custom Data Update

components/global/main.tf
Revert frontdoor module to master branch
```
[ ] Yes
[x] No
```
=> DTSPO-10835 - Frontdoor Module

environments/stg/stg.tfvars
https://tools.hmcts.net/jira/browse/EM-4651
Added in em-icp to AAT frontdoor
```
[ ] Yes
[X] No
```
=> Added in em-icp to AAT frontdoor

environments/stg/stg.tfvars
https://tools.hmcts.net/jira/browse/EM-4651
Added in product name for em-icp to fix broken build
```
[ ] Yes
[X] No
```
=> Added in product name for em-icp to fix broken build

environments/demo/demo.tfvars
=> DTSPO-11427 demo_upgrade

environments/stg/stg.tfvars
=> remove 00 app gw

environments/demo/demo.tfvars
Reverts hmcts/azure-platform-terraform#1381
=> Revert "DTSPO-11427 demo_upgrade"

components/apim-appgw/main.tf, components/apim/main.tf, components/backendappgateway/main.tf, components/dynatrace_activegate/nonprod.tf, components/frontendappgateway/main.tf, components/global/main.tf, components/shutter/module_shutter.tf, environments/variables.tf
Set expiresAfter tag to 3000-01-01 so sandbox resources do not get deleted
```
[ ] Yes
[x] No
```
=> DTSPO-11790 - add expiresAfter tag

environments/prod/prod.tfvars
=> remove 00 appgw from rotation

environments/prod/prod.tfvars
=> add 00 back in

environments/prod/prod.tfvars
=> remove 01 appgw

environments/prod/prod.tfvars
=> add back in 01 appgw

environments/sbox/backend_lb_config.yaml
=> add labs-jasonpaige

environments/sbox/backend_lb_config.yaml
=> Adding new golden path apps to sbox

environments/sbox/backend_lb_config.yaml
=> Clean up labs-jasonpaige

environments/prod/prod.tfvars
=> Prod config for dtsse-ardoq-adapter

environments/prod/backend_lb_config.yaml
=> Adds missing dtsse-ardoq-adapter lb config

environments/prod/prod.tfvars
Trying to resolve this blocked request: [App Insights](https://portal.azure.com#@531ff96d-0ae9-462a-8d2d-bec7c0b42082/blade/Microsoft_OperationsManagementSuite_Workspace/Logs.ReactView/resourceId/%2Fsubscriptions%2F8cbc6f36-7c56-4963-9d36-739db5d00b27%2FresourceGroups%2Flz-prod-rg%2Fproviders%2FMicrosoft.Network%2Ffrontdoors%2Fhmcts-prod/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAA0WN307CMByF732KZQ9ghsEYL3ZRGF0WaKulcY4bU7sfo9tsSVfYn%252FjwAjF67k6%252B7%252BSg6eQg0bIytvNadXffQX8ABwGHzp6cghdnz7oEF8RxEJJsydmWYXFPVyJnfB0G0pTBUnqorBtvDnbW%252BNJal8MnOh5braTX1mDtoJdtu7FV%252BHci1RV9dLfhorWq%252BWfeSdVoU3HYX6pR8KtFbP6%252BLnp0SWJBluNX3xP%252B1J1hevNu2Cdi9cxIjTFflZiIaqAIRbs0G%252BlD9kjH2YHmr9NG8HZXE8%252FSYl5so4EmaCBi0dCazFhK4vAHAvL4qhgBAAA%253D/timespan/P1D)
**Does this PR …
=> Exclude POSTs for DTSSE

environments/ithc/backend_lb_config.yaml, environments/prod/backend_lb_config.yaml, environments/test/backend_lb_config.yaml
=> fis Incl for all the environments

environments/demo/demo.tfvars
plum-public.demo app gateway frontend
```
[ ] Yes
[X] No
```
=> plum-public.demo app gateway frontend

environments/prod/prod.tfvars
=> remove prod01 appgw from rotation

environments/prod/prod.tfvars
=> bring back 01

environments/prod/prod.tfvars
=> add back in 00

environments/ithc/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/EM-2789
Revert em-ccd-orchestrator change
```
[ ] Yes
[X] No
```
=> Revert em-ccd-orchestrator change

environments/ithc/ithc.tfvars, environments/prod/prod.tfvars, environments/sbox/sbox.tfvars, environments/stg/stg.tfvars, environments/test/test.tfvars
https://tools.hmcts.net/jira/browse/SIDM-8464
Exclude post body scope attribute
```
[ ] Yes
[X] No
```
=> SIDM-8464 Exclude post body scope attribute

environments/demo/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/EM-2789
Revert em-ccd-orchestrator change on Demo.
```
[ ] Yes
[X] No
```
=> Revert em-ccd-orchestrator change on Demo

environments/stg/stg.tfvars
https://tools.hmcts.net/jira/browse/FACT-1296
switch fact aat to prevention mode
```
[ ] Yes
[x] No
```
=> switch fact aat to prevention mode

environments/stg/stg.tfvars
https://tools.hmcts.net/jira/browse/FACT-1296
add fact aat global exclusions
```
[ ] Yes
[x] No
```
=> add fact aat global exclusions

environments/stg/stg.tfvars
https://tools.hmcts.net/jira/browse/FACT-1296
update fact aat global exclusions
```
[ ] Yes
[x] No
```
=> update fact aat global exclusions

environments/prod/prod.tfvars
https://tools.hmcts.net/jira/browse/FACT-1296
switch fact prod to prevention mode
```
[ ] Yes
[x] No
```
=> switch fact prod to prevention mode

environments/sbox/sbox.tfvars
=> adding-golden-path-fd

environments/sbox/sbox.tfvars
Hackaton test lab
```
[ ] Yes
[ ] No
```
=> GP test lab

environments/sbox/sbox.tfvars
=> Tyler-goldenpath-cleardown

azure_pipeline.yaml
=> Dtspo-12074 update pipelinetest condition

azure_pipeline-global.yaml, azure_pipeline.yaml
=> Dtspo 12074.  update pipelinetest 

environments/stg/stg.tfvars
=> add fis-ds-update-web application copy

environments/test/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/ST-1027
Add sptribs-case-api to perftest environment
```
[ ] Yes
[x] No
```
=> ST-1027 Add sptribs-case-api to perftest env

environments/demo/demo.tfvars, environments/ithc/ithc.tfvars, environments/stg/stg.tfvars, environments/test/test.tfvars
=> ISDB-658 DSS Update case for All non prod environments

environments/stg/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/EM-5151
Removed redundant em entries for AAT to resolve the Dynatrace AAT availability SLO status.
```
[ ] Yes
[X] No
```
=> Removed redundant em entries for AAT

environments/demo/demo.tfvars
https://tools.hmcts.net/jira/browse/HMIS-1142
Setting up the Front end for the new HMI Demo environment 
```
[ ] Yes
[x] No
```
=> HMIS-1142 - HMI Demo environment setup

environments/demo/demo.tfvars
Removed to fix fd - re-adding now @yogendraU 
```
[ ] Yes
[ ] No
```
=> Re-add dss-update-case

environments/demo/demo.tfvars
https://tools.hmcts.net/jira/browse/HMIS-1142
Change backend domain for hmi-apim
```
[ ] Yes
[x] No
```
=> HMIS-1142 - backend_doman change

environments/demo/demo.tfvars, environments/ithc/ithc.tfvars, environments/test/test.tfvars
=> Updated application name

environments/demo/demo.tfvars
This change:
- Adds third batch of applications to demo FD:
- Relies on:
- DNS: https://github.com/hmcts/azure-public-dns/pull/1131
- Flux: https://github.com/hmcts/cnp-flux-config/pull/21899
```
[ ] Yes
[ ] No
```
=> Add third batch demo apps

environments/demo/demo.tfvars
This change:
- Adds fifth batch of demo apps to new setup (second to last 🕺🏻 )
- Requires:
- DNS: https://github.com/hmcts/azure-public-dns/pull/1139
- Flux: https://github.com/hmcts/cnp-flux-config/pull/21959
```
[ ] Yes
[ ] No
```
=> Add fifth batch demo apps to migrate

.github/CODEOWNERS
Adding init.tf files
```
[ ] Yes
[x] No
```
=> Add init.tf files to ignore list CODEOWNERS

environments/prod/prod.tfvars
https://tools.hmcts.net/jira/browse/PRL-2882
Creating azure front door config for Private law
```
[ ] Yes
[x] No
```
=> Private law Azure front door

environments/sbox/sbox.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-12511
Update safe settings health probe path to correct endpoint
```
[ ] Yes
[x] No
```
=> DTSPO-12511 - Update safe settings health path

environments/prod/backend_lb_config.yaml
=> add notifications service

azure_pipeline.yaml
=> prod disable

azure_pipeline.yaml
=> plum fixed enable tests

environments/demo/backend_lb_config.yaml
SDT-112 (https://tools.hmcts.net/jira/browse/SDT-112)
Added SDT apps to demo backend load balancer configuration.
```
[ ] Yes
[x] No
```
=> Add SDT apps to demo

environments/demo/backend_lb_config.yaml, environments/ithc/backend_lb_config.yaml, environments/prod/backend_lb_config.yaml, environments/stg/backend_lb_config.yaml, environments/test/backend_lb_config.yaml
DFR-1997
Decommission-notification-serivce - this service has been absorb in finrem-case-orchestration-service
```
[ ] Yes
[ x] No
```
=>  DFR-1997: decommission-notification-serivce

environments/prod/prod.tfvars
Exclude the return url arg
```
[ ] Yes
[x] No
```
=> PCQ: Exclude return url

environments/demo/backend_lb_config.yaml, environments/ithc/backend_lb_config.yaml, environments/prod/backend_lb_config.yaml, environments/stg/backend_lb_config.yaml, environments/test/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/ST-1300
```
[ ] Yes
[ ] No
```
=> sptribs_frontend has been implemented

azure_pipeline.yaml
In order to make sure that this module change does not break production environment, turned off production environment from the pipeline
https://github.com/hmcts/cnp-module-api-mgmt-private/pull/37
```
[ ] Yes
[ X ] No
```
=> commented staging and production apim update

environments/ithc/ithc.tfvars
https://tools.hmcts.net/jira/browse/ST-1300
```
[ ] Yes
[ ] No
```
=> sptribs-frontend / ithc.tfvars

environments/stg/stg.tfvars
https://tools.hmcts.net/jira/browse/PCQ-1724
This is to change AAT back to prevention mode same as pod , it was changed for make a plea testing
```
[ ] Yes
[x] No
```
=> Update stg.tfvars to change pcq aat to Prevention as same as prod

azure_pipeline.yaml
Update to a valid service connection
```
[ ] Yes
[X] No
```
=> Update to a valid service connection

environments/demo/backend_lb_config.yaml, environments/ithc/backend_lb_config.yaml, environments/prod/backend_lb_config.yaml, environments/stg/backend_lb_config.yaml, environments/test/backend_lb_config.yaml
Add et-hearings-api to backend lb config
```
[ ] Yes
[ ] No
```
=> ET Hearings API

environments/demo/backend_lb_config.yaml, environments/demo/demo.tfvars, environments/ithc/backend_lb_config.yaml, environments/prod/backend_lb_config.yaml, environments/stg/backend_lb_config.yaml, environments/test/backend_lb_config.yaml, environments/test/test.tfvars
https://tools.hmcts.net/jira/browse/ST-1300
Remove sptribs-frontend from load balancer multiple envs.
Added/amended sptribs-frontend app Front Door config in Demo and Perftest envs.
```
[ ] Yes
[x] No
```
=> Amend ST config for frontend app multiple envs

environments/test/test.tfvars
fix sptribs perftest
```
[ ] Yes
[X] No
```
=> fix sptribs perftest

environments/prod/prod.tfvars
=> take out prod-00

environments/prod/prod.tfvars
take prod01 out of AGW
```
[ ] Yes
[X] No
```
=> take prod01 out of AGW

environments/prod/prod.tfvars
=> Revert "take prod01 out of AGW"

components/backendappgateway/main.tf, components/frontendappgateway/main.tf, environments/prod/prod.tfvars, environments/variables.tf
=> Change application gateway min nodes

environments/demo/backend_lb_config.yaml, environments/ithc/backend_lb_config.yaml, environments/prod/backend_lb_config.yaml, environments/stg/backend_lb_config.yaml, environments/test/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/IJPS-37
Added entry for JPS
```
[ ] Yes
[ x] No
```
=> IJPS-37: Added entry for JPS

azure_pipeline.yaml
=> temp disable pipeline tests for p1

environments/demo/backend_lb_config.yaml, environments/ithc/backend_lb_config.yaml, environments/test/backend_lb_config.yaml
SDT-122 (https://tools.hmcts.net/jira/browse/SDT-122) - perftest
- Added all SDT apps to ithc and perftest backend load balancer configurations.
- Added civil-sdt-commissioning to demo backend load balancer configuration.
```
[ ] Yes
[x] No
```
=> Add SDT apps to demo, ithc and perftest

components/backendappgateway/main.tf, components/frontendappgateway/main.tf, environments/prod/prod.tfvars, environments/variables.tf
=> Further scale up min nodes for prod appgws

environments/prod/backend_lb_config.yaml
=> Move activity API to different gateway

environments/stg/stg.tfvars
https://tools.hmcts.net/jira/browse/PCQ-1753
Unblocking iss
```
[ ] Yes
[x] No
```
=> Update stg.tfvars for PCQ

.gitignore, components/shutter/local.tf, components/shutter/module_shutter.tf, environments/prod/prod.tfvars
Add local for shutter_apps
Brings this repo in line with sds
This ensures an error does not occur when shutter_apps is set to false
```
[ ] Yes
[x] No
```
=> Add local for shutter

azure_pipeline.yaml, components/apim/main.tf, environments/prod/prod.tfvars, environments/stg/stg.tfvars, environments/variables.tf
DTSPO-14138
Add-Custom Gateway to cftapps
```
[ ] Yes
[ X] No
```
=> Add-Custom Gateway to cftapps

environments/prod/prod.tfvars
=> remove cluster 00 for rebuild

environments/test/test.tfvars
DTSPO-12900
Remove perftest 00 from AGW
```
[ ] Yes
[ x ] No
```
=> remove perftest 00 from agw

environments/prod/prod.tfvars
=> Shutter plum app for testing static webapp solution

components/apim-appgw/local.tf, components/apim/local.tf, migrate-appgateway.md
https://tools.hmcts.net/jira/browse/DTSPO-14595
Removed ukwest entries from the files that were associated with ukw.
```
[ ] Yes
[x] No
```
=> Removed ukwest entries

components/shutter_static_webapp/static_webapp.tf
passing env variable to module
=> dtspo-14285 update shutter static web app

azure_pipeline.yaml, components/shutter_static_webapp/static_webapp.tf, environments/prod/prod.tfvars
=> Create Static webapp for prod env

environments/demo/demo.tfvars, environments/ithc/ithc.tfvars, environments/prod/prod.tfvars, environments/sbox/sbox.tfvars, environments/stg/stg.tfvars, environments/test/test.tfvars
https://tools.hmcts.net/jira/browse/SIDM-8809
code verifier
```
[ ] Yes
[X] No
```
=> SIDM-8809 code verifier

environments/test/test.tfvars
DTSPO-12900
Re-add perftest 00 back to AGW
```
[ ] Yes
[ x ] No
```
=> re-add perftest 00 back to agw

environments/ithc/ithc.tfvars
Reverts hmcts/azure-platform-terraform#1626
=> Revert "ITHC: Remove ithc01 internal LB to allow for AKS patch 1.26"

environments/test/test.tfvars
DTSPO-12900
Remove perftest 01 from AGW
```
[ ] Yes
[ x ] No
```
=> Upgrade perftest

environments/demo/backend_lb_config.yaml, environments/ithc/backend_lb_config.yaml, environments/stg/backend_lb_config.yaml, environments/test/backend_lb_config.yaml
=> adding civil orchestrator service

environments/stg/stg.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-12903
* Remove aat01 for AKS patch GA version 1.26
```
[ ] Yes
[x] No
```
=> AAT: Remove aat01 for AKS patch GA version 1.26

environments/stg/stg.tfvars
Reverts hmcts/azure-platform-terraform#1643
=> Revert "AAT: Remove aat01 for AKS patch GA version 1.26"

environments/stg/stg.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-12903
* Remove AAT-00 for AKS patch GA version 1.26
```
[ ] Yes
[x] No
```
=> AAT: Remove AAT-00 for AKS patch GA version 1.26

environments/demo/demo.tfvars
DTSPO-12902
```
[ ] Yes
[ ] No
```
=> Remove Demo01 - AKS upgrades

environments/stg/stg.tfvars
Reverts hmcts/azure-platform-terraform#1646
=> Revert "AAT: Remove AAT-00 for AKS patch GA version 1.26"

environments/demo/demo.tfvars
[DTSPO-12902](https://tools.hmcts.net/jira/browse/DTSPO-12902)
```
[ ] Yes
[ ] No
```
=> Remove demo01 cluster for aks upgrades

environments/demo/demo.tfvars
DTSPO-12902
```
[ ] Yes
[ ] No
```
=> Remove Demo 00 for aks upgrade

environments/demo/demo.tfvars
Reverts hmcts/azure-platform-terraform#1653 - code change done in https://github.com/hmcts/aks-cft-deploy/pull/498/files
=> Revert "Remove Demo 00 for aks upgrade"

environments/demo/demo.tfvars, environments/ithc/ithc.tfvars, environments/prod/prod.tfvars, environments/sbox/sbox.tfvars, environments/stg/stg.tfvars, environments/test/test.tfvars
https://tools.hmcts.net/jira/browse/SIDM-8663
exclude csrf cookie
```
[ ] Yes
[X] No
```
=> SIDM-8663 csrf cookie

components/shutter_static_webapp/static_webapp.tf, components/shutter_static_webapp/variables.tf, environments/prod/prod.tfvars, environments/sbox/sbox.tfvars
=> update static web app sku

components/shutter_static_webapp/static_webapp.tf, components/shutter_static_webapp/variables.tf, environments/prod/prod.tfvars, environments/sbox/sbox.tfvars
=> shutter Web App: Add a sku_size variable

environments/sbox/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/SIDM-8836
Setup idam-user-profile-bridge
```
[ ] Yes
[X] No
```
=> SIDM-8836 Setup idam-user-profile-bridge

azure_pipeline.yaml
=> DTSPO-13833 updating pat-token to use SP-token

components/apim-appgw/download_root_certs.bash, components/apim-appgw/local.tf, components/apim-appgw/main.tf, environments/sbox/apim_appgw_config.yaml
- [ X] commit messages are meaningful and follow good commit message guidelines
https://tools.hmcts.net/jira/browse/DTSPO-14843
Inline this repo with APIM App-Gateway module to SSL certificate download dynamically.
```
[ ] Yes
[ X] No
```
=> added downloading root cert changes

environments/demo/backend_lb_config.yaml, environments/ithc/backend_lb_config.yaml, environments/stg/backend_lb_config.yaml, environments/test/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/SIDM-8836
Add idam-user-profile-bridge to AAT, Demo, ITHC, Perftest backend LBs configurations.
```
[ ] Yes
[x] No
```
=> Backend LB config for idam-user-profile-bridge

environments/test/test.tfvars
disable cache on manage-case.perftest FD URL
```
[ ] Yes
[X] No
```
=> disable cache on manage-case.perftest FD URL

environments/prod/prod.tfvars
Reverts hmcts/azure-platform-terraform#1694
=> Revert "disable manage-case FD cache - Production"

environments/prod/prod.tfvars
adding change back in to test between 12 and 5
=> Revert "Revert "disable manage-case FD cache - Production""

environments/demo/demo.tfvars
disable FD cache for manage-case demo and demo-int
```
[ ] Yes
[X] No
```
=> disable FD cache for manage-case demo and demo-int

environments/prod/prod.tfvars
=> shutter-pet-apps

azure_pipeline.yaml, components/apim-appgw/init.tf, components/apim-appgw/local.tf, components/apim-appgw/main.tf, environments/sbox/sbox.tfvars, environments/test/apim_appgw_config.yaml, environments/test/test.tfvars, environments/variables.tf
add apim perftest appgw
```
[ ] Yes
[X] No
```
=> add apim perftest appgw

components/apim-appgw/main.tf, components/apim-appgw/root_certs.tf
multiple certs for apim appgw
```
[ ] Yes
[X] No
```
=> multiple certs for apim appgw

environments/demo/backend_lb_config.yaml, environments/demo/demo.tfvars
=> add in demo et config

environments/demo/backend_lb_config.yaml, environments/prod/backend_lb_config.yaml, environments/stg/backend_lb_config.yaml
=> fix backends

components/apim-appgw/main.tf, components/apim-appgw/root_certs.tf, environments/sbox/apim_appgw_config.yaml, environments/test/apim_appgw_config.yaml
multiple ssl certs on appgw apim
```
[ ] Yes
[X] No
```
=> multiple ssl certs on appgw apim

environments/demo/demo.tfvars, environments/stg/stg.tfvars
=> add in fd config for datacapture

environments/prod/prod.tfvars
=> et-test-whitelist

environments/prod/prod.tfvars
=> switch to keyvault

environments/prod/prod.tfvars
=> new cookies

environments/stg/backend_lb_config.yaml, environments/stg/stg.tfvars
=> Add help with fees FEs and API

environments/stg/stg.tfvars
=> Add help with fees cookie exepts aat

environments/demo/backend_lb_config.yaml, environments/demo/demo.tfvars
=> Demo help with fees FE & api conf & cookie exepts

components/global/main.tf, environments/sbox/sbox.tfvars, environments/variables.tf
https://tools.hmcts.net/jira/browse/DTSPO-13990 
Test frontend to test the migration to premium/standard 
```
[ ] Yes
[X ] No
```
=> deploying new classic frontdoor to sbox

components/global/main.tf, environments/sbox/sbox.tfvars
Reverting frontdoor deployement
=> reverted frontdoor to allow prod build

components/global/main.tf, environments/sbox/sbox.tfvars
In the last attempt, Frontdoor deployed but with error here - 
https://dev.azure.com/hmcts/PlatformOperations/_build/results?buildId=438027&view=logs&j=bc94ff9d-672b-57db-ec5a-c9ee377acb4a&t=23d6abd6-34c1-5a62-59b0-8f550538cfca 
So going to try and deploy frontdoor after applying fix on the module here
https://github.com/hmcts/terraform-module-frontdoor/compare/master...remove-retention-days
=> deployed after updating the module

environments/stg/stg.tfvars
=> HWF address lookup stg.tfvars

environments/stg/stg.tfvars
=> Stg help with fees lookup exepts

components/global/main.tf, environments/sbox/sbox.tfvars, environments/variables.tf
removing test frontdoor
https://tools.hmcts.net/jira/browse/DTSPO-13990
=> removed test frontdoor

environments/stg/backend_lb_config.yaml
=> Update HWF api backend_lb_config.yaml

environments/prod/backend_lb_config.yaml, environments/prod/prod.tfvars, environments/stg/stg.tfvars
=> PROD Hwf WAF conf & LB

environments/prod/prod.tfvars
=> PROD help with fees zone name update

environments/sbox/sbox.tfvars
[DTSPO-14200](https://tools.hmcts.net/jira/browse/DTSPO-14200)
Removing cluster for aks upgrade 1.27
```
[ ] Yes
[x] No
```
=> remove cluster for upgrade

environments/sbox/sbox.tfvars
JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/DTSPO-14200
Upgrading cft sbox 01 cluster 
```
[ ] Yes
[x] No
```
=> removing sbox 01

environments/test/apim_appgw_config.yaml
add add_rewrite_rule true for mtls appgw
```
[ ] Yes
[X] No
```
=> add add_rewrite_rule true for mtls appgw

environments/test/apim_appgw_config.yaml
N/A
Remove rewrite rule flag for mtls app gateway in perftest environment.  Will be re-added afterwards to trigger a rebuild.
```
[ ] Yes
[x] No
```
=> Remove rewrite rule flag for mtls app gateway

environments/variables.tf
add variable default to fix tagging pipeline 
```
[ ] Yes
[x] No
```
=> add variable default

environments/test/apim_appgw_config.yaml
N/A
Re-added rewrite rule flag for mtls app gateway in perftest environment.
```
[ ] Yes
[x] No
```
=> Add rewrite rule flag for mtls app gateway

components/apim-appgw/.terraform.lock.hcl, components/apim-appgw/init.tf, components/apim/init.tf, components/backendappgateway/provider.tf, components/cftapps_private_dns/provider.tf, components/dynatrace_activegate/provider.tf, components/frontendappgateway/provider.tf, components/global/provider.tf
Reverts hmcts/azure-platform-terraform#1553
=> Revert "Update Terraform azurerm to v3.74.0"

environments/demo/backend_lb_config.yaml, environments/ithc/backend_lb_config.yaml, environments/prod/backend_lb_config.yaml, environments/sbox/backend_lb_config.yaml, environments/stg/backend_lb_config.yaml, environments/test/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/RIA-7910
ia-hearings-api is a new component being developed for HMC integration. 
- [X ] commit messages are meaningful and follow good commit message guidelines
=> Updates to add new IA component ia-hearings-api

environments/sbox/sbox.tfvars
Adding fortend to sbox frontdoor with APEX domain to test..
=> added frotend apex

environments/sbox/sbox.tfvars
Reverts hmcts/azure-platform-terraform#1769
=> Revert "added frotend apex"

environments/sbox/sbox.tfvars
This is attempt 2 to add test APEX domain to sbox frontdoor.
=> adding test APEX frontend

environments/sbox/sbox.tfvars
Test - 3 - with frontdoor domain
=> testing with fd domain

environments/sbox/sbox.tfvars
=> updated custom domain

azure_pipeline.yaml
https://tools.hmcts.net/jira/browse/DTSPO-13994
Turning off sbox_global stage while finishing off the import process
=> turning off sbox global while finishing with impor

environments/test/apim_appgw_config.yaml
SDT-115 (https://tools.hmcts.net/jira/browse/SDT-115)
Corrected server variable name in rewrite_rules conditions/variable property in perftest appgw configuration.
=> Corrected server variable name in perftest appgw config

environments/demo/demo.tfvars
[DTSPO-14196](https://tools.hmcts.net/jira/browse/DTSPO-14196)
Removing cluster from appgw
=> remove-cluster-from-appgw-for-upgrade

environments/demo/demo.tfvars
[DTSPO-14198](https://tools.hmcts.net/jira/browse/DTSPO-14198)
Re-adding appgw after cluster demo-00 version upgrade 1.27
=> re-add-appgw

environments/demo/demo.tfvars
[DTSPO-14198](https://tools.hmcts.net/jira/browse/DTSPO-14198)
Removing appgw demo-01 cluster for upgrade
=> remove-appgw-for-cluster-upgrade

environments/demo/demo.tfvars
[DTSPO-14198](https://tools.hmcts.net/jira/browse/DTSPO-14198)
Re-adding appgw after cluster upgrade 1.27
=> Dtspo 14198 demo 01 upgrade

components/global/diagnostics.tf, components/global/provider.tf
Will be used instead of log analytics for high traffic logs we don't access very much
=> Add diagnostics storage account

environments/ithc/ithc.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-14197
remove app gw for cft ith 00 to upgrade to  version 1.27.
=> remove app gw for cft ith 00 to upgrade

components/backendappgateway/diagnostics.tf, components/backendappgateway/main.tf, components/frontendappgateway/diagnostics.tf, components/frontendappgateway/main.tf
Follow on to https://github.com/hmcts/sds-azure-platform/pull/576
=> Send App gateway logs to storage account

environments/stg/stg.tfvars
[DTSPO-14199](https://tools.hmcts.net/jira/browse/DTSPO-14199)
R-adding appgw after cluster-00 upgrade 1.27
=> re-add-appgw-cluster-upgrade

environments/stg/stg.tfvars
https://github.com/hmcts/azure-platform-terraform/pull/new/DTSPO-14199-cluster-01-ugrade
Removing appgw for cluster cft-aat-01 upgrade
=> remove-appgw-cluster-upgrade

environments/stg/stg.tfvars
[DTSPO-14199](https://tools.hmcts.net/jira/browse/DTSPO-14199)
Re-adding appgw after cluster upgrade 1.27
=> Dtspo 14199 cluster ugr

azure_pipeline.yaml, environments/ithc/ithc.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-15146
upgraded ithc frontdoor to premium
- [ X ] commit messages are meaningful and follow good commit message guidelines
=> DTSPO-15146 upgraded ithc frontdoor to premium

azure_pipeline.yaml, environments/test/test.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-15146
upgraded perftest to premium
- [X ] commit messages are meaningful and follow good commit message guidelines
=> DTSPO-15146 - upgraded perftest to premium

environments/test/test.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-15146
Fixed backend issue which is using backed value rather than backend domain
- [ X] commit messages are meaningful and follow good commit message guidelines
=> DTSPO-15146 - fix the backend issue with nfdiv

environments/ithc/ithc.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-14197
re-adding app gw after upgrading cft-ithc 00 cluster to version 1.27.
=> re-adding app gw for cft-ithc 00 cluster

environments/ithc/ithc.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-14197
removing app GW for cft-itch 01 ckuster for an upgrade
=> re-move app gw for cft-ithc 01 cluster

environments/test/test.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-14196
Removing appgw for cluster cft-perftest-00 upgrade
=> DTSPO-14196: Remove appgw cluster

environments/ithc/ithc.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-14197
Re-add CFT-ITHC 01 app gw after upgrading aks to version 1.27
=> adding app gw back for cft-ithc 01

azure_pipeline.yaml
https://tools.hmcts.net/jira/browse/DTSPO-15147
switching off AAT front door for migration to premium.
=> switching off AAT frontdoor for migration

azure_pipeline.yaml, environments/stg/stg.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-15147
AAT frontdoor migrated and imported to terraform.
=> DTSPO-15147 upgraded AAT frontdoor to premium

environments/test/test.tfvars
Reverts hmcts/azure-platform-terraform#1815
=> Revert "DTSPO-14196: Remove IP for 01"

environments/prod/prod.tfvars
[DTSPO-14195](https://tools.hmcts.net/jira/browse/DTSPO-14195)
Removing appgw for cluster upgrade 1.27
=> remove-appgw-00

environments/prod/prod.tfvars
Reverts hmcts/azure-platform-terraform#1826
=> Revert "remove-appgw-00"

environments/prod/prod.tfvars
[DTSPO-14195](https://tools.hmcts.net/jira/browse/DTSPO-14195)
Removing appgw for cluster 01 upgrade 1.27
=> Dtspo 14195 cft 01 cluster upgrade

environments/prod/prod.tfvars
Reverts hmcts/azure-platform-terraform#1828
=> Revert "Dtspo 14195 cft 01 cluster upgrade"

environments/prod/prod.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-15318
CNAME to be added in https://github.com/hmcts/azure-public-dns/pull/1402
This adds a redirect to front door to reach new external url with app proxy
=> DTSPO-15318: Add redirect sds sbox jenkins

environments/prod/prod.tfvars
Reverts hmcts/azure-platform-terraform#1834 -- This needs to go in SDS-azure-platform instead
=> Revert "DTSPO-15318: Add redirect sds sbox jenkins"

environments/prod/prod.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-15305
Need to have the redirect from  platform.hmcts.net to gov.uk.
=> Adoption DNS-Creation-added entry for adoption public beta release

environments/demo/demo.tfvars
https://tools.hmcts.net/jira/browse/NFDIV-3768
Add nfdiv demo config
=> NFDIV-3768: Add nfdiv demo config

environments/ithc/ithc.tfvars
=> Added et-pet to ithc

environments/ithc/ithc.tfvars
=> Bug fix - incorrect backend for palo for et-pet

environments/prod/prod.tfvars
[DTSPO-15318](https://tools.hmcts.net/jira/browse/DTSPO-15318)
Adds front door redirects for old url to app proxy URLS
=> DTSPO-15318: Add front door redirects for CFT PTL jenkins

environments/sbox/sbox.tfvars
Adding frontend record for goldenpath frontdoor setup
=> Adding frontend record for goldenpath frontdoor setup - mfox

environments/demo/demo.tfvars
=> Adding new domain for ocmc

environments/demo/demo.tfvars
=> Removing CUI and OCMC entries

environments/demo/demo.tfvars
=> Adding CUI and OCMC entries

environments/sbox/sbox.tfvars
This is test on the Sandbox environment to see if it throws error when removing custom domains.
=> testing app removal from migrated frontdoors

environments/ithc/ithc.tfvars
=> Fixes to et3 and admin for pet-et

environments/ithc/backend_lb_config.yaml
=> ET API backend config

environments/demo/demo.tfvars, environments/dev/dev.tfvars, environments/prod/prod.tfvars, environments/sbox/sbox.tfvars, environments/stg/stg.tfvars, environments/test/test.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-15708
To fix the login issue on the reform storage account.
=> DTSPO-15708 - fixing SA login issue

azure_pipeline.yaml
https://tools.hmcts.net/jira/browse/DTSPO-15147
Turn off prod frontdoor to prepare it for Frontdoor migration
=> DTSPO-15147 - turn off prod frontdoor

environments/stg/stg.tfvars
=> adding in new value for staging

components/global/main.tf
https://tools.hmcts.net/jira/browse/DTSPO-13992
Updated Frontdoor branch
=> updated frontdoor module branch

environments/ithc/ithc.tfvars, environments/prod/prod.tfvars, environments/sbox/sbox.tfvars, environments/stg/stg.tfvars, environments/test/test.tfvars
https://tools.hmcts.net/jira/browse/SIDM-8998
ignore query string csrf
=> SIDM-8998 idam-user-dashboard ignore query string csrf

environments/sbox/sbox.tfvars
[DTSPO-16046](https://tools.hmcts.net/jira/browse/DTSPO-16046)
Adding ngfw test fd
=> add ngfw test

environments/ithc/ithc.tfvars
This reverts commit db9237bb037bcda092f5648a9de99c2e288fc4b6.
=> Revert "Temporarily disabling ITHC firewall rules for ET-PET ITHC testing (#1892)"

environments/sbox/sbox.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-16054
Removing sbox 01 AKS cluster from the Azure LB so it can be upgraded.
=> Remove 01 cluster from lb for upgrade

environments/sbox/sbox.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-15840
remove app gw sbox 00 for upgrade
=> remove app gw cft sbox 00

azure_pipeline.yaml
=> Point back to master branch for ADO library

environments/prod/prod.tfvars
ST
REfactoring config to correct urls and add www redirect of true
=> ST - refactor frontend config

environments/prod/prod.tfvars
=> ST - Added Exclusions for WAF

environments/sbox/sbox.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-15840
RE-ADD-APP-GW-CFT-SBOX-00
=> add appgw back for sbox cft 00

environments/prod/prod.tfvars
ST - Added Exclusions for WAF - exclude sptribs-cookie-preferences
=> ST - Added Exclusions for WAF - exclude sptribs-cookie-preferences

environments/prod/prod.tfvars
ST DSS Create Case CIC Release
Exclude _crsf WAF blocks
=> ST - refactor frontend config to exclude _csrf

environments/test/test.tfvars
[DTSPO-15845](https://tools.hmcts.net/jira/browse/DTSPO-15845)
removing appgw cluster 00 for version upgrade
=> remove appgw cluster 00 for version upgrade

environments/test/test.tfvars
Reverts hmcts/azure-platform-terraform#1929
=> Revert "remove appgw cluster 00 for version upgrade"

environments/test/test.tfvars
[DTSPO-15845](https://tools.hmcts.net/jira/browse/DTSPO-15845)
removing appgw cluster 01 aks version upgrade
=> remove appgw cluster 01 version upgrade v1.28

environments/test/test.tfvars
Reverts hmcts/azure-platform-terraform#1932
=> Revert "remove appgw cluster 01 version upgrade v1.28"

environments/demo/demo.tfvars
Reverts hmcts/azure-platform-terraform#1935
=> Revert "remove appgw cluster 00 version upgrade v1.28"

environments/demo/demo.tfvars
[DTSPO-15847](https://tools.hmcts.net/jira/browse/DTSPO-15847)
removing appgw for version upgrade cft-demo-01
=> remove appgw for version upgrade

environments/demo/demo.tfvars
Reverts hmcts/azure-platform-terraform#1937
=> Revert "remove appgw for version upgrade"

azure_pipeline.yaml, environments/prod/apim_appgw_config.yaml, environments/prod/prod.tfvars
SDT-115 (https://tools.hmcts.net/jira/browse/SDT-115)
- Added environments/prod/apim_appgw_config.yaml file.  This contains application gateway configuration for production environment.
- Updated environments/prod/prod.tfvars file with additional properties needed by application gateway configuration.
=> SDT-115: Added production app gateway config

environments/stg/stg.tfvars
[DTSPO-15848](https://tools.hmcts.net/jira/browse/DTSPO-15848)
removing appgw for aks version upgrade
=> remove appgw for aks version upgrade

environments/stg/stg.tfvars
Reverts hmcts/azure-platform-terraform#1940
=> Revert "remove appgw for aks version upgrade"

environments/stg/stg.tfvars
[DTSPO-15848](https://tools.hmcts.net/jira/browse/DTSPO-15848)
removing appgw for version upgrade v1.28
=> remove appgw for version upgrade v1.28

environments/prod/apim_appgw_config.yaml, environments/prod/prod.tfvars
Currently pipeline fails
`Private static IP address 10.11.8.192 falls within reserved IP range of subnet prefix 10.11.8.192/27`
=> Update APIM prod AppGW to correct IP

environments/stg/stg.tfvars
Reverts hmcts/azure-platform-terraform#1944
=> Revert "remove appgw for version upgrade v1.28"

environments/prod/prod.tfvars
* add postParamName WAF exception in prod for TT-PET
=> tt-pet: add postParamName WAF exception for prod

environments/prod/prod.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-15778
To be merged after https://github.com/hmcts/azure-public-dns/pull/1575
Adds redirect from old -> new URL for backstage
Similar done for jenkins in https://github.com/hmcts/azure-platform-terraform/pull/1841
=> DTSPO-15788: Add fd redirect for backstage

environments/prod/prod.tfvars
(https://tools.hmcts.net/jira/browse/DTSPO-15844)
CR - CHG5014847 - remove app GW for prod 00
=> removing-app-gw-prod-00

environments/prod/prod.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-15844
re-add app gw for prod-00
=> adding back app gw prod 00

environments/prod/prod.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-15844
removing app gw for prod 01
=> removing app gw for prod 01

environments/stg/stg.tfvars
https://tools.hmcts.net/jira/browse/SSCSCI-650
Align the firewall settings of AAT to match production for SYA and MYA
=> SSCSCI-650 - Align the firewall settings of AAT to match production

environments/prod/prod.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-16416
* remove exclusion postParamName as this is non-functional
* add custom rule for PostParamName to test
=> TT: remove exclusion postParamName, add custom PostParamName

azure_pipeline.yaml, components/apim-appgw/main.tf
Changed application gateway component Terraform file to reference main branch of terraform-module-apim-application-gateway repository.
Temporarily commented out prod_apim_appgw section of azure_pipeline.yaml to prevent current production configuration being overwritten.
This change must only be merged after https://github.com/hmcts/terraform-module-apim-application-gateway/pull/20 has been merged.
=> Changed App Gateway component branch ref back to main

environments/prod/prod.tfvars
=> Fixed incorrect whitelist configuration for et1

environments/prod/prod.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-16416
* disable default rule _DefaultRuleSet-1.0-SQLI-942110_ in prod WAF for TT
=> Tax Tribunals: disable rule SQLI-942110 in prod WAF for TT

environments/demo/demo.tfvars, environments/ithc/ithc.tfvars, environments/stg/stg.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-16416
* Add disabled_rules for Tax Tribunals WAFs in lower envs to match prod
=> Add disabled_rules for Tax Tribunals WAFs in lower envs to match prod

azure_pipeline.yaml, components/apim-appgw/main.tf, environments/prod/apim_appgw_config.yaml, environments/sbox/apim_appgw_config.yaml, environments/test/apim_appgw_config.yaml
Changed appim-appgw/main.tf to reference backend-http-settings-host-name-refactor branch of terraform-module-apim-application-gateway repository.
Removed backend_host_name_override properties from production and perftest application gateway configuration files.
Removed listener properties from sandbox application gateway configuration file.
=> Update App Gateway config in line with refactoring

environments/sbox/sbox.tfvars
DTSPO-16046
amending name to test poc issue
=> amend name to test poc issue

environments/sbox/sbox.tfvars
DTSPO-16046
amending custom domain to test poc issue
=> Dtspo 16046 ngfw poc

environments/sbox/backend_lb_config.yaml, environments/sbox/sbox.tfvars
DTSPO-16046
Amend component name for ngfw poc
=> DTSPO-16046 ngfw poc

environments/stg/backend_lb_config.yaml
N/A
Added SDT apps to AAT load balancer config
=> Added SDT apps to AAT load balancer config

environments/sbox/backend_lb_config.yaml, environments/sbox/sbox.tfvars
DTSPO-16046
Adding frontend for ngfw poc lab
=> DTSPO-16046

environments/sbox/sbox.tfvars
DTSPO-16046 amend backend domain name
amend backend domain name
=> DTSPO-16046 amend backend domain name

environments/demo/demo.tfvars, environments/ithc/ithc.tfvars, environments/stg/stg.tfvars, environments/test/test.tfvars
https://tools.hmcts.net/jira/browse/DTSSTCI-403
Configure sptribs-dss-update-case-web DNS for lower envs
NOTE: Changing mode to "protection" to come in next sprint
=> DTSSTCI-403

environments/sbox/backend_lb_config.yaml, environments/sbox/sbox.tfvars
[DTSPO-16903](https://tools.hmcts.net/jira/browse/DTSPO-16903)
remove unused labs
=> DTSPO-16903-remove unused labs

environments/demo/demo.tfvars, environments/ithc/ithc.tfvars, environments/prod/prod.tfvars, environments/stg/stg.tfvars
https://tools.hmcts.net/jira/browse/CUIRA-233
Add CUI-RA WAF exclusions
=> Add CUI exclusions

environments/prod/prod.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-17043
Update custom_domain for cui-ra to include www.
=> Update cui-ra custom domain

environments/demo/demo.tfvars, environments/ithc/ithc.tfvars, environments/prod/prod.tfvars, environments/stg/stg.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-17067
Suppress false positive for WAF
=> DTSPO-17067 - Suppress false positives

environments/demo/demo.tfvars, environments/ithc/ithc.tfvars, environments/test/test.tfvars
Use rules from AAT across all test envs and enable Prevention mode for WAF for NFD service domains.
=> Enable Prevention for WAF mode and copy AAT exclusions

environments/demo/demo.tfvars, environments/ithc/ithc.tfvars, environments/stg/stg.tfvars, environments/test/test.tfvars
seeing another blocked request in the firewall, adding exclusion for it on base domain.
=> Add another exclusion to base domain for NFD

environments/demo/demo.tfvars, environments/ithc/ithc.tfvars, environments/stg/stg.tfvars, environments/test/test.tfvars
copy rules onto base domain as well as the custom domains as i'm seeing repeat rule issues for that area in WAF logs.
=> NFD - Add rules to base host for nfd

environments/stg/stg.tfvars
https://tools.hmcts.net/jira/browse/DTSSTCI-394
Update exclusions for SpTribs in AAT and update WAF to be in prevention mode in AAT for SpTribs
=> DTSSTCI-394

environments/prod/prod.tfvars
Testing in lower envs has been successful. Applying rules to prod.
=> Apply WAF rule exceptions to NFD prod

environments/demo/demo.tfvars, environments/ithc/ithc.tfvars, environments/test/test.tfvars
https://tools.hmcts.net/jira/browse/PCQ-1879
Enable prevention mode for demo,ithc,test. staging and production is already in prevention
=> PCQ-1879enable Prevention mode for demo,ithc and testing

environments/prod/prod.tfvars
Reverts hmcts/azure-platform-terraform#2032
=> Revert "Apply WAF rule exceptions to NFD prod"

environments/stg/stg.tfvars
Run staging tests via FrontDoor for idam-user-dashboard and idam-hmcts-access
=> SIDM-9140 staging via frontdoor

environments/demo/demo.tfvars, environments/ithc/ithc.tfvars, environments/prod/prod.tfvars, environments/stg/stg.tfvars, environments/test/test.tfvars
https://tools.hmcts.net/jira/browse/LAU-843
Switch Detection mode to Prevention for Log&Audit
=> LAU-843 enable prevention mode on LAU

environments/demo/demo.tfvars, environments/ithc/ithc.tfvars, environments/prod/prod.tfvars, environments/stg/stg.tfvars, environments/test/test.tfvars
LAU-843
allow iss query param to allow idam login
=> LAU-843 allow iss query param to allow idam login

environments/demo/demo.tfvars, environments/ithc/ithc.tfvars, environments/sbox/sbox.tfvars, environments/stg/stg.tfvars, environments/test/test.tfvars
[SIDM-9126](https://tools.hmcts.net/jira/browse/SIDM-9126)
Moving hmcts-access to Prevention mode
=> Change hmcts-access to Prevention

environments/demo/demo.tfvars, environments/ithc/ithc.tfvars, environments/sbox/sbox.tfvars, environments/stg/stg.tfvars, environments/test/test.tfvars
https://tools.hmcts.net/jira/browse/SIDM-9126
Add default exclusions to idam-hmcts-access WAF policies.
=> Add exclusions to hmcts-access WAF policy

environments/demo/demo.tfvars, environments/ithc/ithc.tfvars, environments/sbox/sbox.tfvars, environments/stg/stg.tfvars, environments/test/test.tfvars
https://tools.hmcts.net/jira/browse/SIDM-9126
More exclusions.
=> Exclusions for hmcts-access WAF policy

components/dynatrace_activegate/nonprod-private.tf, components/dynatrace_activegate/prod.tf
https://tools.hmcts.net/jira/browse/DTSPO-16138
Remove activegates from state
These have been moved to hmcts/dynatrace-activegate
Will raise a new PR to delete the component and module files
=> DTSPO-16138 - Remove dynatrace activegates

environments/sbox/sbox.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-16593
Remove sbox 00 cluster
=> DTSPO-16593 - remove sbox 00 cluster

environments/sbox/sbox.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-16593
Remove sbox01 from Appgateway
=> DTSPO-16593 - remove sbox 01

environments/sbox/sbox.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-16593
Remove 01
=> DTSPO-16593 - remove 01

environments/demo/demo.tfvars
Remove demo 00 from the appgateway
=> DTSPO-16594 - remove demo 00 from appgateway

environments/demo/demo.tfvars
Reverts hmcts/azure-platform-terraform#2067
=> Revert "DTSPO-16594 - remove demo 00 from appgateway"

environments/demo/demo.tfvars
Removing demo01 cluster for uprade
=> DTSPO-16594 - remove demo 01 from appgateway

.github/workflows/pr-reviewer.yml
Add CI PR AI Reviewer
- Added a GitHub Actions workflow file `pr-reviewer.yml`.
- Defines a CI workflow triggered on `pull_request` action for the `master` branch and also via `workflow_dispatch`.
- Sets up a review job that creates a diff file, generates a response, and creates a comment on the PR with the response.
- Utilizes environment variables and GitHub secrets to interact with an API and handle response generation.
- Incorporates the use of `jq` and `curl` to create the API request and handle the response.
- Retrieves and posts the API response as a comment on the pull request.
- Utilizes the actions/github-script to create a comment on the PR.
=> Add CI PR AI Reviewer

environments/stg/stg.tfvars
Reverts hmcts/azure-platform-terraform#2075
- Added a second IP address to the `cft_apps_cluster_ips` array in `stg.tfvars`
- Updated the `cft_apps_cluster_ips` to include [\"10.10.143.250\", \"10.10.159.250\"] 🔄
=> Revert "DTSPO-16594 - remove 00 cluster to upgrade"

environments/stg/stg.tfvars
disabling 01 cluster for upgrade
=> DTSPO-16594 - remove 01 cluster to upgrade

environments/stg/stg.tfvars
Reverts hmcts/azure-platform-terraform#2078
=> Revert "DTSPO-16594 - remove 01 cluster to upgrade"

environments/test/test.tfvars
Reverts hmcts/azure-platform-terraform#2082
=> Revert "DTSPO-16594 - perftest 00 cluster remove from appgateway"

environments/ithc/ithc.tfvars
https://tools.hmcts.net/jira/browse/DTSSTCI-757
Remove RFI whitelisted rule for testing in ITHC env
- Removed RFI rule from the frontends in ithc.tfvars
- Removed RFI rule from the global exclusions in ithc.tfvars
=> DTSSTCI-757

environments/prod/prod.tfvars
Reverts hmcts/azure-platform-terraform#2092
- Added a new IP address to the `cft_apps_cluster_ips` list
- Increased the `frontend_agw_max_capacity` from 10 to 15
- No other changes made 🔄
=> Revert "DTSPO-16595 - remove prod 01 cluster from appgateway"

.github/workflows/pr-reviewer.yml, .github/workflows/pr-summary.yml
update git diff to only current branch
- Updated the `Create a diff file` job to use the correct diff between the feature branch and `origin/master.remotes/origin/${{ github.head_ref }}`.
- Updated the `Create a diff file` job to use the correct diff between the feature branch and `origin/master.remotes/origin/${{ github.head_ref }}`.
- Changed the prompt type to \"pullrequest-summary-perfile\" when generating a response.
=> update git diff to only current branch

environments/demo/demo.tfvars, environments/ithc/ithc.tfvars, environments/test/test.tfvars
https://tools.hmcts.net/jira/browse/LAU-886
Ignore cookies with names "lau-cookie-preferences", "lau-session" and "dtCookie"
Request to gippi failed to process
=> LAU-886 disable blocking few cookies

environments/ithc/ithc.tfvars
https://tools.hmcts.net/jira/browse/DTSSTCI-260
Test using sub domain in ithc with sub domain of sptribs-frontend
- Changed the custom domain for \"sptribs-dss-update-case-web\" from \"sptribs-dss-update-case-web.ithc.platform.hmcts.net\" to \"update.sptribs-frontend.ithc.platform.hmcts.net\" in ithc.tfvars.
=> DTSSTCI-260

environments/prod/prod.tfvars
https://tools.hmcts.net/jira/browse/DIAC-360
The changes in this pull request include:
- Updated the mode property from \"Detection\" to \"Prevention\"
- Added disabled_rules property for LFI, RCE, RFI, and SQLI
- Added new global_exclusions for match_variable and selector values
=> DIAC-360 exclusion update for PROD

.github/workflows/pr-reviewer.yml, .github/workflows/pr-summary.yml
Rename Gippi to AEP
- Updated .github/workflows/pr-reviewer.yml
- Changed error message from \"Request to gippi failed to process\" to \"Request to AEP failed to process\"
- Updated .github/workflows/pr-summary.yml
- Changed error message from \"Request to gippi failed to process\" to \"Request to AEP failed to process\"
- Updated script to include proper formatting for pull request body
=> Rename Gippi to AEP

components/apim/main.tf, environments/ithc/ithc.tfvars, environments/sbox/sbox.tfvars, environments/variables.tf
Changed vars into object for better readaility and validation in module side
Request to AEP failed to process
=> DTSPO-17136-apim-upgrade-improvements

environments/prod/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/SIDM-9214
Add idam-user-profile-bridge
- **backend_lb_config.yaml**
- Added SSL configuration for the user-profile-bridge component.
=> SIDM-9214 Update backend_lb_config.yaml

components/apim/main.tf
update ref to cft branch in module, so that cft can be targeted seperately for upgrades
=> Update APIM ref for CFT only upgrades

environments/ithc/ithc.tfvars
add ithc migration values to tfvars
- Added migration_variables including trigger_migration, trigger_migration_temp_pip, and temp_subnet_address_prefixes.
This file now contains new variables related to migration.
=> add ithc migration values

environments/demo/demo.tfvars, environments/ithc/ithc.tfvars
cft demo upgrade https://tools.hmcts.net/jira/browse/DTSPO-17760
cft ithc code cleanup https://tools.hmcts.net/jira/browse/DTSPO-17759
added migration vars to demo and set to true
ithc temp resources set to false
- **environments/demo/demo.tfvars**
- Added migration_variables settings for trigger_migration, trigger_migration_temp_pip, and temp_subnet_address_prefixes.
- **environments/ithc/ithc.tfvars**
- Changed trigger_migration_temp_pip from true to false.
=> added migration vars to demo, code cleanup for ithc

environments/demo/demo.tfvars, environments/ithc/ithc.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-17760
trigger migration false to migrate cft apim demo back to original resources
removed ithc vars no longer needed
- Changed `trigger_migration` from `true` to `false` in `migration_variables`.
- Removed the entire `migration_variables` block.
- Removed `trigger_migration = false` and related fields.
=> cft apim upgrade demo migrate back

environments/demo/demo.tfvars, environments/test/test.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-17762
trigger migration false to go back to original resources 
removed demo vars no longer needed
- Updated demo.tfvars:
- Removed migration_variables block and its contents.
- Updated frontends section by removing an entry for \"reformscan\".
- Updated test.tfvars:
- Changed trigger_migration value from true to false.
- Removed trigger_migration_temp_pip entry.
- Updated temp_subnet_address_prefixes value.
=> migrate to original resources and remove demo vars

environments/test/test.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-17762
removed migration vars for cft apim test no longer needed, code cleanup 
- Removed migration_variables block and related variables from the file.
- Updated the value of cft_apps_ag_ip_address to \"10.48.96.123\".
- Updated the value of frontend_agw_private_ip_address to \"10.48.96.113\".
- Updated the values in cft_apps_cluster_ips to [\"10.48.79.250\", \"10.48.95.250\"].
=> code cleanup cft apim test

environments/stg/stg.tfvars
add migration values to stg tfvars
- Added migration_variables block with trigger_migration and trigger_migration_temp_pip set to true, and temp_subnet_address_prefixes set to \"10.10.162.0/24\"
- Updated frontend_agw_private_ip_address to \"10.10.161.102\"
=> add migration values

environments/stg/stg.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-17761
complete upgrade for cft apim stg
- Updated `stg.tfvars`: Changed `trigger_migration` from `true` to `false` and added `trigger_migration_temp_pip` as `true` with `temp_subnet_address_prefixes` set to \"10.10.162.0/24\".
=> ready cft stg apim for pt2 upgrade

components/apim/main.tf, environments/stg/stg.tfvars, environments/variables.tf
removed migration vars 
- `components/apim/main.tf`:
- Updated the source for the module \"api-mgmt\" to use the \"main\" branch instead of \"apim-cft-upgrade\".
- Removed the \"migration_variables\" block from the module \"api-mgmt\".
- `environments/stg/stg.tfvars`:
- Removed the \"migration_variables\" block.
- Updated the \"frontend_agw_private_ip_address\" to \"10.10.161.102\".
- `environments/variables.tf`:
- Removed the \"migration_variables\" variable definition.
=> revert apim module, apim upgrade complete

azure_pipeline.yaml
https://tools.hmcts.net/jira/browse/DTSPO-17593
Updated name of the pipeline so it correctly displays if its terraform `plan` or`apply`
Request to AEP failed to process
=> DTSPO-17593 - updated name of the pipeline

environments/test/apim_appgw_config.yaml
missed rewrite rule for apim perftest
- Modified `apim_appgw_config.yaml`
- Added `add_rewrite_rule: true`
- Added a new rewrite rule named \"AddCustomHeadersRule\" with sequence number \"100\"
=> missed rewrite rule for apim perftest

environments/sbox/sbox.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-17682
Adding azure front door
- `environments/sbox/sbox.tfvars` 🔄
- Added a new configuration for \"labs-goldenpath-khaled\" including product, name, custom domain, DNS zone name, backend domain, and disabled rules.
=> DTSPO-17682-goldenpath-step-9.1

environments/sbox/sbox.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-17682
Adding azure front door
- Added a new key \"shutter_app\" with a value of \"false\" to the frontends block.
=> DTSPO-17682-adding-azure-front-door

environments/demo/demo.tfvars, environments/ithc/ithc.tfvars, environments/stg/stg.tfvars, environments/test/test.tfvars
https://tools.hmcts.net/jira/browse/SIDM-9310
Add hmcts-access exclusions for password, email, username
- Added new matching conditions for request body post argument names for \"password\", \"username\", and \"email\".
- Added new matching conditions for request body post argument names for \"password\", \"username\", and \"email\".
- Added new matching conditions for request body post argument names for \"password\", \"username\", and \"email\".
- Added new matching conditions for request body post argument names for \"password\", \"username\", and \"email\".
=> SID-9130 Add hmcts-access exclusions for password, email, username

environments/demo/demo.tfvars, environments/ithc/ithc.tfvars, environments/test/test.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-18119 
Added new configurations for "em-icp" product with custom domain, DNS zone name, and backend domain in each environment Demo, Perftest, and LTHC
- [ X] commit messages are meaningful and follow good commit message guidelines
- [ X] README and other documentation has been updated / added (if needed)
- [X ] tests have been updated / new tests has been added (if needed)
- [ X] Does this PR introduce a breaking change
- Modified `demo.tfvars`, `ithc.tfvars`, and `test.tfvars`
- Added new configurations for \"em-icp\" product with custom domain, DNS zone name, and backend domain in each file
=> added Perftest

environments/demo/demo.tfvars
- Updated the \"fact-admin\" frontend mode from \"Detection\" to \"Prevention\"
- Added global exclusions for specific request cookie names and query string argument names for the \"fact-admin\" frontend.
=> FACT-1846 setting fact admin to prevention mode DEMO

environments/demo/demo.tfvars
- Changed mode for the \"fact-admin\" backend from \"Detection\" to \"Prevention\" ✨
- Added global exclusions for specific request cookie names and query string argument names 🍪
=> FACT-1881 added global exclusions for fact admin

environments/demo/demo.tfvars, environments/ithc/ithc.tfvars
Adding DSS application to ITHC
- Added a new \"dss\" configuration with custom domain, DNS zone name, mode, backend domain, and global exclusions for the demo environment.
- Added a new \"dss\" configuration with custom domain, DNS zone name, mode, backend domain, certificate name, and global exclusions for the ithc environment.
=> deploying DSS in ithc and demo environment

environments/demo/demo.tfvars
adding missing firewall exclusion - fact admin won't log in because request with regards to idam
- Modified file: demo.tfvars
- Added a new selector \"auth_verification\" under frontends.
=> FACT-1846 added missing auth_verification exclusion for fact-admin

environments/demo/demo.tfvars
adding missing firewall exclusion - fact admin won't log in because request with regards to idam
- Added new frontends configuration for RequestBodyPostArgNames with different operators and selectors. 🛠️
=> FACT-1846 adding some more block exclusions fact-admin

environments/ithc/ithc.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-18302
DSS Deployment to ITHC
- environments/ithc/ithc.tfvars```:
- Added disabled_rules for SQL injection, local file inclusion, and remote code execution.
- Added global exclusions for specific request cookies and query string arguments.
=> DSS deployments to ITHC

environments/demo/demo.tfvars
https://tools.hmcts.net/jira/browse/DTSCCI-525
Adding global exclusion to resolve access being blocked. 
- The file `demo.tfvars` in the `demo` environment has been modified.
- Two new global exclusions have been added, matching specific request cookie and query string names in the `frontends` section.
- Additionally, the existing `cmc` section has been updated with the same global exclusions as the previous change.
=> Dtscci 525 prevention mode for demo

components/apim-appgw/root_certs.tf, environments/test/apim_appgw_config.yaml
apim test with liberata ca
- `components/apim-appgw/root_certs.tf`
- Added a new entry \"liberata_ca\" to the local variable `test`
- `environments/test/apim_appgw_config.yaml`
- Added a new rootca_certificate entry \"liberata_ca\" under rootca_certificates
=> apim test with liberata ca

environments/demo/demo.tfvars
- Added a new entry to the `frontends` block with a `match_variable` of \"RequestCookieNames\", `operator` of \"Equals\", and `selector` of \"money-claims-cookie-preferences\".
- Removed an entry from the `frontends` block with a `match_variable` of \"RequestCookieNames\", `operator` of \"Equals\", and `selector` of \"money-claims-cookie-preferences\".
=> Excluding money-claims-cookie-preferences cookies

components/shutter_static_webapp/init.tf, environments/demo/demo.tfvars
adding postparamvalue
- `components/shutter_static_webapp/init.tf`:
- Updated azurerm provider version from \"3.113.0\" to \"3.65.0\".
- `environments/demo/demo.tfvars`:
- Updated frontend configurations including match_variable, operator, and selector for different scenarios within the demo environment.
=> FACT-1846 added more exclusions for fact-admin demo

components/apim-appgw/root_certs.tf, environments/test/apim_appgw_config.yaml
Install Exela cert on perf test
- Added a new local variable `exela_ca` to the `locals` block.
- Added `exela_ca` to the list of `rootca_certificate_name`.
=> Install Exela cert on perftest

environments/stg/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/EM-6150
set up em-media-viewer in AAT
- In `backend_lb_config.yaml`, a new configuration has been added for the \"em\" product and \"media-viewer\" component.
=> set up em-media-viewer in AAT

azure_pipeline.yaml, components/apim-appgw/local.tf, components/apim-appgw/root_certs.tf, environments/demo/apim_appgw_config.yaml, environments/demo/demo.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-18453
- add apim_appgw yaml config for demo
- map mtls certs through tf component for demo
- add demo_apim_appgw deployment to pipeline
- add tfvars for demo apim_appgw
- **azure_pipeline.yaml**
- Added a deployment for 'demo_apim_appgw' with corresponding environment, component, service connection, storage account, and pipeline tests.
- **components/apim-appgw/local.tf**
- Updated to include 'demo' environment in conditional statements for vnet_rg and vnet_name.
- **components/apim-appgw/root_certs.tf**
- Added a new local variable 'demo' including specific certificates for the 'demo' environment.
- **environments/demo/apim_appgw_config.yaml**
- Added a new file defining configuration for the 'demo' environment, including gateways, SSL …
=> DTSPO-18453: deploy demo apim appgw

azure_pipeline.yaml, components/apim-appgw/local.tf, components/apim-appgw/root_certs.tf, environments/stg/apim_appgw_config.yaml, environments/stg/stg.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-18453
- add apim_appgw yaml config for aat
- map mtls certs through tf component for aat
- add apim_appgw deployment to pipeline for aat
- add tfvars for aat apim_appgw
- Added a new deployment for 'stg_apim_appgw' with relevant details.
- Updated the environment for 'stg_frontendappgateway' to 'stg'.
- Updated the 'env', 'vnet_rg', 'vnet_name', and 'hub_env' variables based on the 'var.env' value.
- Added a new variable called 'stg' and its configuration details.
- Added a new file with gateway configuration details for staging environment.
- Added new variables 'key_vault_subscription', 'hub_app_gw_private_ip_address', and 'apim_appgw_backend_pool_fqdns'.
=> DTSPO-18453: deploy aat apim appgw

environments/stg/apim_appgw_config.yaml, environments/stg/stg.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-18453
- update apim appgw private ip for stg
- Updated private_ip_address from 10.11.8.216 to 10.11.8.219 in `apim_appgw_config.yaml`
- Updated `hub_app_gw_private_ip_address` from [\"10.11.8.216\"] to [\"10.11.8.219\"] in `stg.tfvars`
=> DTSPO-18453: update apim appgw private ip for stg

environments/prod/prod.tfvars
https://tools.hmcts.net/jira/browse/DTSCCI-525
Update Exclusion rules to match AAT. 
- Removed `\"942150\"` from SQLI disabled rules
- Added `\"930100\"` and `\"930130\"` to LFI disabled rules
- Removed `\"932150\"` from RCE disabled rules
- Added `\"931130\"` to RFI disabled rules
- Updated match variables for request body, request cookies, and query string arguments for cmc product.
=> DTSCCI-525 Update Exclusion rules to match other environments

environments/stg/apim_appgw_config.yaml, environments/stg/stg.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-18453
- update aat apim appgw private ip
- Updated the `private_ip_address` from `10.11.8.203` to `10.11.8.215` for the gateway configuration.
- Modified the `ssl_certificates` with the `certificate_name` wildcard-aat-platform-hmcts-net for app configuration.
- Changed the `hub_app_gw_private_ip_address` from `[\"10.11.8.203\"]` to `[\"10.11.8.215\"]`.
- Updated the `apim_appgw_backend_pool_fqdns` to [\"firewall-prod-int-palo-cftapimgmtstg.uksouth.cloudapp.azure.com\"].
=> DTSPO-18453: update aat apim appgw private ip

environments/sbox/sbox.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-18493
Doing the goldenpath tutorial and making sure everything is still working
- **sbox.tfvars**
- Added a new configuration block for \"labs-endakelly-nodejs\" product with custom domain, DNS zone name, backend domain, certificate name, and disabled rules.
=> DTSPO-18493 - Goldenpath nodenjs refresh

environments/demo/demo.tfvars, environments/ithc/ithc.tfvars, environments/prod/prod.tfvars, environments/stg/stg.tfvars, environments/test/test.tfvars
https://tools.hmcts.net/jira/browse/PAY-6602
Initial update to block direct APIM access for external suppliers.
- Added a new block to the frontends array to block fee and payment endpoints.
- Added a new block to the frontends array to block fee and payment endpoints.
- Added a new block to the frontends array to block fee and payment endpoints.
- Added a new block to the frontends array to block fee and payment endpoints.
- Added a new block to the frontends array to block fee and payment endpoints.
=> PAY-6602: Initial update to block direct APIM access for external suppliers

azure_pipeline.yaml, components/apim/main.tf
https://tools.hmcts.net/jira/browse/DTSPO-18411
Change branch to test APIM diagnostic logging on SBOX
- The `azure_pipeline.yaml` file was modified to update deployment configuration for various environments like `demo`, `test`, `stg` and `prod`, with some new configurations and removal of previous configurations.
- The `components/apim/main.tf` file was modified to update the source URL for the api-mgmt module.
=> Disable APIM except for SBOX to test azure apim diagnostic resource

environments/ithc/ithc.tfvars, environments/prod/prod.tfvars
https://tools.hmcts.net/jira/browse/DTSCCI-525
Update Exclusion rules  change to mode to Prevention for ITHC to match environments. 
- File: ithc.tfvars
- Added new mode``` and updated ```disabled_rules``` and ```global_exclusions``` for \"civil-citizen-ui\" and \"cmc\" frontends
- Changed mode from \"Detection\" to \"Prevention\"
- Updated disabled_rules for SQL injection (SQLI), Local File Inclusion (LFI), Remote Code Execution (RCE), and Remote File Inclusion (RFI)
- Added global_exclusions for specific match_variable and selectors for both frontends
=> DTSCCI-525 Update rules in ithc to match envs

azure_pipeline.yaml
+ Add APIM logging for demo,staging,ithc and test
- azure_pipeline.yaml```: Added deployment configurations for different environments (ithc, demo, test, stg) for APIM (API Management) component, including service connections, storage account details, and dependencies.
- Updated deployment configurations for APIM in different environments with service connections, storage account details, and pipeline tests.
=> DTSPO-18411: Add apim logging for non prod

components/apim-appgw/root_certs.tf, environments/demo/apim_appgw_config.yaml
https://tools.hmcts.net/jira/browse/DTSPO-18581
Adding the PCIPAL cert to the APIM demo app gateway for DTSPO-18581
- `components/apim-appgw/root_certs.tf`:
- Added `pcipal_ca` to the list of local certificates.
- `environments/demo/apim_appgw_config.yaml`:
- Added `pcipal_ca` to the rootca_certificate_name list.
=> Adding PCIPAL cert to demo apim appgw.

components/apim/main.tf
https://tools.hmcts.net/jira/browse/DTSPO-18642
- swap apim-mgmt module ref to master branch
- Updated the source URL for the \"api-mgmt\" module to use the \"main\" branch instead of \"dtspo-18411-apim-log-issue\".
=> DTSPO-18643: swap api-mgmt module ref to main

environments/sbox/sbox.tfvars
See [DTSPO-18670](https://tools.hmcts.net/jira/browse/DTSPO-18670)
remove cft-sbox-00 from app gw
- **environments/sbox/sbox.tfvars**:
- Removed one of the IP addresses from the `cft_apps_cluster_ips` list.
=> remove cft-sbox-00

environments/sbox/sbox.tfvars
See [DTSPO-18670](https://tools.hmcts.net/jira/browse/DTSPO-18670)
re-add cft-sbox-00-aks to appgw
- Changed file: `environments/sbox/sbox.tfvars`
- Updated `cft_apps_cluster_ips` from `[\"10.2.11.250\"]` to `[\"10.2.9.250\", \"10.2.11.250\"]`
=> re-add-cft-sbox-00 to app gw

environments/sbox/sbox.tfvars
See [DTSPO-18670](https://tools.hmcts.net/jira/browse/DTSPO-18670)
remove sbox 01 from app gw to order to upgrade aks version
- Removed one IP address from the `cft_apps_cluster_ips` list, now it contains only one IP address instead of two.
=> remove sbox-01 from gw

environments/sbox/sbox.tfvars
See [DTSPO-18670](https://tools.hmcts.net/jira/browse/DTSPO-18670)
readd cft-sbox-01 to app gw after aks uprade 
- Added a new IP address \"10.2.11.250\" to the `cft_apps_cluster_ips` array in sbox.tfvars.
=> re-add cft-sbox 01 cluster

environments/demo/demo.tfvars
remove demo 00 cluster
- **demo.tfvars**
- Removed the IP address \"10.50.79.221\" from the `cft_apps_cluster_ips` list and set `certificate_name_check` to false.
=> DTSPO-18669 Upgrade CFT NonProd AKS Clusters to Kubernetes 1.30 - remove demo 00 cluster

environments/demo/demo.tfvars
=> DTSPO-18669 Upgrade CFT NonProd AKS Clusters to Kubernetes 1.30 - re-add demo 00 IP

environments/demo/demo.tfvars, environments/ithc/ithc.tfvars, environments/prod/prod.tfvars, environments/stg/stg.tfvars
https://tools.hmcts.net/jira/browse/RST-6863
Request to AEP failed to process
=> HwF - Adding online app search to WAF filter

environments/stg/stg.tfvars
Comment out AAT 00 IP for AKS upgrade
- Removed the second IP address from the `cft_apps_cluster_ips` list.
=> DTSPO-18669 Upgrade CFT NonProd AKS Clusters to Kubernetes 1.30 comment out AAT 00 IP

environments/stg/stg.tfvars
re-add aat 01 IP to app gw 
- Added a new IP address \"10.10.159.250\" to the `cft_apps_cluster_ips` array.
=> Upgrade CFT NonProd AKS Clusters to Kubernetes 1.30 - re-add AAT 01 ip

environments/test/test.tfvars
See [DTSPO-18669(https://tools.hmcts.net/jira/browse/DTSPO-18669)
remove cft-aks-perftest-00-aks IP from app gw
- The `test.tfvars` file in the `test` environment has been modified.
- The `cft_apps_cluster_ips` values have been changed, with one IP address being removed from the list.
- The `frontend_agw_private_ip_address` has been updated to \"10.48.96.113\".
=> remove cft-perftest-00-aks-IP

environments/test/test.tfvars
comment out perftest 01 IP 
- Removed one IP address from the `cft_apps_cluster_ips` list.
=> Upgrade CFT NonProd AKS Clusters to Kubernetes 1.30 - comment out cft-perftest-01 IP

environments/test/test.tfvars
Re-add cft-perfftest-01 IP to app gw 
- Updated `test.tfvars`: Added a new IP address \"10.48.95.250\" to the `cft_apps_cluster_ips` list.
=> re-add cft-perfftest-01

environments/prod/prod.tfvars
comment out cft-prod-00-aks IP 
- Removed one IP address from the `cft_apps_cluster_ips` list, now it only contains \"10.90.95.250\" instead of [\"10.90.79.250\", \"10.90.95.250\"]
=> Upgrade CFT Prod and PTL AKS Clusters to Kubernetes 1.30 - comment out cft-prod 00 ip

environments/prod/prod.tfvars
Reverts hmcts/azure-platform-terraform#2276
- Modified prod.tfvars
- Updated cft_apps_cluster_ips from [\"10.90.95.250\"] to [\"10.90.79.250\", \"10.90.95.250\"]
=> Revert "Upgrade CFT Prod and PTL AKS Clusters to Kubernetes 1.30 - comment out cft-prod 00 ip"

environments/prod/prod.tfvars
comment out cft prod 00 IP from app gw 
- Updated prod.tfvars in the prod environment
- Removed one IP address from cft_apps_cluster_ips array
- Updated the frontend_agw_private_ip_address to \"10.90.96.12\"
- Updated frontend_agw_min_capacity to 10 and frontend_agw_max_capacity to 15
=> Upgrade CFT Prod and PTL AKS Clusters to Kubernetes 1.30 - Comment out cft-aks-prod-00-aks

environments/prod/prod.tfvars
Re-add cft-prod-00-aks IP 
- Updated `cft_apps_cluster_ips` from `[\"10.90.95.250\"]` to `[\"10.90.79.250\", \"10.90.95.250\"]` 🔄.
=> Upgrade CFT Prod AKS Clusters to Kubernetes 1.30 - re add cft-prod-00 IP

components/shutter_static_webapp/init.tf, environments/prod/prod.tfvars
comment out cft-prod-01 aks IP from app gw 
- Updated `components/shutter_static_webapp/init.tf`: 
- Changed the `subscription_id` value in two provider blocks and added `skip_provider_registration` attribute to both.
- Updated `environments/prod/prod.tfvars`: 
- Removed one IP from the `cft_apps_cluster_ips` list.
=> Upgrade CFT Prod AKS Clusters to Kubernetes 1.30 - comment out cft-prod-01-aks-IP

environments/prod/prod.tfvars
add 01 back to app gw
- Added a new IP address \"10.90.95.250\" to the `cft_apps_cluster_ips` array.
=> Upgrade CFT Prod and PTL AKS Clusters to Kubernetes 1.30 - re-add prod 01 IP

components/apim-appgw/root_certs.tf, environments/demo/apim_appgw_config.yaml
https://tools.hmcts.net/jira/browse/DTSPO-19039
New Certificate upload to Demo CFT APIM Gateway
- Added a new local variable \"pcipal_cav2\" to the list of local variables.
- Added \"pcipal_cav2\" to the list of rootca_certificate_name under gateways.
=> Demo: Add PCIPal ca cert for mtls to demo apim appgw

components/apim-appgw/root_certs.tf, environments/demo/apim_appgw_config.yaml
https://tools.hmcts.net/jira/browse/DTSPO-19039
Amend the name for demon ner cert value
-
- Updated the local variable `pcipal_cav2` to `pcipalv2_ca`.
- Removed `pcipal_cav2` from the `rootca_certificate_name` list and added `pcipalv2_ca`.
=> Amend the naming for new cert value

environments/demo/demo.tfvars, environments/ithc/ithc.tfvars, environments/stg/stg.tfvars, environments/test/test.tfvars
https://tools.hmcts.net/jira/browse/FACT-1991
fact phone numbers messing up when adding things like and / or. need to add exclusion for this rule
this will be test
- `environments/demo/demo.tfvars` 🛠️ Added disabled rules for SQL injection with specific rule IDs.
- `environments/ithc/ithc.tfvars` 🛠️ Added disabled rules for SQL injection with specific rule IDs.
- `environments/stg/stg.tfvars` 🛠️ Added disabled rules for SQL injection with specific rule IDs.
- `environments/test/test.tfvars` 🛠️ Added disabled rules for SQL injection with specific rule IDs.
=> FACT-1991 NON PROD false positive exceptions

environments/prod/prod.tfvars
https://tools.hmcts.net/jira/browse/FACT-1991
fact phone numbers messing up when adding things like and / or. need to add exclusion for this rule
this will be test
- File: prod.tfvars
- Added a new block for disabled_rules within the frontends section to disable specific SQL injection rules with their corresponding rule IDs.
=> FACT-1991 PROD false positive exceptions

components/apim-appgw/root_certs.tf, environments/demo/apim_appgw_config.yaml
https://tools.hmcts.net/jira/browse/DTSPO-19039
Added Certificates to APIM 
- Replaced the previous root certificates with the updated list of root certificates in the `demo` environment.
- Updated the root CA certificates for the API Management Application Gateway in the `demo` environment to include `pcipal_ssl_com_intermediate_ca` and `pcipal_ssl_com_root_ca`.
=> Added cert to APIM

environments/prod/prod.tfvars
See [RET-5406](https://tools.hmcts.net/jira/browse/RET-5406)
Start deploying ET-SYR to prod
- Updated `prod.tfvars`
- Added a new backend configuration for \"et-syr\" with custom domain and DNS zone name
- Included global exclusions for \"et-syr\" such as matching request cookie names
=> ET-SYR Prod deployment

components/apim-appgw/root_certs.tf, environments/prod/apim_appgw_config.yaml
https://tools.hmcts.net/jira/browse/DTSPO-21983
Adding MTLS self-signed certs for Production as well.
- Added two new certificates `pcipal_ssl_com_intermediate_ca` and `pcipal_ssl_com_root_ca` to the `prod` object.
- Added `pcipal_ssl_com_intermediate_ca` and `pcipal_ssl_com_root_ca` as `rootca_certificate_name` under the `gateways` section.
=> DTSPO-21983 - added production mtls certs

environments/stg/backend_lb_config.yaml
Adding PCS API to Azure Application Gateway to allow for load balancing on AAT.
See [HDPI-28](https://tools.hmcts.net/jira/browse/HDPI-28)
Adding PCS to Azure Application Gateway to allow for load balancing on AAT.
No testing performed as this is enabling changes only.
- [] Does this PR introduce a breaking change
- The file **backend_lb_config.yaml** in the **stg** environment has been updated to add a new product and component in the gateways configuration for media-viewer and api 🔄.
=> Update backend_lb_config.yaml to add PCS API to load balancing.

environments/stg/stg.tfvars
See [HDPI-29](https://tools.hmcts.net/jira/browse/HDPI-29)
Adding the PCS Frontend to the front door/Firewall with WAF mode set to prevention.
No testing done, this is a configuration change.
- `environments/stg/stg.tfvars` 🔄
- Added a new block for a \"pcs-frontend\" with specific details like mode, custom_domain, dns_zone_name, backend_domain, and global_exclusions.
=> Adding the front door/Firewall config for PCS Frontend

environments/sbox/sbox.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-22339
Caching settings exist in the frontdoor module, testing overrides and effects on caching settings
- Added caching configuration for url file extensions and route configuration override action.
This pull request introduces changes to the `sbox.tfvars` file in the `environments/sbox` directory. It adds caching configurations for url file extensions and route configuration override action.
=> Testing compression on caching for sbox idam public web

environments/demo/demo.tfvars
https://tools.hmcts.net/jira/browse/HDPI-42
- **environments/demo/demo.tfvars**
- Added a new configuration block for \"pcs-frontend\" including name, mode, custom_domain, dns_zone_name, backend_domain, and global_exclusions.
=> HDPI-42: Demo PCS frontend firewall config

environments/ithc/backend_lb_config.yaml
[HDPI-70](https://tools.hmcts.net/jira/browse/HDPI-70)
Adding load balancer to the PCS-API on ITHC
None, configuration change,
- backend_lb_config.yaml
- Added a new configuration for product `pcs` with component `api` to the `gateways` section
=> HDPI-70 - Add load balancer for PCS-API on ITHC

environments/test/backend_lb_config.yaml
yaml
backend_lb_config.yaml
- Added a new configuration for product \"pcs\" and component \"api\" under gateways
```
=> Add pcs api to perftest

environments/sbox/sbox.tfvars
See [DTSPO-22645](https://tools.hmcts.net/jira/browse/DTSPO-22645)
Adding corresponding Frontdoor Entries following the golden path
Creating a Custom Domain which matches the DNS record -"labs-goldenpath-ashleigh"- created in a previous PR. Along with a backend pool that the frontdoor sends request to which matches the public ip -  172.167.29.122 -created in a previous PR and attached to the Azure firewall and a routing rule that Azure frontdoor needs to process your requests.
- Changed the product, name, and custom_domain values for the frontends block.
- Updated the backend_domain for labs-goldenpath-ashleigh.
- Removed several blocks related to different products and their configurations.
- Updated the backend_domain for labs-goldenpath-ashleigh.
=> addinging corresponding Frontdoor entries

environments/test/backend_lb_config.yaml
- Added configuration for a new component \"test-stubs-service\" under the \"ccd\" product.
- Updated the component for the \"judicial-payment-service\" under the \"pcs\" product.
=> add test stub service

environments/demo/backend_lb_config.yaml
- Added a new component \"case-print-service\" under the product \"ccd\".
- Updated the configuration to include \"case-print-service\" as a component under the product \"ccd\".
=> add ccd print service to demo

environments/sbox/sbox.tfvars
See [DTSPO-22757](https://tools.hmcts.net/jira/browse/DTSPO-22757)
Add frontend entry for Lukasz's Golden Path sandbox in sbox.tfvars
Not applicable, this is Golden Path tutorial PR.
- Added a new product \"labs-goldenpath-lukasz\" with custom domain, DNS zone name, backend domain, certificate name, and disabled rules.
=> Add frontdoor entry for Lukasz's Golden Path sandbox

environments/sbox/sbox.tfvars
N/A
Frontdoor entry created
None
- **sbox.tfvars**
- Added a new configuration block for \"lab-jamiemcconnell-goldenpath\" product with custom domain and backend domain configurations.
=> Frontdoor entry created

environments/sbox/sbox.tfvars
N/A
Adding front door entry for Dawid Golden Path Lab DNS
This is Golden Path Virtual Networks step 9
N/A
- Added a new product \"labs-goldenpath-dawid\" with custom domain, DNS zone name, backend domain, certificate name, and disabled rules.
- Updated the frontends list to include the new product details.
=> Add front door entry for Dawid Golden Path Lab DNS (GP step 9)

environments/sbox/sbox.tfvars
N/A
Corrected Frontdoor entry to align with Golden Path lab instructions
None
- Updated the product, name, and custom_domain for the \"labs-goldenpath-jamie\" frontend.
- Updated the backend_domain for the \"labs-goldenpath-jamie\" frontend.
=> Corrected Frontdoor entry to align with lab instructions

environments/sbox/sbox.tfvars
N/A
Add Front Door entry for the Node JS application I created for ExpressJS Golden Path tutorial
N/A
- `environments/sbox/sbox.tfvars`
- Added a new configuration for `labs-dawidstrozak-nodejs` including product, name, custom domain, DNS zone name, backend domain, and certificate name.
=> Add Front Door entry for Dawid Golden Path Node JS Application

environments/sbox/sbox.tfvars
N/A
Front door config as per Golden Path instructions
N/A
- Added a new configuration for \"labs-jamiemcconnell-nodejs\" including product, custom domain, DNS zone name, backend domain, and certificate name.
=> Update sbox.tfvars - Golden Path

environments/sbox/sbox.tfvars
See [DTSPO-22757](https://tools.hmcts.net/jira/browse/DTSPO-22757)
Add frontdoor entry for Lukasz's Golden Path NodeJS app
N/A, this is Golden Path tutorial PR.
- Added a new configuration block for \"labs-lukaszk-hmcts-nodejs\" including product, name, custom_domain, dns_zone_name, and backend_domain.
- Updated the list of frontends with the new configuration block for \"labs-lukaszk-hmcts-nodejs\".
=> Add frontdoor entry for Lukasz's Golden Path NodeJS app

environments/sbox/sbox.tfvars
Pipeline currently failing, and other envs are being skipped. labs-goldenpath-lukasz already exists. Removing here to quickly unblock others.
Just removing a lab from sbox that is 3 weeks old anyway.
- Removed the configuration for \"labs-goldenpath-lukasz\" from the tfvars file.
=> Update sbox.tfvars, Pipeline fix

environments/sbox/sbox.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-23140
Remove Front Door entries for the two Golden Path labs
N/A
- Removed several blocks of configurations for different products and their respective custom domains and backend domains.
=> Remove Front Door entries for the two Golden Path labs

environments/demo/demo.tfvars
[DTSPB-4467](https://tools.hmcts.net/jira/browse/DTSPB-4467)
try to the update the disabled_rules and reproduce the issue is low env
- Updated the `disabled_rules` attribute to include new SQL injection rule \"942110\" and updated the RCE rule to include \"932130\" in addition to \"932115\".
=> DTSPB-4467 add disabled_rules in demo for tesing

environments/sbox/sbox.tfvars
N/A
Remove Front Door entries for the Golden Path labs that are causing the pipeline to fail
N/A
- The `sbox.tfvars` file in the `environments/sbox` directory has undergone changes where multiple blocks of configuration entries have been removed. These entries were related to various products like \"labs-goldenpath-ashleigh,\" \"labs-goldenpath-jamie,\" \"labs-ashleigh31-nodejs,\" and more. All the removed blocks had configurations for custom domains, DNS zone names, backend domains, certificate names, and disabled rules.
=> Remove Golden Path Labs Front Door Entries

environments/ithc/ithc.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-23355
Changing WAF ruleset from 1.0 to 2.1
- The file `ithc.tfvars` in the `ithc` environment has been modified to include the addition of `ruleset_type` and `ruleset_value` with their respective values, and a `Microsoft_DefaultRuleSet` has been set to \"2.1\".
=> changing ruleset to waf 2.1

environments/ithc/ithc.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-23355
Disabling 2 rules which block login
- File: ithc.tfvars
- Added a new set of disabled_rules in the configuration, with specific rules under General being disabled (\"200002\", \"200003\").
=> Platops/dtspo 23355 private law waf2.1ruleset

environments/prod/prod.tfvars
LIVE issue fix 
- Added a new selector for \"RequestCookieNames\" with the operator \"Equals\" and the selector \"_hwf-publicapp_session\" in the frontends.
=> WAF filter update

environments/demo/demo.tfvars
https://tools.hmcts.net/jira/browse/EXUI-2362
update demo web pub ip for exui
- Changed the `pubsub_endpoint` value from `[\"10.50.100.50\"]` to `[\"10.50.100.5\"]` 🔄.
=> pubsub_endpoint ip updated

components/frontendappgateway/main.tf, components/pubsubappgateway/main.tf, environments/demo/demo.tfvars, environments/ithc/ithc.tfvars, environments/prod/prod.tfvars, environments/stg/stg.tfvars, environments/test/test.tfvars
fix pubsub integration appgw
ℹ️ Pull request includes the following changes:
ℹ️ In components/pubsubappgateway/main.tf: Removed the \"destinations\" variable.
ℹ️ In environments/demo/demo.tfvars: Updated the \"pubsub_endpoint\" IP address.
ℹ️ In environments/ithc/ithc.tfvars: Updated the \"pubsub_endpoint\" IP address.
ℹ️ In environments/prod/prod.tfvars: Updated the \"pubsub_endpoint\" IP address.
ℹ️ In environments/stg/stg.tfvars: Updated the \"pubsub_endpoint\" IP address.
ℹ️ In environments/test/test.tfvars: Updated the \"pubsub_endpoint\" IP address.
=> fix pubsub integration appgw

environments/ithc/ithc.tfvars
[FPET-1263](https://tools.hmcts.net/jira/browse/FPET-1263)
- Added \"942440\" to the list of disabled rules for the \"SQLI\" category.
=> FPET-1234 disbled DefaultRuleSet-1.0-SQLI-942440 rule

azure_pipeline.yaml, components/frontendappgateway/local.tf, components/frontendappgateway/main.tf, components/frontendappgateway/provider.tf, components/pubsubappgateway/local.tf, components/pubsubappgateway/main.tf, components/pubsubappgateway/provider.tf, environments/demo/demo.tfvars, environments/dev/dev.tfvars, environments/ithc/ithc.tfvars, environments/prod/prod.tfvars, environments/sbox/sbox.tfvars, environments/stg/stg.tfvars, environments/test/test.tfvars, environments/variables.tf
DTSPO-23915
Adding settings to allow for https and certificates, updating health probe path
- `azure_pipeline.yaml`:
- Added configurations for `ithc_pubsubappgateway` and `ithc_backendappgateway`.
- Updated `test_pattern` values for `apim.test.ts` and `pipeline.test.ts`.
- `components/frontendappgateway/local.tf`:
- Added `hub_env` and `key_vault_name` to the locals block.
- `components/frontendappgateway/main.tf`:
- Added `providers` block with `azurerm.hub` and `azurerm.kv`.
- `components/frontendappgateway/provider.tf`:
- Added providers for `kv` and `hub`.
- `components/pubsubappgateway/local.tf`:
- Added `key_vault_name` and `hub_env` to the locals block.
- `components/pubsubappgateway/main.tf`:
- Added `providers` block with `azurerm`, `azurerm.kv`, and `azurerm.hub`.
- …
=> DTSPO-23915 adding additional settings for pubsub app gateway

environments/demo/backend_lb_config.yaml, environments/demo/demo.tfvars
PAY-7609: Decommission of Digital Bar: Front end (BAR Web) DEMO env
[PAY-7609] (https://tools.hmcts.net/jira/browse/PAY-7609).
- Removed \"bar\" component and its associated configuration.
- Removed \"bar\" product and its associated configuration from the gateways.
- Removed \"bar\" and \"bar-int\" configurations for custom domains, DNS zone names, and backend domains.
=>  PAY-7609: Decommission of Digital Bar: Front end (BAR Web) DEMO env

environments/ithc/ithc.tfvars
- ithc.tfvars``` changed the mode from \"Detection\" to \"Prevention\" for the \"sscs-iba\" frontend.
=> Update WAF for SSCS IBA to Prevention

environments/sbox/sbox.tfvars
following golden path
- The `sbox.tfvars` file in the `environments/sbox` directory has been updated to add a new configuration for a product called \"labs-yur-nodejs\". This configuration includes custom domain, DNS zone name, backend domain, certificate name, and disabled rules.
=> goldenpath nodejs roger

environments/demo/demo.tfvars, environments/prod/prod.tfvars, environments/stg/stg.tfvars, environments/test/test.tfvars
https://tools.hmcts.net/jira/browse/FPET-1263
https://tools.hmcts.net/jira/browse/VUL-6219 
https://tools.hmcts.net/jira/browse/DTSPO-23355
- Enable Prevention mode private law citizen application
- Disabled rules that is blocking the application for private law citizen application
- Added custom rule to fix the ithc issue https://tools.hmcts.net/jira/browse/VUL-6219 
- The changes were made in ITHC earlier. the same copied over for other environments for private law citizen application
- Updated the mode from \"Detection\" to \"Prevention\"
- Added custom rules for blocking certain script content in JSON requests
- Updated disabled rules for specific types of injection attacks
- Updated the mode from \"Detection\" to …
=> FPET-1263 / DTSPO-23355 WAF changes to prevention mode && ITHC issue fix VUL-6219 

environments/prod/prod.tfvars
- Changed `prod.tfvars` in `environments/prod`:
- Added two new rules for `RequestCookieNames` in the `frontends` configuration.
=> Adding dynatrace cookie to list of exclusions

environments/prod/prod.tfvars
https://tools.hmcts.net/jira/browse/RST-7203
WAF exception
- Added a new selector for `applicant_address[street]` under the `frontends` section.
=> HwF public app WAF fix

environments/prod/prod.tfvars
https://tools.hmcts.net/jira/browse/EXUI-2910
Agw setting for PROD
- Added a new configuration block for \"em-icp\" with specific product, name, mode, custom domain, DNS zone name, and backend domain.
=> EXUI-2910: agw setting for PROD

environments/ithc/ithc.tfvars
- Modified ithc.tfvars```
- Added a new block for \"fis-ds-web\" with custom domain, DNS zone, mode, backend domain, certificate name, and global exclusions for query string arg names.
=> Added fis-ds-web configs for ITHC env

environments/sbox/sbox.tfvars
See [DTSPO-22075](https://tools.hmcts.net/jira/browse/DTSPO-22075)
Temporary remove cft-sbox-01 from load balancer for testing https://github.com/hmcts/aks-cft-deploy/pull/694
Testing on https://github.com/hmcts/aks-cft-deploy/pull/694
N/A
Please provide the steps required to deploy these changes to Azure.
Please add any other information that is important to this PR, such as screenshots, logs, or links to other related PRs.
https://dev.azure.com/hmcts/PlatformOperations/_build/results?buildId=774457&view=logs&j=3786ccf2-758c-5203-1f23-cc188c0bdf6d&t=8e5c75b6-a045-5267-6735-93497f765c58
- Removed one IP address from the `cft_apps_cluster_ips` list.
- Updated the `cft_apps_cluster_ips` to `[\"10.2.9.250\"]`.
- Updated the `apim_appgw_backend_pool_fqdns` to …
=> temp removed sbox 01

components/frontendappgateway/main.tf, components/pubsubappgateway/main.tf
https://tools.hmcts.net/jira/browse/DTSPO-24594
Changing module branch back to master after create new module for tls 1.2
- Updated the source URL to \"git::https://github.com/hmcts/terraform-module-applicationgateway.git?ref=master\"
- Updated the source URL to \"git::https://github.com/hmcts/terraform-module-applicationgateway.git?ref=master\"
- Changed the count condition to check for var.env equal to \"sbox\" before setting count to 0, else sets count to 1
=> revert module branch back to master

environments/prod/backend_lb_config.yaml
PAY-7621: Decommission of Digital Bar: Front end (BAR Web): Production
[PAY-7624] (https://tools.hmcts.net/jira/browse/PAY-7621)
- Removed \"bar\" API component from the configuration.
- Removed \"rd\" professional API component from the configuration.
=>  PAY-7617: Decommission of Digital Bar: Backend (BAR API): Production

environments/sbox/sbox.tfvars
See [DTSPO-22075](https://tools.hmcts.net/jira/browse/DTSPO-22075)
re-add cft-sbox-01 frontend IP to LB
=> DTSPO- 22075 - readd sbox 01 to lb

environments/demo/backend_lb_config.yaml, environments/ithc/backend_lb_config.yaml, environments/test/backend_lb_config.yaml
[HDPI-188](https://tools.hmcts.net/jira/browse/HDPI-188)
Add load balancer for Enforcement-API in Demo, ITHC, and PerfTest
N/A Configuration change
- `backend_lb_config.yaml`:
- Added backend configurations for the enforcement component in the demo, ithc, and test environments.
=> HDPI-188 - Add load balancer for Enforcement-API in Demo, ITHC, and PerfTest

environments/sbox/sbox.tfvars
Testing golden path as part of onbaording
- The file `sbox.tfvars` in the `environments/sbox` directory has been updated.
- A new configuration block has been added to specify settings for a service called \"labs-abhivan-nodejs\" within the frontends list.
- The custom_domain, dns_zone_name, shutter_app, backend_domain, certificate_name, and disabled_rules have been defined for the \"labs-abhivan-nodejs\" service.
- This update adds configurations for a new service within the sbox environment.
=> abhivan golden-path test

environments/demo/backend_lb_config.yaml
- **backend_lb_config.yaml**
- Added a `request_timeout` of 180 for the `admin-web` component with SSL enabled.
=> Bump timeout for ccd-admin-web

environments/sbox/sbox.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-25672
Re adding sbox01 to app gateway after upgrade to V1.32
- Added a new IP address \"10.2.11.250\" to the `cft_apps_cluster_ips` list in the sbox.tfvars file.
=> Re adding sbox01

environments/demo/demo.tfvars
Reverts hmcts/azure-platform-terraform#2475
- Updated cft_apps_cluster_ips``` from \"10.50.95.221\" to [\"10.50.79.221\", \"10.50.95.221\"] 🔄
=> Revert "Remove demo-00 cluster from access for upgrading process"

environments/demo/demo.tfvars
Copied over exclusions from ITHC
See [ADOP-2484](https://tools.hmcts.net/jira/browse/ADOP-2484)
- Copy adoption-web firewall config from ITHC to demo for testing
- [x ] commit messages are meaningful and follow good commit message guidelines
- [ x] README and other documentation has been updated / added (if needed)
- [x ] tests have been updated / new tests has been added (if needed)
- Modified file: environments/demo/demo.tfvars
- Changed the mode from \"Detection\" to \"Prevention\"
- Added global exclusions for various match_variable and selectors related to cookies, query strings, and request body post args.
=> ADOP-2484: Enable prevention in demo for testing

environments/demo/demo.tfvars
Reverts hmcts/azure-platform-terraform#2477
- demo.tfvars```
- Added a new IP address \"10.50.95.221\" to the `cft_apps_cluster_ips` array.
=> Revert "Remove cft-demo-01 from app gw for upgrade"

environments/demo/demo.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-25674
Remove Demo01 from App GW for code upgrade
- File: demo.tfvars
- Removed the second IP address from the cft_apps_cluster_ips list and set certificate_name_check to false.
=> Remove Demo01 from App GW for code upgrade

environments/demo/demo.tfvars
Reverts hmcts/azure-platform-terraform#2482
- Added an additional IP address (\"10.50.95.221\") to the `cft_apps_cluster_ips` list.
=> Revert "Remove Demo01 from App GW for code upgrade"

environments/stg/stg.tfvars
Reverts hmcts/azure-platform-terraform#2495
- Added a new IP address \"10.10.159.250\" to the \"cft_apps_cluster_ips\" array.
=> Revert "DTSPO-35686: Removing aat-01 from app gateway for upgrade"

environments/demo/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/CCD-6381
Expose the int demo datastore and def store apps via the config
N/A
N/A
- [N] Does this PR introduce a breaking change
- **backend_lb_config.yaml**:
- Added configuration for new API components related to the \"ccd\" product.
=> CCD-6381 Add int demo apps to the config

environments/demo/demo.tfvars, environments/stg/stg.tfvars, environments/test/test.tfvars
https://tools.hmcts.net/jira/browse/ADOP-2484
Enable prevention mode in PERFTEST and AAT, update global exclusions in DEMO
- Added global exclusions for \"RequestBodyPostArgNames\" with specific selectors in `demo.tfvars`, `stg.tfvars`, and `test.tfvars`
- Switched the mode to \"Prevention\" and updated the `backend_domain` in `stg.tfvars` and `test.tfvars`
=> ADOP-2484: Enable prevention mode in PERFTEST and AAT, update global exclusions in DEMO

environments/prod/prod.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-25676
Add back 00 cluster.
- File: prod.tfvars
- Updated cft_apps_cluster_ips to include an additional IP address \"10.90.79.250\" alongside \"10.90.95.250\"
=> Add back 00 prod cluster

environments/prod/prod.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-25676 
Removes 01 from prod
- Removed one IP address from the cft_apps_cluster_ips list.
=> Remove 01 prod from gateway

environments/prod/prod.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-25676 
Remove 00 cluster from gateway.
- Removed one of the IPs from the `cft_apps_cluster_ips` array.
- Updated `cft_apps_cluster_ips` to `[\"10.90.95.250\"]`.
=> Remove 00 prod from gateway

environments/prod/prod.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-25676 
Add 00 back to prod gateway.
- Changed `cft_apps_cluster_ips` from `[\"10.90.95.250\"]` to `[\"10.90.79.250\", \"10.90.95.250\"]` 🔄.
=> Add 00 prod to gateway

environments/prod/prod.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-25676
Re-add 01 to prod gateway.
- Added a new IP address \"10.90.95.250\" to the `cft_apps_cluster_ips` list.
=> DO NOT MERGE Add prod 01 cluster to gateway

environments/prod/prod.tfvars
https://tools.hmcts.net/jira/browse/ADOP-2484
Enable prevention mode in PROD
- `prod.tfvars`
- Changed the `mode` from \"Detection\" to \"Prevention\" for the \"child-adoption\" frontend.
- Added new global exclusions for various match variables, operators, and selectors for the \"apply-to-adopt-a-child-placed-in-your-care\" service.
=> ADOP-2484: Enable prevention mode in PROD

environments/demo/backend_lb_config.yaml, environments/sbox/backend_lb_config.yaml, environments/stg/backend_lb_config.yaml, environments/test/backend_lb_config.yaml
- Removed \"product: bulk-scan\" and \"component: sample-app\" under the orchestrator.
- Removed \"product: bulk-scan\" and \"component: sample-app\" under the orchestrator.
- Removed \"product: bulk-scan\" and \"component: sample-app\" under the orchestrator.
- Removed \"product: bulk-scan\" and \"component: sample-app\" under the orchestrator.
=> FACT-2391 remove sample-apps

environments/demo/demo.tfvars, environments/ithc/ithc.tfvars, environments/prod/prod.tfvars, environments/stg/stg.tfvars, environments/test/test.tfvars
- Modified environments/demo/demo.tfvars, environments/ithc/ithc.tfvars, environments/prod/prod.tfvars, environments/stg/stg.tfvars, environments/test/test.tfvars:
- Changed the selector for the match_variable \"RequestBodyPostArgNames\" operator \"Equals\" from specific document names to \"UploadedFiles\".
=> [NFDIV-3888] Correct nfd upload paths

environments/ithc/ithc.tfvars
See [FPVTL-421](https://tools.hmcts.net/jira/browse/FPVTL-421)
- Testing was done in ITHC and flagged these as false positives.
- Added new rules for matching request cookie names, query string argument names, and request cookie names. 🔄
=> FPVTL-421: Update rules to stop false-positives

environments/sbox/sbox.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-26781
- Modified file: sbox.tfvars
- Added a new entry for a product \"labs-manohar-hmcts-nodejs\" with custom domain, DNS zone name, backend domain, and certificate name.
=> DTSPO-26781: labs-manohar-hmcts-nodejs

environments/sbox/sbox.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-26781
DTSPO-26781-mano-golden-path-revert
- Removed configurations for \"labs-goldenpath-mano\" and \"labs-manohar-hmcts-nodejs\" products from the `frontends` list.
=> DTSPO-26781: mano-golden-path-revert

environments/sbox/sbox.tfvars
- `environments/sbox/sbox.tfvars` 🔄
- Added a new configuration for `labs-shabbir-nodejs` with custom domain and backend domain configurations.
=> labs-shabbir-nodejs for golden path

environments/demo/demo.tfvars, environments/ithc/ithc.tfvars, environments/stg/stg.tfvars, environments/test/test.tfvars
See [PAY-8027](https://tools.hmcts.net/jira/browse/PROJ-XXXXhttps://tools.hmcts.net/jira/browse/PAY-8027)
Changed the PaymentOutcome-web mode to Prevention for Demo and ITHC
Testing can only be done once PR has been built
- Changed demo.tfvars```, ```ithc.tfvars```, ```stg.tfvars```, and ```test.tfvars``` in the ```environments``` directory
- Updated the ```mode``` from \"Detection\" to \"Prevention\" for the \"paymentoutcome-web\" in each environment.
=> PAY-8027 paymentoutcome-web set to prevention mode

environments/prod/prod.tfvars
- Added LFI rules for multi-part uploads 🛡️
=> DTSCCI-2575 - DTSCCI-2604 added ruleset to whitelist false positive

environments/sbox/backend_lb_config.yaml
adding configuration for golden path run through as per the instructions on the golden-path documentation: https://github.com/hmcts/golden-path-java/blob/master/docs/index.md#configure-load-balancing-for-high-availability
- backend_lb_config.yaml
- Added a new component \"hurricanepilot\" under the \"labs\" product in the gateways section.
=> add labs-hurricanepilot

environments/demo/demo.tfvars
https://tools.hmcts.net/jira/browse/DFPL-2704
Correcting field names following initial testing.
Change to demo for testing.
- `demo.tfvars`
- Updated selectors for match variables, replacing 'FirstName' with 'FirstNames'. Example: `applicant1FirstName` changed to `applicant1FirstNames`. This change is repeated for multiple match variables throughout the file.
=> ADOP-2707 correct field names (demo testing)

environments/demo/demo.tfvars
https://tools.hmcts.net/jira/browse/DFPL-2704
Correct field name for testing in demo
- Changed environments/demo/demo.tfvars
- Updated the value of the 'selector' field from \"birthMotherFirstName\" to \"birthMotherFirstNames\"
=> ADOP-2707 fix field name

environments/prod/prod.tfvars
- `prod.tfvars`
- Added frontend \"932110\" to the frontends list
- Removed \"932110\" from the RCE list
- Added \"932110\" to the RCE list
- Removed \"932110\" from the frontends list
=> DTSCCI-000 Remove duplicate RCE block

environments/ithc/ithc.tfvars
See [RET-5319](https://tools.hmcts.net/jira/browse/RET-5319)
Initial changes to test moving WAF into Prevention mode
- `ithc.tfvars`: Mode changed from \"Detection\" to \"Prevention\" for the frontends, and added global exclusions for request cookies and other variables to the firewall configuration. SQL injection rules were disabled as well.
=> ET-SYA WAF into Prevention on ITHC

environments/prod/apim_appgw_config.yaml
n/a
updated apim_appgw_config.yaml to add the new Digicert CA for CBUS production
* [ x] No
- [ x] Does this PR introduce a breaking change
- `environments/prod/apim_appgw_config.yaml`
- Added a new rootca_certificate_name \"civil_sdt_root_ca_2025\" under rootca_certificates.
=> Updated apim_appgw_config.yaml to add new Digicert CA for DC1

environments/demo/backend_lb_config.yaml, environments/ithc/backend_lb_config.yaml, environments/prod/backend_lb_config.yaml, environments/stg/backend_lb_config.yaml, environments/test/backend_lb_config.yaml
FACT-2484
Added config for new fact data API
- backend_lb_config.yaml```
- Added a new component \"data-api\" to the \"fact\" product in the \"demo\", \"ithc\", \"prod\", \"stg\", and \"test\" environments.
=> FACT-2484 Added config for new fact repo

environments/demo/demo.tfvars, environments/prod/prod.tfvars, environments/stg/stg.tfvars
https://tools.hmcts.net/jira/browse/RST-7634
- `demo.tfvars` 🔄 Three new frontend configurations were added to the file, each including match variables, operators, and selectors.
- `prod.tfvars` 🔄 Five frontend configurations were updated in the file, each including match variables, operators, and selectors.
- `stg.tfvars` 🔄 Three new frontend configurations were added to the file, each including match variables, operators, and selectors.
=> HWF WaF filter update

environments/prod/prod.tfvars
https://tools.hmcts.net/jira/browse/PAY-8102
WAF change to add  disabled_rules  for  SQLI = ["942440"] and to include global_exclusions for _csrf.
Testing done in lower environment.
- **prod.tfvars**
- Added a new rule to disable SQL injection with a specific rule ID \"942440\".
- Included a global exclusion for \"RequestCookieNames\" to check for the presence of a specific cookie \"_csrf\".
=> PAY-8102: Allow -- characters in CSRF token
