- components/global/main.tf
- components/global/variables.tf
- environments/sandbox/global.tfvars
- modules/azure-landing-zone/data.tf
- modules/azure-landing-zone/frontdoor.tf
- modules/azure-landing-zone/variables.tf
> update ssl frontdoor custom

- azure_pipeline.yaml
> update missing buildnumber

- environments/ithc/global.tfvars
- environments/stg/global.tfvars
[AB#593](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/593)
TODO:
> Add divorce config

- environments/ithc/global.tfvars
- environments/sbox/global.tfvars
- environments/stg/global.tfvars
- modules/azure-landing-zone/frontdoor.tf
> update frontdoor config

- modules/azure-landing-zone/diagnostics.tf
> frontdoor diagnostics

- modules/azure-landing-zone/frontdoor.tf
> update forwarding rule to be http

- environments/ithc/global.tfvars
- environments/stg/global.tfvars
> Need to confirm from secops

- environments/ithc/global.tfvars
- environments/sbox/global.tfvars
- environments/stg/global.tfvars
- modules/azure-landing-zone/frontdoor.tf
> add az firewall routing to palo

- components/base/module_firewall.tf
- components/global/main.tf
- components/global/variables.tf
- environments/ithc/base.tfvars
- environments/ithc/global.tfvars
- environments/prod/base.tfvars
- environments/prod/global.tfvars
- environments/sbox/base.tfvars
- environments/sbox/global.tfvars
- environments/stg/base.tfvars
- environments/stg/global.tfvars
- environments/test/base.tfvars
- environments/test/global.tfvars
- modules/azure-firewall/diagnostics.tf
- modules/azure-landing-zone/data.tf
- modules/azure-landing-zone/diagnostics.tf
- modules/azure-landing-zone/frontdoor.tf
- modules/azure-landing-zone/frontdoor_kv_access.tf
- modules/azure-landing-zone/variables.tf
[AB#594](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/594)
```
[ ] Yes
[ ] No
```
> Add support for custom routing

- environments/ithc/global.tfvars
- environments/sbox/global.tfvars
- environments/stg/global.tfvars
[AB#594](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/594)
> Update pip names

- azure_pipeline.yaml
- ci/terraform-lint.tests.ps1
- environments/mgmt/ithc.tfvars
- pipeline-templates/terraform-plan.yaml
[AB#594](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/594)
> Parallelise plan and add CI check

- environments/ithc/global.tfvars
- environments/stg/global.tfvars
[AB#689](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/689)
Disable SQL comment sequence detected rule for divorce,
The JWT from IDAM that is set in the cookie is triggering this rule sometimes
```
[ ] Yes
[ ] No
```
> Add additional rule disable for divorce

- environments/sbox/global.tfvars
[AB#689](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/689)
> Remove plum for now as Piyush has it shuttered

- components/shutter/module_default_shutter.tf
- environments/sbox/shutter.tfvars
- modules/shutter_page/cdn_endpoints.tf
- modules/shutter_page/custom_domains.tf
Add custom domain creation working with Standrad_Verizon and Premium_Verizon CDN profiles
> Us615 shutter app

- modules/shutter_page/enable_https.tf
Enable enable ssl with custom domain using CDN managed certificate
> enable ssl with custom domain

- environments/stg/global.tfvars
> add pet-app stg service for testing

- azure_pipeline.yaml
- components/shutter/module_default_shutter.tf
- environments/prod.tfvars
- modules/shutter_page/cdn_endpoints.tf
- modules/shutter_page/storage_account.tf
[AB#700](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/700)
> Add storage account to prod

- environments/stg.tfvars
> change backend domain for pet

- environments/ithc.tfvars
- environments/prod.tfvars
- environments/sbox.tfvars
- environments/stg.tfvars
- modules/app-gateway-module/main.tf
- modules/azure-landing-zone/frontdoor.tf
[AB#690](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/690)
Few things left to do to make this work 
```
[ ] Yes
[ ] No
```
> Frontdoor config for divorce in prod

- environments/prod.tfvars
[AB#690](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/690)
```
[ ] Yes
[ ] No
```
> Enable SSL

- environments/ithc.tfvars
- environments/prod.tfvars
- environments/stg.tfvars
[AB#693](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/693)
> Disable additional rules divorce

- environments/prod.tfvars
> remove traffic from prod 01

- environments/prod.tfvars
Reverts hmcts/azure-platform-terraform#63
> Revert "remove traffic from prod 01"

- environments/prod.tfvars
> Remove Prod 00 traffic

- environments/prod.tfvars
Reverts hmcts/azure-platform-terraform#70
> Revert "Remove Prod 00 traffic"

- .gitignore
- components/shutter/module_default_shutter.tf
- modules/shutter_page/cdn_endpoints.tf
- modules/shutter_page/custom_domains.tf
- modules/shutter_page/enable_https.tf
- modules/shutter_page/templates/customHttps.json
- modules/shutter_page/variables.tf
[AB#728](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/728)
```
[ ] Yes
[ ] No
```
> Try fix shuttering

- environments/prod.tfvars
- environments/sbox.tfvars
- modules/shutter_page/enable_https.tf
- modules/shutter_page/variables.tf
[AB#728](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/728)
```
[ ] Yes
[ ] No
```
> Lookup certificate version like in frontdoor

- environments/prod.tfvars
[AB#729](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/729)
```
[ ] Yes
[ ] No
```
> Add sscs prod config

- environments/ithc.tfvars
- environments/stg.tfvars
[AB#725](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/725)
> Disable iss parameter in query string

- environments/prod.tfvars
- environments/stg.tfvars
[AB#729](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/729)
```
[ ] Yes
[ ] No
```
> SSCS prod config

- components/global/main.tf
- environments/ithc.tfvars
- environments/prod.tfvars
- environments/sbox.tfvars
- environments/stg.tfvars
- environments/test.tfvars
- environments/variables.tf
- modules/azure-landing-zone/frontdoor_waf_policy.tf
- modules/azure-landing-zone/variables.tf
[AB#725](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/725)
Required so we can move only divorce into monitor mode
```
[ ] Yes
[ ] No
```
> Per app WAF mode settings

- environments/prod.tfvars
[AB#725](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/725)
```
[ ] Yes
[ ] No
```
> Revert accidental exclusions change

- environments/prod.tfvars
[AB#734](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/734)
```
[ ] Yes
[ ] No
```
> Try re-add sscs cor which failed last time

- environments/prod.tfvars
Reverts hmcts/azure-platform-terraform#85
> Revert "Try re-add sscs cor which failed last time (#85)"

- environments/prod.tfvars
Reverts hmcts/azure-platform-terraform#86
> Revert "Revert "Try re-add sscs cor which failed last time (#85)""

- environments/prod.tfvars
- environments/stg.tfvars
We're getting some random failures and can't debug why, case has been
raised with microsoft
> Change sscs to detection

- environments/prod.tfvars
- environments/stg.tfvars
CHG5000455 [AB#725](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/725)
1 week in monitoring mode to make sure we didn't miss anything
```
[ ] Yes
[ ] No
```
> Change divorce to monitor and add exclusions

- environments/stg.tfvars
> Take aat-01 out of service

- environments/stg.tfvars
> Restore aks aat-01

- environments/ithc.tfvars
add front door configuration for idam-ithc
```
[ ] Yes
[x] No
```
> feat(idam-ithc): add front door configuration

- environments/stg.tfvars
> div pfe aat detection mode

- environments/ithc.tfvars
https://tools.hmcts.net/jira/browse/SIDM-3686
ITHC add idam exclusion
```
[ ] Yes
[x] No
```
> SIDM-3686 - ITHC add idam exclusion

- environments/ithc.tfvars
https://tools.hmcts.net/jira/browse/SIDM-3686
idam-ithc exclusion
```
[ ] Yes
[x] No
```
> SIDM-3686 - idam-ithc exclusion

- azure_pipeline.yaml
- modules/app-gateway-module/main.tf
https://tools.hmcts.net/jira/browse/SIDM-3686
add rule set for idam and x-forward-for
```
[ ] Yes
[x] No
```
> SIDM-3686 - add rule set for idam and x-forward-for

- environments/ithc.tfvars
- environments/prod.tfvars
- environments/stg.tfvars
- environments/test.tfvars
> 17.2 all apps frontdoor config

- environments/test.tfvars
> Enable ssl perftest

- environments/stg.tfvars
https://tools.hmcts.net/jira/browse/PCQ-109
Add PCQ frontfoor config to aat (staging).
```
[ ] Yes
[x] No
```
> Add PCQ frontdoor config

- azure_pipeline.yaml
- modules/app-gateway-module/main.tf
> WAF mode for frontend app gw

- environments/stg.tfvars
Configure adoption frontdoor
```
[ ] Yes
[X] No
```
> Add adoption frontdoor config

- environments/stg.tfvars
Adding IAC frontend Front door config for AAT only
Related app: https://github.com/hmcts/ia-aip-frontend
> IAC AIP frontend Front door config for AAT

- environments/stg.tfvars
> Add missing backend for stg

- environments/stg.tfvars
> Add missing space

- environments/test.tfvars
https://tools.hmcts.net/jira/browse/SIDM-3773
idam-perftest front door
```
[ ] Yes
[x] No
```
> SIDM-3773 - idam-perftest front door

- environments/prod.tfvars
[[AB#806](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/806)]
```
[ ] Yes
[x] No
```
> Drain prod-01-kas for upgrade

- azure_pipeline.yaml
- components/dynatrace_activegate/local.tf
- components/dynatrace_activegate/main.tf
- components/dynatrace_activegate/provider.tf
- components/dynatrace_activegate/variables.tf
- environments/ptl.tfvars
- environments/variables.tf
- modules/dynatrace-activegate/cloudconfig.tpl
- modules/dynatrace-activegate/variables.tf
- modules/dynatrace-activegate/vm.tf
- pipeline-templates/terraform-apply.yaml
- pipeline-templates/terraform-plan.yaml
[AB#809](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/809)
```
[ ] Yes
[ ] No
```
> AB#809 Dynatrace activegate installation

- environments/prod.tfvars
[[AB#806](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/806)]
```
[ ] Yes
[x] No
```
> Restore prod-01-aks

- environments/prod.tfvars
[[AB#806](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/806)]
```
[ ] Yes
[x] No
```
> Drain prod-00-aks

- azure_pipeline.yaml
- environments/prod.tfvars
[AB806]
```
[ ] Yes
[x] No
```
> Restore prod-00-aks

- environments/ithc.tfvars
> Add xui config

- environments/ithc.tfvars
Adding Front Door config for IAC in ITHC env.
> IAC Adding ITHC front door config

- environments/stg.tfvars
https://tools.hmcts.net/jira/browse/SIDM-3821
aat adding in frondoor configuration and listers
```
[ ] Yes
[X] No
```
> SIDM-3821 IDAM AAT FrontDoor configuration and listeners

- environments/ithc/ithc.tfvars
- environments/prod/prod.tfvars
- environments/stg/stg.tfvars
- environments/test/test.tfvars
> Add AAT probate front door config

- modules/app-gateway-module/main.tf
Reverts hmcts/azure-platform-terraform#114
> Revert "WAF mode for frontend app gw"

- environments/prod/prod.tfvars
- environments/stg/stg.tfvars
[AB#815](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/815)
Initial tuning, more to come, will do incrementally so we can monitor it
```
[ ] Yes
[ ] No
```
> Initial WAF tuning

- environments/stg/stg.tfvars
[AB#829](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/829)
> Probate in detection mode

- environments/prod/prod.tfvars
[AB#815](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/815)
> More divorce WAF tuning

- environments/prod/prod.tfvars
[AB#815](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/815)
> DIV-PFE WAF tuning 3

- environments/prod/prod.tfvars
[AB#815](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/815)
> More divorce tuning

- environments/prod/prod.tfvars
[AB#841](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/841)
> Initial cmc waf tuning

- environments/prod/prod.tfvars
[AB#841](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/841)
> More CMC WAF tuning

- environments/prod/prod.tfvars
[AB#843](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/843)
> Initial SSCS tuning

- azure_pipeline.yaml
RPE-1186
Removed temporary fix required for pipeline builds to trigger on PRs. 
```
[ ] Yes
[x] No
```
> removed temporary fix for PR triggers. Issue closed

- environments/sbox/sbox.tfvars
Solo: @verityit
Adding frontend config for sprod
```
[ ] Yes
[ ] No
```
> SIDM-3934: Added sprod frontend config

- azure_pipeline.yaml
https://tools.hmcts.net/jira/browse/RPE-1187
```
[ ] Yes
[x] No
```
> Re-enable shutter pages builds

- environments/demo/backend_lb_config.yaml
> Adding CCD backends to appgw in demo

- environments/sbox/sbox.tfvars
> rename idam sprod to prevent storage name clash

- environments/demo/backend_lb_config.yaml
> Adding probate backends to demo

- environments/ithc/ithc.tfvars
- environments/sbox/sbox.tfvars
- environments/stg/stg.tfvars
https://tools.hmcts.net/jira/browse/SIDM-3905
Adding exclusions to match the current prod designs
```
[ ] Yes
[X] No
```
> SIDM-3905 add additional idam exclusions

- modules/app-gateway-module-backend/main.tf
https://tools.hmcts.net/jira/browse/SIDM-3775
Backend TLS fix
#149 
```
[ ] Yes
[x] No
```
> SIDM-3775 - Backend TLS fix

- modules/app-gateway-module-backend/main.tf
https://tools.hmcts.net/jira/browse/SIDM-3775
Update backend health probe host to match ingress.
When ingressHost is set to the [internal](https://github.com/hmcts/cnp-flux-config/blob/9027945e712d4a7056de84e6771ef46b0babff89/k8s/sandbox/common/idam/idam-api.yaml#L22),
I cannot access the service through the AppGw.
If I change the [ingressHost](https://github.com/hmcts/cnp-flux-config/blob/ee0d009fafd485e0f424136ee0d68e33451c035a/k8s/sandbox/common/idam/idam-api.yaml#L22),
the backend health probe will fail.
```
[ ] Yes
[x] No
```
> SIDM-3775 - Backend health probe host

- azure_pipeline.yaml
> Update terraform version

- environments/stg/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/SIDM-3775
idam-aat ssl backends
```
[ ] Yes
[x] No
```
> SIDM-3775 - idam-aat ssl backends

- environments/sbox/sbox.tfvars
idam-sbox update sprod
fixes https://dev.azure.com/hmcts/CNP/_build/results?buildId=48582&view=logs&j=af23e80f-37e8-5103-7c94-174957406613&t=65732b43-8d7b-50e2-4c75-01717dca1fee&l=36
```
[ ] Yes
[x] No
```
> fix(idam-sbox sprod): update dns

- environments/ithc/backend_lb_config.yaml
- environments/prod/backend_lb_config.yaml
- environments/stg/backend_lb_config.yaml
- environments/test/backend_lb_config.yaml
[AB#798](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/798)
Enabled SSL for ccd admin web 
```
[ ] Yes
[x] No
```
> enabled ssl for ccd admin web in all envs

- environments/demo/backend_lb_config.yaml
Adds FPL case service
```
[ ] Yes
[ ] No
```
> Add FPL case service to demo

- environments/demo/backend_lb_config.yaml
- environments/ithc/backend_lb_config.yaml
- environments/prod/backend_lb_config.yaml
- environments/stg/backend_lb_config.yaml
- environments/test/backend_lb_config.yaml
> Adding probate back office

- environments/stg/backend_lb_config.yaml
- environments/stg/stg.tfvars
https://tools.hmcts.net/jira/browse/SIDM-3963
idam-aat DNS switch over
```
[ ] Yes
[x] No
```
> SIDM-3963 - idam-aat DNS switch over

- environments/stg/stg.tfvars
Remove idam-web-public. Certificate has gone bad.
```
[ ] Yes
[ ] No
```
> fix(idam): remove frontdoor listener part 1

- environments/stg/stg.tfvars
This reverts commit da393af7c12b9f18d90774a4076bf62dfbb4b1f2.
Re add aat idam-web-public
```
[ ] Yes
[ ] No
```
> Revert "fix(idam): remove frontdoor listener part 1" ... part 2

- environments/stg/stg.tfvars
This reverts commit 9d9297f06dfb78fd2b9fbc473473ed00b5673ff8.
```
[ ] Yes
[ ] No
```
> Revert "Revert "fix(idam): remove frontdoor listener part 1""

- environments/stg/stg.tfvars
Enable idam-web-public listener
```
[ ] Yes
[ ] No
```
> Idam web public aat cert fix part 2

- environments/stg/stg.tfvars
Remove exclusions. Enable detection
> idam-aat Remove exclusions. Enable detection

- environments/ithc/backend_lb_config.yaml
> Updated product name

- environments/stg/backend_lb_config.yaml
- environments/stg/stg.tfvars
> feat(idam-aat2): add aat2 listeners

- .gitignore
- environments/demo/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/ROC-7656
Add claim-store to demo
```
[ ] Yes
[x ] No
```
> add claim-store to demo

- environments/stg/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/PCQ-170
Add LB config for Protected Characteristics Questions (PCQ)
```
[ ] Yes
[x] No
```
> PCQ-170 Add PCQ Backend LB Config

- environments/test/backend_lb_config.yaml
> Added ethos to test env

- environments/prod/prod.tfvars
New frontend app
Related info:
App: https://github.com/hmcts/ia-aip-frontend
Public DNS Config: https://github.com/hmcts/azure-public-dns/pull/111
Prod Flux Config: https://github.com/hmcts/cnp-flux-config/pull/2654 (requires production-apps / devops team approval)
> IAC AIP Prod Front door config

- azure-platform-terraform.iml
- environments/ithc/ithc.tfvars
- environments/prod/prod.tfvars
- environments/stg/stg.tfvars
- environments/test/test.tfvars
> Add fees pay

- environments/prod/prod.tfvars
> fix fee register url

- environments/test/test.tfvars
> add xui perftest front door config

- environments/demo/backend_lb_config.yaml
[Configure App GW for bulk and reform scan repos](https://tools.hmcts.net/jira/browse/BPS-1160)
```
[ ] Yes
[x] No
```
> Add BulkScan and ReformScan components to demo App GW

- environments/test/test.tfvars
> fix backend domain typo for various apps

- environments/prod/prod.tfvars
> Probate waf exclusions continued

- environments/prod/prod.tfvars
> Update exclusions for access + auth tokens

- environments/sbox/sbox.tfvars
- modules/azure-landing-zone/frontdoor.tf
> Additional www frontend which redirects to default endpoint.

- environments/sbox/sbox.tfvars
> remove sbox additional redirect

- environments/prod/prod.tfvars
> Adding www redirect for fees register

- environments/prod/prod.tfvars
> fix fees register

- modules/azure-landing-zone/data.tf
- modules/azure-landing-zone/frontdoor.tf
> Fix certificate iterator for www redirect to work

- modules/azure-landing-zone/frontdoor_waf_policy.tf
> changing count to avoid deletes on change

- environments/prod/prod.tfvars
> Add paybubble and bar app to prod

- environments/stg/stg.tfvars
Reverts hmcts/azure-platform-terraform#216
> Revert "Switch to aat 01"

- environments/prod/prod.tfvars
> Add csrf to exclusions

- environments/stg/stg.tfvars
Reverts hmcts/azure-platform-terraform#217
> Switch to aat 01

- environments/sbox/sbox.tfvars
improvement(idam-sandbox): waf tuning
```
[ ] Yes
[x] No
```
> SIDM-n/a - improvement(idam-sandbox): waf tuning

- environments/prod/prod.tfvars
> Add file upload field exclusion

- environments/prod/prod.tfvars
> Probate WAF prevention

- environments/stg/stg.tfvars
https://tools.hmcts.net/jira/browse/SIDM-3821
idam-aat disable detection mode
```
[ ] Yes
[x] No
```
> SIDM-3821 - idam-aat disable detection mode

- environments/ithc/ithc.tfvars
> PRO-7285: Added ithc config probate

- environments/test/test.tfvars
https://tools.hmcts.net/jira/browse/RDO-7191
Updated environments/test/test.tfvars to set IDAM WAF to detection.
```
[ ] Yes
[X] No
```
> Updated environments/test/test.tfvars to set IDAM WAF to detection.

- environments/stg/stg.tfvars
revert(idam-aat): revert enable waf
```
[ ] Yes
[x] No
```
> revert(idam-aat): revert enable waf

- environments/ithc/ithc.tfvars
- environments/test/test.tfvars
https://tools.hmcts.net/jira/browse/PCQ-22
Add frontdoor config for PCQ perftest and ithc.
```
[ ] Yes
[x] No
```
> PCQ-22 Updating to add FE config for ithc and perftest.

- environments/prod/backend_lb_config.yaml
feat(idam-prod): add parallel ingress
```
[ ] Yes
[x] No
```
> feat(idam-prod): add parallel ingress

- environments/stg/backend_lb_config.yaml
Adding new backend app: https://github.com/hmcts/ia-home-office-integration-api
> IAC: Adding home-office-api

- components/dynatrace_activegate/main.tf
- modules/dynatrace-activegate/variables.tf
> update instance name, remove activegate

- components/dynatrace_activegate/main.tf
> readd active gate

- environments/prod/prod.tfvars
> Drain 01 for Dynatrace change

- environments/prod/prod.tfvars
> Switch to Prod 01

- environments/stg/stg.tfvars
SIDM-3821
add rules for:
- redirect_uri as post
- refresh_token
```
[ ] Yes
[x] No
```
> SIDM-3821 - stg.tfvars: idam-web-public sort and add rules

- environments/demo/backend_lb_config.yaml
> add s2s to demo

- environments/demo/backend_lb_config.yaml
> Added ccpay bulkscanning api to demo

- environments/sbox/sbox.tfvars
- modules/azure-landing-zone/frontdoor.tf
> Adding option to disable caching

- environments/prod/prod.tfvars
- environments/stg/stg.tfvars
- environments/test/test.tfvars
> Disable cache on ccd gw

- environments/demo/backend_lb_config.yaml
> add xui lb config for demo

- environments/stg/backend_lb_config.yaml
[RIA-2688](https://tools.hmcts.net/jira/browse/RIA-2688)
IA timed event service lb settings
```
[ ] Yes
[x] No
```
> IA timed event service lb settings

- environments/stg/backend_lb_config.yaml
Adding new Immigration & Asylum app
> Adding ia-case-payments-api LB config

- environments/prod/prod.tfvars
https://tools.hmcts.net/jira/browse/SIDM-4082
enable idam-prod idam-web-public prevention mode.
```
[ ] Yes
[x] No
```
> SIDM-4082 - chore(idam-prod): enable prevention mode

- environments/prod/prod.tfvars
- environments/sbox/sbox.tfvars
- environments/stg/stg.tfvars
- environments/test/test.tfvars
CHG5001117
Re-enable Frontdoor caching for CCD gateway and Plum
```
[ ] Yes
[ x] No
```
> Enable Frontdoor caching on CCD gateway

- environments/demo/backend_lb_config.yaml
- environments/prod/backend_lb_config.yaml
- environments/stg/backend_lb_config.yaml
- environments/test/backend_lb_config.yaml
> Added ECM component to Ethos

- environments/demo/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/RDCC-1333
Added RD config
```
[ ] Yes
[X] No
```
> Added RD config

- environments/ithc/ithc.tfvars
> change xui-manage-org to use ukwest backend

- environments/test/backend_lb_config.yaml
Adding bulkscanning app into perftest env
```
[ ] Yes
[x] No
```
> Adding bulkscanning app into perftest

- environments/test/backend_lb_config.yaml
> added bulk-scan, evidence-share component

- environments/ithc/ithc.tfvars
- environments/test/test.tfvars
> migrate half ithc and perftest apps to ukwest

- environments/ithc/ithc.tfvars
- environments/test/test.tfvars
> migrate all ithc and perftest apps to ukwest arch

- environments/ithc/backend_lb_config.yaml
Adding ccpay-bulkscanning to ITHC env
Adding ccpay-bulkscanning to ITHC env
```
[ ] Yes
[x] No
```
> Adding ccpay bulkscanning to ithc env

- environments/test/backend_lb_config.yaml
Adding fee-register api into perftest
Adding fee-register api into perftest
```
[ ] Yes
[x] No
```
> Adding fee-register api into perftest

- environments/demo/backend_lb_config.yaml
Add rse-check-aat.service.core-compute-aat.internal to app gateway
https://tools.hmcts.net/jira/browse/RDO-7608
Configure the AKS app gateway for the rse-check application.
```
[ ] Yes
[ x ] No
```
> Add rse-check service

- environments/prod/prod.tfvars
- environments/stg/stg.tfvars
> migrate aat and prod paybubble to ukwest

- environments/stg/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/RDO-7608
```
[ ] Yes
[ x ] No
```
> Add rse-check into AAT

- environments/prod/prod.tfvars
> swap to prod-01

- environments/prod/prod.tfvars
> Restore prod-00

- environments/prod/prod.tfvars
> Remove prod-01 from pool

- environments/prod/prod.tfvars
> Both Prod clusters back online

- environments/stg/stg.tfvars
https://tools.hmcts.net/jira/browse/RDO-7760
Disable rule 932115 for probate
This replicates changes made on prod https://github.com/hmcts/azure-platform-terraform/commit/6c422181fbad4d0555744daaa54153bff36d9da3
```
[ ] Yes
[ ] No
```
> Disable rule 932115 for probate

- environments/prod/backend_lb_config.yaml
- environments/prod/prod.tfvars
https://tools.hmcts.net/jira/secure/RapidBoard.jspa?rapidView=1305&view=detail&selectedIssue=PCQ-271
Added front-door config and load balancer config for PCQ project in production environment.
```
[ ] Yes
[X ] No
```
> PCQ Production front-door config and lb config

- environments/stg/stg.tfvars
https://tools.hmcts.net/jira/browse/RDO-7760
Set PCQ WAF to detection mode in AAT.
```
[ ] Yes
[ ] No
```
> Set PCQ WAF to Detection (AAT)

- environments/stg/stg.tfvars
> aat-00 offline for k8s upgrade

- environments/stg/stg.tfvars
> aat00 back online

- environments/stg/backend_lb_config.yaml
> Onboarding access management service.

- environments/stg/backend_lb_config.yaml
AM-750
Onboarding ccd case document am api application.
```
[ ] Yes
[ ] No
```
> Onboarding CCD application.

- environments/test/backend_lb_config.yaml
Removing duplicate lines
```
[ ] Yes
[x] No
```
> Removing duplicate lines

- environments/stg/stg.tfvars
> aat-00 back online

- environments/stg/stg.tfvars
> Swap over to aat-00 only

- environments/test/test.tfvars
> Perftest01 offline

- environments/test/test.tfvars
> Perftest01 back online

- environments/prod/prod.tfvars
[[AB#936](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/936)]
```
[ ] Yes
[x] No
```
> Prod00 offline

- environments/prod/prod.tfvars
> Prod00 back online

- environments/prod/prod.tfvars
> Prod01 offline

- environments/prod/prod.tfvars
> Prod01 back online

- modules/app-gateway-module/main.tf
Configuration does not do what is desired. Update corrects rewrite.
https://docs.microsoft.com/en-us/azure/application-gateway/rewrite-http-headers#server-variables
```
[ ] Yes
[x] No
```
> fix(header config): {var_add_x_forwarded_for_proxy}

- environments/demo/backend_lb_config.yaml
- environments/ithc/backend_lb_config.yaml
- environments/prod/backend_lb_config.yaml
- environments/stg/backend_lb_config.yaml
- environments/test/backend_lb_config.yaml
> Add rpe pdf service

- environments/prod/prod.tfvars
> add in JUI redirect

- environments/stg/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/AM-792 
Onboarding AM Judicial Booking application.
```
[ ] Yes
[ ] No
```
> Onboarding AM Judicial Booking application.

- environments/ithc/ithc.tfvars
- environments/test/test.tfvars
PAY-3311 - Exclusion for paybubble
Exclusions need to be added in perftest environment
> Paybubble waf

- environments/test/test.tfvars
> PAY-3311 - Paybubble WAF added exclusion for idam cookie

- environments/demo/backend_lb_config.yaml
- environments/stg/backend_lb_config.yaml
> Added exposing ucmc-service on aat and demo

- environments/demo/backend_lb_config.yaml
- environments/stg/stg.tfvars
> SSCS TYA demo and AAT redirect

- environments/demo/backend_lb_config.yaml
- environments/stg/stg.tfvars
> undo redirect attempt

- environments/demo/backend_lb_config.yaml
- environments/stg/backend_lb_config.yaml
- environments/test/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/SSCS-7588
```
[ ] Yes
[ ] No
```
> SSCS-7758 Remove non prod SSCS-COR-Backend Infra

- environments/ithc/ithc.tfvars
https://tools.hmcts.net/jira/browse/SIDM-4342
ithc - idam-web-admin with ip whitelisting
```
[ ] Yes
[x] No
```
> SIDM-4342 - ithc - idam-web-admin with ip whitelisting

- environments/demo/backend_lb_config.yaml
N/A
ia-case-payments-api Demo env
```
[ ] Yes
[x] No
```
> ia-case-payments-api Demo env

- environments/prod/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/SSCS-7588
```
[ ] Yes
[X] No
```
> SSCS-7588 Remove Prod SSCS-Cor-Backend LB

- environments/stg/stg.tfvars
https://tools.hmcts.net/jira/browse/SIDM-4342
feat(idam-aat): add idam-web-admin to FD
```
[ ] Yes
[x] No
```
> SIDM-4342 - feat(idam-aat): add idam-web-admin to FD

- components/dynatrace_activegate/prod.tf
> add network zone to prod activegate

- components/dynatrace_activegate/prod.tf
> revert back to 3 activegate instances

- environments/prod/prod.tfvars
- environments/stg/stg.tfvars
- environments/test/test.tfvars
https://tools.hmcts.net/jira/browse/SIDM-4342
feat(aat perftest prod): idam-web-admin with ip whitelisting
```
[ ] Yes
[x] No
```
> SIDM-4342 - feat(aat perftest prod): idam-web-admin with ip whitelisting

- environments/sbox/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/SIDM-4430
Disable cookie affinity for idam sandbox as part of the stateless sessions work.
```
[ ] Yes
[x] No
```
> chore(idam-sbox): disable appgw cookie affinity

- azure_pipeline.yaml
- components/cftapps_cluster_lb/main.tf
- components/cftapps_cluster_lb/provider.tf
- components/cftapps_cluster_lb_backend/main.tf
- components/cftapps_cluster_lb_backend/provider.tf
- components/global/main.tf
- components/global/provider.tf
- environments/demo/demo.tfvars
- environments/ithc/ithc.tfvars
- environments/ldata/ldata.tfvars
- environments/prod/prod.tfvars
- environments/ptl/ptl.tfvars
- environments/sbox/sbox.tfvars
- environments/stg/stg.tfvars
- environments/test/test.tfvars
- environments/variables.tf
- modules/app-gateway-module-backend/main.tf
- modules/app-gateway-module-backend/provider.tf
- modules/app-gateway-module-backend/variables.tf
- modules/app-gateway-module/main.tf
- modules/app-gateway-module/provider.tf
- modules/app-gateway-module/variables.tf
- modules/azure-landing-zone/diagnostics.tf
- modules/azure-landing-zone/provider.tf
- modules/azure-landing-zone/variables.tf
[AB#970](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/970)
> Use hmcts-prod/nonprod/sandbox for logs

- environments/prod/prod.tfvars
https://tools.hmcts.net/jira/browse/EUI-2220
__auth__ cookie causing SQL injection rule false positive
DefaultRuleSet-1.0-SQLI-942440
[ { "matchVariableName": "CookieValue:_auth_", "matchVariableValue": "eyJ0eXAiOiJKV1QiLCJ6aXAiOiJOT05FIiwia2lkIjoieEpwTmtUMXE0WkR4QzBQTW5zeS9pNHRTN0QwPSIsImFsZyI6IlJTMjU2" } ]
```
[ ] Yes
[ x] No
```
> ExUI prevent false positive caused by __auth__ cookie

- environments/sbox/sbox.tfvars
- modules/app-gateway-module/main.tf
https://tools.hmcts.net/jira/browse/SIDM-n/a
improvement(idam): allow fe appgw affinity for idam-web-admin
```
[ ] Yes
[x] No
```
> SIDM-n/a - improvement(idam): allow fe appgw affinity for idam-web-admin

- components/cftapps_cluster_lb/provider.tf
- modules/app-gateway-module/main.tf
- modules/app-gateway-module/variables.tf
Updates tf provider to recent version.
Fixes issue with var.frontends for frontdoor and frontend appgw.
Enables cookie based affinity for idam-web-admin on frontend appgw in sbox.
```
[ ] Yes
[x] No
```
> fix(terraform var.frontends) idam-web-admin frontend cookie based affinity

- environments/ithc/ithc.tfvars
- environments/prod/prod.tfvars
- environments/stg/stg.tfvars
- environments/test/test.tfvars
feat(idam): enable affinity for fe idam-web-admin
```
[ ] Yes
[x] No
```
> feat(idam): enable affinity for fe idam-web-admin

- environments/demo/backend_lb_config.yaml
- environments/stg/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/CMC-467
```
[ ] Yes
[x] No
```
> Exposed unspec-service on aat and demo

- environments/stg/backend_lb_config.yaml
- environments/stg/stg.tfvars
> add new app

- environments/demo/backend_lb_config.yaml
- environments/stg/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/CMC-467
Renaming cleanup
```
[ ] Yes
[x] No
```
> Removed ucmc after transition to unspec

- environments/ithc/ithc.tfvars
https://tools.hmcts.net/jira/browse/SIDM-4662
add waf exclusions for idam in ithc
```
[ ] Yes
[x] No
```
> fix(idam): add waf exclusions for ithc

- environments/ithc/ithc.tfvars
https://tools.hmcts.net/jira/browse/SIDM-4662
Add query param exclusions for the idam web admin WAF exclusions in ITHC environment
```
[ ] Yes
[x] No
```
> fix(idam): update ithc waf exclusions for query params

- environments/prod/prod.tfvars
- environments/sbox/sbox.tfvars
- environments/stg/stg.tfvars
- environments/test/test.tfvars
https://tools.hmcts.net/jira/browse/SIDM-4662
Added required waf exclusions for idam web-admin in remaining environments.
```
[ ] Yes
[x] No
```
> fix(idam): added waf exclusions (sidm4662)

- environments/prod/prod.tfvars
[AB#978](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/978)
```
[ ] Yes
[ ] No
```
> Bring both clusters back online in prod

- environments/ithc/ithc.tfvars
- environments/prod/prod.tfvars
- environments/sbox/sbox.tfvars
- environments/stg/stg.tfvars
- environments/test/test.tfvars
- modules/azure-landing-zone/frontdoor_waf_policy.tf
> RDO-8162 additions for multiple match_conditions in FW

- environments/prod/prod.tfvars
adding cookie exemptions for cmc to solve the ongoing prod issue
```
[ ] Yes
[x] No
```
> Prodissuecmc

- environments/prod/prod.tfvars
p2_inc5089506_intermittent_issue_accessing_reform_urls
Fix for prod issue.
```
[ ] Yes
[x] No
```
> fix for prod issue

- environments/stg/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/AM-813
Onboarding AM Organisation Role Mapping application
```
[ ] Yes
[ ] No
```
> Onboarding AM Organisation Role Mapping application

- environments/stg/backend_lb_config.yaml
- environments/test/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/SIDM-n/a
feat(idam): disable idam-api affinity
```
[ ] Yes
[x] No
```
> SIDM-n/a - feat(idam): disable idam-api affinity

- environments/demo/backend_lb_config.yaml
- environments/ithc/backend_lb_config.yaml
- environments/test/backend_lb_config.yaml
> Add entries for caseworker-ref-api

- components/dynatrace_activegate/nonprodukwest.tf
> ukwest nonprod activegate for ukwest palo testing

- environments/prod/prod.tfvars
p1_sscs_inc5089613_some_dwp_users_unable_to_access_cases_due_to_errors_idam
```
[ ] Yes
[x] No
```
> disabling cache for idam web

- environments/ithc/ithc.tfvars
- environments/stg/stg.tfvars
- environments/test/test.tfvars
https://tools.hmcts.net/jira/browse/SIDM-n/a
feat(idam): disable frontdoor cache for web-public to align with prod
also disable cache in nonprod/qa for testing idam-web-admin
```
[ ] Yes
[x] No
```
> SIDM-n/a - feat(idam): disable frontdoor cache for web-public to align with prod

- environments/stg/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/AM-960
```
[ ] Yes
[X] No
```
> Add entries for caseworker-ref-api on stg

- environments/ithc/ithc.tfvars
- environments/stg/stg.tfvars
- environments/test/test.tfvars
This reverts commit b6c21a573aea85a55a8e8e822ee361840c06b685, reversing
changes made to 49becdb0dc2cccced373eac4acabc21936bf77f3.
See https://tools.hmcts.net/jira/browse/RPE-1237
> Revert "Merge pull request #396 from hmcts/idam-fd-cache"

- environments/stg/backend_lb_config.yaml
Added wa-workflow-api to backend lb for stg
> Added wa-workflow-api to backend lb for stg

- environments/demo/backend_lb_config.yaml
- environments/ithc/backend_lb_config.yaml
- environments/stg/backend_lb_config.yaml
- environments/test/backend_lb_config.yaml
> Add camunda LB config

- environments/demo/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/RDCC-1758
```
[ ] Yes
[x] No
```
> Add RD JDL and JRD

- environments/prod/prod.tfvars
https://tools.hmcts.net/jira/browse/SIDM-4749
fix(idam-web-admin): turn off caching
```
[ ] Yes
[x] No
```
> SIDM-4749 - fix(idam-web-admin): turn off caching

- environments/ithc/ithc.tfvars
feat(idam.ssosession): exclude session cookie
> feat(idam.ssosession): exclude session cookie

- environments/ithc/ithc.tfvars
previous merge did not apply successfully but succeeded anyway
fix(idam): waf policy
> fix(idam): waf policy

- environments/prod/backend_lb_config.yaml
- environments/prod/prod.tfvars
https://tools.hmcts.net/jira/browse/SIDM-4430
Disable app gw session affinity cookie due to stateless session implementation.
```
[ ] Yes
[x] No
```
> chore(idam-prod): disable appgw cookie affinity

- environments/test/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/RDCC-1769
Add location-ref-api service
```
[ ] Yes
[X] No
```
> Add RD location-ref-api service

- environments/stg/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/RDCC-1769
Add location-ref-api on staging
```
[ ] Yes
[X] No
```
> Add location-ref-api on staging

- environments/stg/stg.tfvars
https://tools.hmcts.net/jira/browse/SIDM-4829
idam 4.0 exclusions
```
[ ] Yes
[x] No
```
> SIDM-4829 - idam 4.0 exclusions

- environments/prod/prod.tfvars
> revert traffic to both clusters

- environments/demo/backend_lb_config.yaml
- environments/stg/backend_lb_config.yaml
Added workflow-api and task-management-api
> WA - Added workflow-api and task-management-api

- environments/sbox/sbox.tfvars
Adding Front Door configuration for HMI POC.  The backend is configured to point to a new PIP, with a NAT rule that forwards traffic to the HMI API Management load balancer private IP.
```
[ ] Yes
[ x ] No
```
> Add HMI POC

- environments/sbox/sbox.tfvars
> HMI POC typo fix

- environments/demo/backend_lb_config.yaml
- environments/stg/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/RWA-112
Added wa-task-configuration-api
```
[ ] Yes
[x ] No
```
> Added wa-task-configuration-api

- environments/sbox/sbox.tfvars
> change apim-poc backend

- environments/ithc/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/RPET-433
added CFS app for ITHC
```
[ ] Yes
[x] No
```
> RPET-433-Div-ITHC

- environments/sbox/sbox.tfvars
Changing HMI entry from PoC to sbox
> update hmi poc > sbox

- modules/dynatrace-activegate/vm.tf
> Active gate module local prefix uk west

- environments/test/test.tfvars
Cookie exclusions on perftest environment
> Perftest frontdoor waf

- environments/stg/backend_lb_config.yaml
> adding fact api to staging config

- modules/dynatrace-activegate/cloudconfig.tpl
- modules/dynatrace-activegate/variables.tf
- modules/dynatrace-activegate/vm.tf
[AB#1084]
```
[ ] Yes
[ ] No
```
> Active Gate plugins installation

- modules/dynatrace-activegate/cloudconfig.tpl
> cloud-init yaml parsing fixes for activegate

- modules/dynatrace-activegate/cloudconfig.tpl
> Fix activategate plugins unzip/install

- environments/ithc/backend_lb_config.yaml
N/A
IA Home Office integration ithc
```
[ ] Yes
[x] No
```
> IA Home Office integration ithc

- environments/ithc/backend_lb_config.yaml
> AAC product config for ithc

- environments/test/test.tfvars
As part of this change https://tools.hmcts.net/jira/browse/PAY-3343, we would like to add configuration
to whitelist the required range of ips in perftest environment.
1) Changes have been reviewed from Devops.
2) We have the necessary approval to make changes in perftest for same.
> Pay 3343 - Fees register new domain for whitelisting of ips

- environments/test/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/RPET-460
Added CFS app to perftest
```
[ ] Yes
[x] No
```
> RPET-460-Div-perftest

- environments/test/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/RPET-460
Added the finrem apps
```
[ ] Yes
[x] No
```
> RPET-460-Finrem-perftest

- environments/prod/prod.tfvars
1) We have IA approval for changes.
2) Required configuration has been tested on perftest and other lower environments.
3) Last 6 months production issues have been covered in and required code fixes are also done.
4) We are going to monitor production logs after the changes
> Front door WAF activation for paybubble on prod

- environments/prod/prod.tfvars
feat(idam 4.0.0): add sso exclusions
> feat(idam 4.0.0): add sso exclusions

- components/global/provider.tf
chore(azurerm): update version
> chore(azurerm): update version

- environments/demo/demo.tfvars
[AB#1119]
```
[ ] Yes
[ ] No
```
> Update demo vnet ip range

- environments/ithc/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/RPET-516
Added finrem apps to ithc
```
[ ] Yes
[x] No
```
> RPET-516-Finrem-Ithc

- azure_pipeline.yaml
> Add dev environment

- environments/dev/dev.tfvars
As dns zones for SDS dev test and stg won't be present for now, changing custom domain dev. > preview.platform.hmcts.net
> chaged custom domain dev>preview

- environments/prod/prod.tfvars
- environments/stg/stg.tfvars
- environments/test/test.tfvars
> Bulkscan migration

- environments/sbox/sbox.tfvars
- environments/test/test.tfvars
renamed sbox entry "hmi-apim-sbox" > "hmi-apim" and added test environment entry "hmi-apim"
```
[ ] Yes
[x ] No
```
> Hmi apim entries

- environments/ldata/ldata.tfvars
- environments/sbox/sbox.tfvars
- environments/test/test.tfvars
feat(idam): add sso exclusions
> feat(idam): add sso exclusions

- environments/sbox/sbox.tfvars
Reverts hmcts/azure-platform-terraform#457
> Revert "Remove one entry to fix state"

- environments/test/test.tfvars
- [ x] commit messages are meaningful and follow good commit message guidelines
```
[ ] Yes
[ x ] No
```
> Update custom dns names

- environments/test/test.tfvars
> Update backends for bulkscan-demo

- environments/prod/prod.tfvars
> remove prod config until perftest is working

- modules/azure-landing-zone/frontdoor.tf
Resolves "context deadline exceeded" error
```
[ ] Yes
[ x ] No
```
> add read timeoutto frontdoor

- modules/azure-landing-zone/frontdoor.tf
30 minutes did not resolve the failing pipeline, but did appear to have a positive impact.
```
[ ] Yes
[ x ] No
```
> Increase timeout to 4 hours

- environments/test/test.tfvars
> Update perftest ip range

- environments/test/test.tfvars
> remove bulkscan and reformscan frontends

- environments/test/test.tfvars
Reverts hmcts/azure-platform-terraform#467
> Revert "remove idam-web-public from perftest to allow green build"

- environments/test/test.tfvars
> test new waf rule

- environments/test/test.tfvars
> add restrictions to fees-register

- environments/test/test.tfvars
Testing WAF filtering on fees-register
```
[ ] Yes
[ x ] No
```
> update uri match value

- azure_pipeline.yaml
> Fix typo in demo apply params

- environments/test/test.tfvars
Testing new config as previous tests did not work
```
[ ] Yes
[ x ] No
```
> reverse logic and switch conditions around

- environments/demo/demo.tfvars
- environments/test/test.tfvars
> Bulk scan config for perftest FD

- environments/test/test.tfvars
> correct fd config for bulk scan

- environments/stg/stg.tfvars
- environments/test/test.tfvars
> Add fact and fact-admin to perftest... and also add fact-admin to aat

- environments/dev/dev.tfvars
- environments/sbox/backend_lb_config.yaml
- environments/sbox/sbox.tfvars
- environments/stg/stg.tfvars
> Bulk Scan FD config

- environments/stg/stg.tfvars
> Routing traffic to aat-00 only

- environments/test/test.tfvars
> Correct bulkscan perftest backend

- environments/stg/stg.tfvars
> rerouting traffic to aat-01 only as rebuilding aat-00

- environments/stg/stg.tfvars
> changes to include aat-00 to accept traffic

- environments/test/test.tfvars
- modules/azure-landing-zone/frontdoor.tf
enable setting backend header.
if new `host_header` not set default will `custom_domain`
```
[ ] Yes
[x] No
```
> Add configurable backend header

- environments/test/test.tfvars
- modules/azure-landing-zone/frontdoor.tf
add parametric forwarding protocol
```
[ ] Yes
[x] No
```
> add parametric forwarding protocol

- environments/test/test.tfvars
- modules/azure-landing-zone/frontdoor.tf
add parametric health path
```
[ ] Yes
[x] No
```
> add parametric health path

- environments/test/test.tfvars
- modules/azure-landing-zone/frontdoor.tf
add parametric health protocol
```
[ ] Yes
[x] No
```
> add parametric health protocol

- environments/ithc/ithc.tfvars
feat(idam-web-admin): ithc exclusions
> feat(idam-web-admin): ithc exclusions

- environments/test/test.tfvars
remove reform-bulk scan frontdoors
```
[ ] Yes
[x] No
```
> remove reform-bulk scan frontdoors

- environments/test/test.tfvars
revert- remove reform-bulk scan frontdoors
```
[ ] Yes
[x] No
```
> revert- remove reform-bulk scan frontdoors

- environments/ithc/backend_lb_config.yaml
- environments/ithc/ithc.tfvars
> Add fact to ithc

- components/global/main.tf
- environments/test/test.tfvars
- environments/variables.tf
- modules/azure-landing-zone/frontdoor.tf
- modules/azure-landing-zone/variables.tf
disable back end pool certificate_name_check
```
[ ] Yes
x ] No
```
> disable back end pool certificate_name_check

- environments/demo/backend_lb_config.yaml
- environments/ithc/backend_lb_config.yaml
- environments/test/backend_lb_config.yaml
RIA-3620, 3621, 3622: Set up Demo, ITHC and Perftest environment for ia-timed-event-service
https://tools.hmcts.net/jira/browse/RIA-3620
https://tools.hmcts.net/jira/browse/RIA-3621
https://tools.hmcts.net/jira/browse/RIA-3622
> RIA-3622: Set up Perftest environment for ia-timed-event-service

- environments/stg/stg.tfvars
- environments/test/test.tfvars
add bulk and reform scan front door settings
```
[ ] Yes
[ ] No
```
> add bulk and reform scan front door settings

- environments/prod/prod.tfvars
Add FD entry for hmiapim prod
```
[ ] Yes
[x ] No
```
> add hmi prod

- environments/prod/backend_lb_config.yaml
N/A
IA Home Office Integration API Prod release
[Tech Readiness Approval](https://tools.hmcts.net/confluence/display/RSTR/Immigration+and+Asylum+-+Rel+4.0.0+-+Home+Office+Integration+API+1)
```
[ ] Yes
[x] No
```
> IA Home Office Integration API Prod release

- environments/prod/prod.tfvars
> routing to prod-00 only as rebuilding prod-01

- environments/prod/prod.tfvars
> redirecting traffic to prod01 only

- environments/prod/prod.tfvars
> prod to accept full load

- environments/demo/backend_lb_config.yaml
- environments/test/backend_lb_config.yaml
NA
Onboarding AM Org Role Mapping Service.
```
[ ] Yes
[ ] No
```
> Onboarding AM Org Role Mapping Service.

- environments/prod/backend_lb_config.yaml
N/A
IA Case Payments API Prod release
[Tech Readiness Approval](https://tools.hmcts.net/confluence/pages/viewpage.action?pageId=1412040095&__ncforminfo=CCSUe8YrjctkCgFDIa6t1teGXMsyhJimp_HquEtJT88dgyeFrZiWJWvQ_aAb3054tRgqGPR4WrM=)
```
[ ] Yes
[x] No
```
> IA Case Payments API Prod release

- environments/prod/prod.tfvars
- environments/stg/stg.tfvars
> correct prod domain

- environments/stg/stg.tfvars
> Remove AAT 01 traffic

- environments/prod/prod.tfvars
Requires https://github.com/hmcts/azure-public-dns/pull/368
> Add reform scan prod frontdoor config

- environments/stg/stg.tfvars
Reverts hmcts/azure-platform-terraform#544
> Revert "Remove AAT 01 traffic"

- environments/ithc/ithc.tfvars
> routing to ithc-00 only as rebuilding ithc-01

- environments/demo/backend_lb_config.yaml
> Add XUI T&Cs Int LB config

- environments/ithc/ithc.tfvars
Add in ithc-01 after being reconfigured with managed identity 
```
[ ] Yes
[X] No
```
> Add ithc-01 with managed identity

- azure_pipeline.yaml
Divorce had another outage last night because cert was disabled, needs investigating before this is run again
> Disable terraform against prod for frontdoor

- environments/ithc/ithc.tfvars
Add in ithc-00 after being reconfigured with managed identity
```
[ ] Yes
[X] No
```
> Add ithc-00 with managed identities into AGW

- environments/ithc/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/SIDM-5087 
Clean up.
```
[ ] Yes
[x] No
```
> Remove debug config

- environments/prod/backend_lb_config.yaml
> added AAC to prod LB config

- environments/prod/prod.tfvars
disable cert name check for Prod
```
[ ] Yes
[x] No
```
> disable cert name check for Prod

- environments/prod/prod.tfvars
- environments/stg/stg.tfvars
- environments/test/test.tfvars
feat(idam): v5 exclusions for perftest and aat
> feat(idam): v5 exclusions for perftest, aat, prod

- environments/demo/demo.tfvars
reform scan fd config
```
[ ] Yes
[x] No
```
> reform scan fd config

- environments/dev/dev.tfvars
- environments/stg/stg.tfvars
- environments/test/test.tfvars
> updated hmi domains

- environments/test/test.tfvars
feat(idam): perftest add keycloak
> feat(idam): perftest add keycloak

- environments/stg/stg.tfvars
> remove whitelist

- environments/stg/stg.tfvars
Removing aat-01 from AGW to be rebuilt with AKS Managed Identity
```
[ ] Yes
[X] No
```
> Remove aat-01 for rebuild with AKS Managed Identity

- environments/stg/stg.tfvars
Add aat-01 into AGW pool with AKS Managed Identity 
```
[ ] Yes
[X] No
```
> Add aat-01 to AGW

- azure_pipeline.yaml
Remove sbox global references to test in another pipeline
```
[ ] Yes
[X] No
```
> Remove sbox global references to test in another pipeline

- environments/test/backend_lb_config.yaml
feat(keycloak): perftest. add http listener
> feat(keycloak): perftest. add http listener

- environments/stg/stg.tfvars
Remove aat-01 from AGW for AKS Managed Identity rebuild
```
[ ] Yes
[X] No
```
> Remove aat-01 from AGW for AKS Managed Identity rebuild

- environments/stg/stg.tfvars
Add aat-00 back into AGW
```
[ ] Yes
[X] No
```
> Add aat-00 back into AGW

- environments/test/backend_lb_config.yaml
feat(keycloak): remove https listener
the listener name is the unique key.
> feat(keycloak): remove https listener

- environments/prod/prod.tfvars
> Fact Admin to Detection Update prod.tfvars

- azure_pipeline.yaml
Stage Precheck created to delay pipeline being ran if another run is already inProgress. To assist with mitigation of locks and failed deployments during PR.
```
[ ] Yes
[X] No
```
> Terraform pipeline delayloop

- environments/prod/prod.tfvars
Remove prod-01 from App Gateway to rebuild with AKS Managed Identity 
```
[ ] Yes
[X] No
```
> Remove Prod-01 from AppGateway

- environments/prod/prod.tfvars
Add prod-01 back to AGW after rebuild with AKS Managed Identity
```
[ ] Yes
[X] No
```
> Add prod-01 back to AGW after rebuild with AKS Managed Identity

- environments/prod/prod.tfvars
Remove Prod-00 from AGW for AKS rebuild Managed Identity
```
[ ] Yes
[X] No
```
> Remove prod-00 from AGW to rebuild with AKS Managed Identity

- environments/prod/prod.tfvars
Add Prod-00 back to AGW after AKS Managed Identity Rebuild
```
[ ] Yes
[X] No
```
> Add Prod-00 back to AGW after AKS Managed Identity Rebuild

- environments/prod/backend_lb_config.yaml
NA
refactor: enable location reference data production
NA
> refactor: enable location reference data production

- azure_pipeline-global.yaml
- azure_pipeline.yaml
Add variable timeoutinminutes
```
[ ] Yes
[X] No
```
> Add variable timeoutinminutes

- environments/sbox/sbox.tfvars
Temporarily removing HMI entry
> remove hmi

- environments/sbox/sbox.tfvars
Reverts hmcts/azure-platform-terraform#602
> Revert "remove hmi"

- environments/test/test.tfvars
Remove perftest-00 from AGW for AKS ManagedIdentity rebuild
```
[ ] Yes
[X] No
```
> Remove perftest-00 from AGW

- environments/test/test.tfvars
Add perftest-00 back to AGW after AKS rebuild
```
[ ] Yes
[X] No
```
> Add perftest-00 back to AGW after AKS rebuild

- environments/test/test.tfvars
Remove perftest01 AKS Managed identity rebuild
```
[ ] Yes
[X] No
```
> Remove perftest01 AKS Managed identity rebuild

- environments/test/test.tfvars
Add perftest-01 to AGW after AKS Managed Identity rebuild
```
[ ] Yes
[X] No
```
> Add perftest-01 to AGW after AKS Managed Identity rebuild

- azure_pipeline-global.yaml
- azure_pipeline.yaml
- pipeline-scripts/file-check-changes.sh
- pipeline-templates/terraform.yaml
Changes to allow only a terraform apply to run if a specific file has been changed, override option included - if set to $true it will ignore the files check and run terraform apply
```
[ ] Yes
[X] No
```
> Changes to allow specific files to be checked

- pipeline-templates/terraform.yaml
Update to correct file name
```
[ ] Yes
[X] No
```
> update file location

- azure_pipeline.yaml
- components/shutter/cdn_profile.tf
- components/shutter/module_shutter.tf
- environments/sbox/sbox.tfvars
- modules/shutter_page/cdn_endpoints.tf
- modules/shutter_page/cdn_profiles.tf
- modules/shutter_page/custom_domains.tf
- modules/shutter_page/enable_https.tf
- modules/shutter_page/storage_account.tf
- modules/shutter_page/storage_container.tf
- modules/shutter_page/variables.tf
Redesign of CDN profile(s) to create on a team basis rather than one CDN profile per environment. 
```
[ ] Yes
[X] No
```
> CDN Module rewrite

- environments/test/backend_lb_config.yaml
- environments/test/test.tfvars
> remove service names NFDIV perftest

- environments/test/backend_lb_config.yaml
- environments/test/test.tfvars
> add back NFDIV perftest

- environments/demo/backend_lb_config.yaml
- environments/ithc/backend_lb_config.yaml
- environments/ldata/backend_lb_config.yaml
- environments/prod/backend_lb_config.yaml
- environments/stg/backend_lb_config.yaml
- environments/test/backend_lb_config.yaml
> Add ccd-message-publisher

- azure_pipeline.yaml
- environments/prod/prod.tfvars
Add Product for prod.tfvars for CDN rebuild
Please review & confirm Product is correct for each - in theory it will be teams name/reference
```
[ ] Yes
[X] No
```
> Add Product for prod.tfvars for CDN rebuild

- modules/shutter_page/custom_domains.tf
- modules/shutter_page/enable_https.tf
To remove if frontend.name != "jui-redirect" from custom domain & enable https due to known issue.
```
[ ] Yes
[X] No
```
> To remove if frontend.name != "jui-redirect" from custom domain 

- azure_pipeline.yaml
- ci/terraform-lint.tests.ps1
- environments/prod/prod.tfvars
> failover to 01

- environments/demo/demo.tfvars
> Swap to demo 01

- environments/demo/demo.tfvars
Reverts hmcts/azure-platform-terraform#619
This will help demo-01 rebuild
> Revert "Swap to demo 01"

- environments/sbox/sbox.tfvars
https://tools.hmcts.net/jira/browse/SIDM-5300
Allow for service client_ids with special characters.
```
[ ] Yes
[x] No
```
> WAF exclusion for IDAM Admin UI

- environments/sbox/sbox.tfvars
https://tools.hmcts.net/jira/browse/SIDM-5300
Allow for service client_ids with special characters.
```
[ ] Yes
[x] No
```
> WAF exclusion for IDAM Admin UI in Sandbox

- azure_pipeline-global.yaml
Disable sandbox in azure devops to run tf locally 
```
[ ] Yes
[x] No
```
> DTSPO-75 - disabling sbox to run terraform locally

- azure_pipeline-global.yaml
- components/cftapps_cluster_lb_backend/main.tf
- components/global/local.tf
- components/global/log_analytics.tf
- components/global/main.tf
- components/global/provider.tf
- components/global/rg.tf
- environments/variables.tf
- modules/app-gateway-module-backend/main.tf
- modules/app-gateway-module/variables.tf
- modules/azure-landing-zone/diagnostics.tf
- modules/azure-landing-zone/variables.tf
- modules/cosmosdb/output.tf
- modules/shutter_page/enable_https.tf
- modules/standards/tag_governance_policy.tf
https://tools.hmcts.net/jira/browse/DTSPO-429
- Migrated to shared frontdoor module.
- Using log analytics workspace id module
- upgraded tf to 0.13 (will be upgrading to 14 once terraform has been applied to each environment)
- upgraded azurerm provider to 2.41.0
- ran terraform fmt to fix pester tests for 0.13 upgrade
```
[ ] Yes
[x] No
```
> DTSPO-75 migrate to shared module

- azure_pipeline-global.yaml
- components/global/main.tf
- setting branch to master for the frontdoor module to complete migration.
```
[ ] Yes
[x] No
```
> DTSPO-75 - set frontdoor module's branch to master

- environments/stg/stg.tfvars
> Fact enable ssl  in aat Update stg.tfvars

- environments/stg/stg.tfvars
Remove aat-00 from AGW for ephemeral disk rebuild
```
[ ] Yes
[X] No
```
> Remove aat-00 from AGW for ephemeral disk rebuild

- environments/test/test.tfvars
> Updating custom rules to block fees url

- environments/prod/prod.tfvars
second round exclusions for body fields, request params and cookies
```
[ ] Yes
[X] No
```
> second round exclusions for body fields, request params and cookies

- environments/prod/prod.tfvars
correction attempt for second round exclusions for body fields, request params and cookies
```
[ ] Yes
[X] No
```
> Rdm 10871 reduce false positives

- environments/stg/stg.tfvars
Add aat-00 after AKS rebuild with ephemeral disk & AKS upgrade 1.19.6
```
[ ] Yes
[X] No
```
> Add aat-00 after AKS rebuild with ephemeral disk & AKS upgrade 1.19.6

- environments/prod/prod.tfvars
add further exclusions on ccd web
```
[ ] Yes
[X] No
```
> add further exclusions on ccd web

- environments/test/test.tfvars
1) Modified existing custom rule
2) Modified exclusions for params
> PAY-3343 - WAF rule changes after prevention mode

- environments/prod/prod.tfvars
add further exclusions on ccd gateway and print service
```
[ ] Yes
[X] No
```
> exclude BNES_dtCookie from ccd api gw and dtSa from case doc service

- environments/stg/stg.tfvars
https://tools.hmcts.net/jira/projects/DTSPO/issues/DTSPO-751
```
[ ] Yes
[x ] No
```
> nfdiv-end-civil-partnership aat

- azure_pipeline-global.yaml
- environments/prod/prod.tfvars
AAT is currently running, so avoiding it for now.
```
[ ] Yes
[x] No
```
> Remove prod-01

- azure_pipeline-global.yaml
- environments/prod/prod.tfvars
Reverts hmcts/azure-platform-terraform#650
> Revert "Remove prod-01"

- environments/prod/prod.tfvars
> Remove prod-00

- environments/prod/prod.tfvars
Reverts hmcts/azure-platform-terraform#652
> Revert "Remove prod-00"

- environments/demo/demo.tfvars
Swap to demo-00 AKS 1.19 rebuild
```
[ ] Yes
[X] No
```
> Swap to demo-00 AKS 1.19 rebuild

- environments/ldata/backend_lb_config.yaml
- environments/ldata/ldata.tfvars
> Adding ldata xui

- environments/demo/demo.tfvars
- environments/ithc/ithc.tfvars
- environments/test/test.tfvars
https://tools.hmcts.net/jira/browse/NFDIV-430
Add additional nfdiv domains to ITHC Perftest & Demo
```
[ ] Yes
[x ] No
```
> add extra NFDIV Frontends

- environments/prod/prod.tfvars
https://tools.hmcts.net/jira/browse/RDM-11072
```
[ ] Yes
[x] No
```
> Update prod.tfvars remove unneeded CCD exclusions

- environments/demo/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/RDCC-2413
Create LRD endpoints
```
[ ] Yes
[X] No
```
> Add LRD API and Data Load endpoints

- environments/prod/prod.tfvars
- environments/stg/stg.tfvars
> SSCS-8680 SSCS WAF exclusions

- modules/app-gateway-module-backend/main.tf
> add hostname prefix for appgw backends

- modules/app-gateway-module-backend/main.tf
Reverts hmcts/azure-platform-terraform#664
> Revert "add hostname prefix for appgw backends"

- environments/stg/stg.tfvars
> Add AAT-01 backend

- modules/app-gateway-module-backend/main.tf
> Add hostname prefix option for backend appgw

- environments/sbox/backend_lb_config.yaml
> Adding docmosis sbox

- environments/stg/backend_lb_config.yaml
Added ccd components from civil damages staging
```
[ ] Yes
[x] No
```
> Added ccd components from civil damages staging

- environments/ithc/backend_lb_config.yaml
- environments/stg/backend_lb_config.yaml
- environments/test/backend_lb_config.yaml
> Add docmosis to ithc, aat, perftest lb config

- environments/stg/backend_lb_config.yaml
Applying reverted hmcts/azure-platform-terraform#671 PR adding ccd components from civil damages staging
```
[ ] Yes
[x] No
```
> Applying reverted 671 PR

- environments/prod/backend_lb_config.yaml
> Adding docmosis prod config

- environments/demo/backend_lb_config.yaml
> Add docmosis demo

- azure_pipeline.yaml
Remove ITHC AppGWs to reconfigure IP addressing in ITHC
```
[ ] Yes
[X] No
```
> Remove ITHC AppGWs to reconfigure IP addressing in ITHC

- azure_pipeline.yaml
Add AppGWs to ITHC and enable true flag
```
[ ] Yes
[X] No
```
> Add AppGWs to ITHC and enable true flag

- environments/ithc/ithc.tfvars
Update to correct ITHC subnet for AppGws
```
[ ] Yes
[X] No
```
> Update to correct ITHC subnet for AppGws

- azure_pipeline.yaml
Update alwaysApply flag to false on ITHC LB
```
[ ] Yes
[X] No
```
> Update alwaysApply flag to false on ITHC LB

- environments/test/test.tfvars
None
Adds divorce frontends to Azure Front Door in perftest env
```
[ ] Yes
[x] No
```
> Add divorce frontends to Azure Front Door in perftest env

- environments/prod/prod.tfvars
- environments/stg/stg.tfvars
Fees register changes have been tested on Perftest and we need to move these changes to AAT and Prod.
Perftest pr:-
https://github.com/hmcts/azure-platform-terraform/pull/643/files
Parent ticket :- 
https://tools.hmcts.net/jira/browse/PAY-3343
> PAY-3343 - WAF changes for Fees register for AAT,Prod

- environments/test/backend_lb_config.yaml
Added entries for work allocation services in perftest
```
[ ] Yes
[x ] No
```
> Added entries for work allocation services in perftest

- environments/prod/prod.tfvars
RDM-11476
```
[ ] Yes
[x] No
```
> Update prod.tfvars CCD FPs

- environments/stg/stg.tfvars
Removing aat00 to test Neuvector deployment with rebuild
```
[ ] Yes
[X] No
```
> Removing aat00 to test Neuvector deployment with rebuild

- environments/demo/backend_lb_config.yaml
> added "case-document-am-api" to demo lb config

- environments/prod/prod.tfvars
Reverts hmcts/azure-platform-terraform#692
RDM-11476, as per Mutlu, needs SECOPS approval
> Revert "Update prod.tfvars CCD FPs"

- environments/stg/stg.tfvars
Reverts hmcts/azure-platform-terraform#693
> Revert "Removing aat00 to test Neuvector deployment with rebuild"

- environments/test/test.tfvars
None
Switches divorce frontends in perftest into detection mode.
```
[ ] Yes
[x] No
```
> Switch divorce frontends in perftest envrionment into detection mode

- environments/prod/prod.tfvars
https://tools.hmcts.net/jira/browse/RDM-11476
```
[ ] Yes
[ ] No
```
> Update prod.tfvars RDM-11476 AWAITING SECOPS

- environments/stg/stg.tfvars
https://tools.hmcts.net/jira/browse/SSCS-8853
Deploying to aat for testing
```
[ ] Yes
[x] No
```
> sscs 8853 deploy just to test

- environments/ithc/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/AM-1242
```
[ ] Yes
[X] No
```
> Add ITHC environment for RAS and ORMS

- environments/prod/prod.tfvars
- environments/stg/stg.tfvars
https://tools.hmcts.net/jira/browse/SSCS-8853
Adding exlusions for MYA and SYA fields that are getting blocked
```
[ ] Yes
[x] No
```
> sscs 8853 adding exclusions

- environments/prod/prod.tfvars
> add listener for courttribunalfinder redirect

- environments/prod/prod.tfvars
> amend domain courttribunalfinder

- environments/prod/prod.tfvars
> revert ctf listener

- environments/demo/backend_lb_config.yaml
- environments/stg/backend_lb_config.yaml
> Case-payment-orders-api to aat and demo

- environments/demo/backend_lb_config.yaml
- environments/ithc/backend_lb_config.yaml
- environments/stg/backend_lb_config.yaml
- environments/test/backend_lb_config.yaml
Tested and verified on sandbox.
```
[ ] Yes
[ x] No
```
> Add to other docmosis instances, already tested on sandbox

- environments/ldata/backend_lb_config.yaml
> force change via change in cert name

- environments/stg/backend_lb_config.yaml
> DTSPO-1869 - remove

- environments/stg/stg.tfvars
Reverts hmcts/azure-platform-terraform#716
> Revert "Remove aat00 for rebuild"

- environments/stg/stg.tfvars
remove aat01 for cluster rebuild
```
[ ] Yes
[X] No
```
> remove aat01 for cluster rebuild

- environments/stg/stg.tfvars
Reverts hmcts/azure-platform-terraform#722
> Revert "remove aat01 for cluster rebuild"

- components/cftapps_private_dns/scripts/tf_import_dns.sh
Update terraform import privatedns script
- Added if -n due to some $PRODUCT_COMPONENT not having an A record and script erroring when trying to terraform import.
```
[ ] Yes
[X] No
```
> Update terraform import privatedns script

- environments/demo/backend_lb_config.yaml
Added ia-home-office-integration-api component to demo environment
```
[ ] Yes
[X] No
```
> Added ia-home-office-integration-api component to demo environment

- environments/stg/stg.tfvars
Remove aat01 from App Gateway
```
[ ] Yes
[X] No
```
> Remove aat01 from App Gateway

- environments/demo/backend_lb_config.yaml
Added ia-home-office-mock-api component to demo environment
```
[ ] Yes
[X] No
```
> Added ia-home-office-mock-api component to demo environment

- environments/ithc/backend_lb_config.yaml
- environments/stg/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/RWA-425
> configure lb for the wa ithc

- environments/stg/stg.tfvars
Reverts hmcts/azure-platform-terraform#729
> Revert "Remove aat01 from App Gateway"

- azure_pipeline.yaml
- components/cftapps_private_dns/main.tf
- environments/test/backend_lb_config.yaml
- environments/test/test.tfvars
Add private dns for perftest and fix files_list for sbox and ithc
```
[ ] Yes
[X] No
```
> Add private dns for perftest and fix files_list for sbox and ithc

- azure_pipeline.yaml
Set alwaysApply to True for ithc private dns
```
[ ] Yes
[X] No
```
> Set alwaysApply to True for ithc private dns

- azure_pipeline.yaml
Terraform apply complete, now reverting to remove alwaysApply: true
> Revert "Set alwaysApply to True for ithc private dns"

- azure_pipeline.yaml
- environments/demo/backend_lb_config.yaml
- environments/demo/demo.tfvars
Add demo private dns component
```
[ ] Yes
[X] No
```
> Add demo private dns component

- environments/test/test.tfvars
https://tools.hmcts.net/jira/browse/NFDIV-556
[ ] No
```
> Switch NFDIV Backend Update test.tfvars

- azure_pipeline.yaml
- environments/stg/backend_lb_config.yaml
- environments/stg/stg.tfvars
Add additional app gateway & private dns component
- Raised PR, will merge Monday providing no AAT-related issues
```
[ ] Yes
[X] No
```
> Add additional app gateway & private dns component

- environments/stg/backend_lb_config.yaml
- environments/stg/stg.tfvars
Update private IP , previous was incorrect to subnet size
```
[ ] Yes
[X] No
```
> Update private IP , previous was incorrect to subnet size

- environments/ithc/ithc.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-2033
Removing-ithc-00
```
[ ] Yes
[X ] No
```
> Removing-ithc-00

- environments/stg/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/CMC-1162
```
[ ] Yes
[x] No
```
> Exposed gateway and user profile for civil damages

- azure_pipeline.yaml
typo & manual pipeline trigger
```
[ ] Yes
[X] No
```
> typo & manual pipeline trigger

- environments/prod/prod.tfvars
Adding request cookie names to paybubble
```
[ ] Yes
[ ] No
```
> Adding request cookie names to paybubble

- environments/prod/prod.tfvars
https://tools.hmcts.net/jira/browse/RDM-11651
```
[ ] Yes
[x] No
```
> Update prod.tfvars ▒▒▒ PLEASE DO NOT MERGE AWAITING SECOPS ▒▒▒

- environments/ithc/ithc.tfvars
Adding ITHC 00 into cluster IPs
```
[ ] Yes
[ X] No
```
> Adding ITHC 00 in

- environments/ithc/ithc.tfvars
removing ithc01 for rebuild
```
[ ] Yes
[ X] No
```
> removing ithc01 for rebuild

- environments/demo/backend_lb_config.yaml
- environments/ithc/backend_lb_config.yaml
- environments/prod/backend_lb_config.yaml
- environments/stg/backend_lb_config.yaml
- environments/test/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/RBC-7423
Added in HRS projects
```
[ ] Yes
[X] No
```
> Added in HRS projects

- environments/stg/stg.tfvars
removing aat 01 for rebuild
```
[ ] Yes
[X ] No
```
> removing aat 01 for rebuild

- environments/demo/backend_lb_config.yaml
- environments/ithc/backend_lb_config.yaml
- environments/stg/backend_lb_config.yaml
- environments/test/backend_lb_config.yaml
> remove nfdiv-cos and cms Update backend_lb_config.yaml

- environments/stg/stg.tfvars
Adding AAT-01 back after rebuild
```
[ ] Yes
[ ]X No
```
> Adding AAT-01 back after rebuild

- environments/stg/stg.tfvars
removing 00 for rebuild
```
[ ] Yes
[ X] No
```
> removing 00 for rebuild

- environments/stg/stg.tfvars
Adding AAT 00 after rebuild
```
[ ] Yes
[X ] No
```
> Adding AAT 00 after rebuild

- environments/prod/prod.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-1894
Removing 00 to do AKS update and rebuild
```
[ ] Yes
[ X] No
```
> Removing 00 to do AKS update and rebuild

- environments/prod/prod.tfvars
Adding Prod-00 after rebuild
```
[ ] Yes
[ X] No
```
> Adding Prod-00 after rebuild

- environments/prod/prod.tfvars
> add in courtfinder redirect

- environments/prod/prod.tfvars
> revert add in courtfinder redirect

- environments/prod/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/AM-1295
Add gateway configurations for RAS production release
```
[ ] Yes
[X] No
```
> Add gateway config for RAS services

- azure_pipeline.yaml
Manual run complete, reverting to remove alwaysApply: true flags
> Revert "Manual run to fix em-hrs private dns"

- environments/demo/backend_lb_config.yaml
- environments/ithc/backend_lb_config.yaml
- environments/stg/backend_lb_config.yaml
- environments/test/backend_lb_config.yaml
Exposing newly added Civil Damages Service pods: https://github.com/hmcts/cnp-flux-config/pull/9024
```
[ ] Yes
[x] No
```
> Added Civil Damages Service to all environments

- environments/stg/backend_lb_config.yaml
Fixing the error:
https://github.com/hmcts/azure-platform-terraform/runs/2298627807
```
[ ] Yes
[x] No
```
> Moved civil damages service from aks00-aat-agw to aks01-aat-agw

- environments/prod/prod.tfvars
> revert revert add in courtfinder redirect

- environments/demo/demo.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-2033
swapped cluster IP for demo env.
```
[ ] Yes
[ X] No
```
> swap demo for aks upgrade

- environments/prod/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/RDCC-2692
Add gateway config for RD Caseworker Ref API service
```
[ ] Yes
[X] No
```
> Add gateway config for caseworker-ref-api

- azure_pipeline.yaml
https://tools.hmcts.net/jira/browse/DTSPO-380
Removed sbox-compliance pipeline stage.  Deemed no longer required.
```
[ ] Yes
[x] No
```
> DTSPO 380 - Modules tagging 2

- environments/stg/backend_lb_config.yaml
[RIA-4243](https://tools.hmcts.net/jira/browse/RIA-4243)
IA Case Access API AAT env
```
[ ] Yes
[x] No
```
> IA Case Access API AAT env

- environments/prod/prod.tfvars
- modules/shutter_page/custom_domains.tf
- modules/shutter_page/enable_https.tf
https://tools.hmcts.net/jira/browse/DTSPO-380
Update to ignore creation of shutter page resources for Fact-Redirect (courttribunalfinder.service.gov.uk) as no longer required and to unblock the apply prod_shutter pipeline stage.
```
[ ] Yes
[ x] No
```
> DTSPO-380 Fix pipeline prod_shutter apply - Ignore Fact-Redirect(CTF)

- environments/stg/backend_lb_config.yaml
N/A
IA Case Access API AAT env fix
```
[ ] Yes
[x] No
```
> IA Case Access API AAT env - second gateway

- azure_pipeline.yaml
alwaysApply true for AAT LBs
```
[ ] Yes
[X] No
```
> alwaysApply true for AAT LBs

- environments/prod/prod.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-1894
removed prod-01 from AGW for planned rebuild to upgrade AKS to 1.19.7
```
[ ] Yes
[x ] No
```
> remove prod-01 from agw to rebuild to upgrade aks version

- environments/prod/prod.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-1894
Added Prod-01 back into AGW.
```
[ ] Yes
[X ] No
```
> added prod-01 back into AGW

- environments/sbox/sbox.tfvars
- environments/variables.tf
https://tools.hmcts.net/jira/browse/DTSPO-2599
Changing Sandbox CDN SKU from Verizon to Microsoft Standard to provide support for keyvault certificate 'latest version'. 
Change will be rolled out to other envs once tested in Sandbox.
```
[ ] Yes
[x ] No
```
> DTSPO-2599 Sandbox change CDN SKU to Microsoft Standard

- environments/prod/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/RBC-7672
Add load balancer for civil service
```
[ ] Yes
[ ] No
```
> feat:Add load balancer for civil service

- environments/demo/backend_lb_config.yaml
- environments/ithc/backend_lb_config.yaml
- environments/prod/backend_lb_config.yaml
- environments/stg/backend_lb_config.yaml
- environments/test/backend_lb_config.yaml
> Add Camunda optimize

- environments/demo/backend_lb_config.yaml
- environments/ithc/backend_lb_config.yaml
- environments/prod/backend_lb_config.yaml
- environments/stg/backend_lb_config.yaml
- environments/test/backend_lb_config.yaml
> override health path for optimize

- azure_pipeline.yaml
- components/cftapps_cluster_lb_backend_cftakstf/.terraform-version
- components/cftapps_cluster_lb_backend_cftakstf/local.tf
- components/cftapps_cluster_lb_backend_cftakstf/main.tf
- components/cftapps_cluster_lb_backend_cftakstf/provider.tf
- components/cftapps_cluster_lb_backend_cftakstf/variables.tf
- components/cftapps_cluster_lb_cftakstf/.terraform-version
- components/cftapps_cluster_lb_cftakstf/local.tf
- components/cftapps_cluster_lb_cftakstf/main.tf
- components/cftapps_cluster_lb_cftakstf/provider.tf
- components/cftapps_cluster_lb_cftakstf/variables.tf
- environments/sbox_cft_akstf/backend_lb_config.yaml
- environments/sbox_cft_akstf/sbox_cft_akstf.tfvars
Test to view plan for cft aks terraform sbox
```
[ ] Yes
[X] No
```
> Test to deploy AppGWs for cft aks terraform sbox

- environments/demo/backend_lb_config.yaml
- environments/ithc/backend_lb_config.yaml
- environments/test/backend_lb_config.yaml
N/A
IA Case Access API lower env
```
[ ] Yes
[x] No
```
> IA Case Access API lower env

- environments/demo/backend_lb_config.yaml
- environments/ithc/backend_lb_config.yaml
- environments/prod/backend_lb_config.yaml
- environments/stg/backend_lb_config.yaml
- environments/test/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/RWA-542
> configure lb for the new service

- environments/demo/backend_lb_config.yaml
- environments/ithc/backend_lb_config.yaml
- environments/stg/backend_lb_config.yaml
- environments/test/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/CMC-1557
```
[ ] Yes
[x] No
```
> Removed civil-damages after transition to civil

- environments/ithc/backend_lb_config.yaml
- environments/test/backend_lb_config.yaml
N/A
Preparing ITHC and Perftest environments
```
[ ] Yes
[x] No
```
> IA Case Payments API lower env

- environments/stg/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/RWA-542
> hit limit so I move it to the one below

- azure_pipeline.yaml
https://tools.hmcts.net/jira/browse/DTSPO-1188
```
[ ] Yes
[x] No
```
> DTSPO-1188: Update template variable reference

- modules/shutter_page/enable_https.tf
see https://github.com/hmcts/cnp-azuredevops-libraries/pull/51
> DTSPO-2599 Use current logged in SP

- environments/ithc/ithc.tfvars
- environments/sbox/sbox.tfvars
- environments/sbox_cft_akstf/sbox_cft_akstf.tfvars
- environments/stg/stg.tfvars
- environments/test/test.tfvars
Exclude monitoring cookies from idam front door rules
> Idam aat cookie exclusion

- environments/test/backend_lb_config.yaml
N/A
IA Home Office integration in perftest
```
[ ] Yes
[x] No
```
> IA Home Office integration in perftest

- environments/prod/prod.tfvars
Cookie exclusions for idam-web-public production.
> Production cookie exclusion changes

- components/dynatrace_activegate_private/nonprod.tf
- modules/dynatrace-private-activegate/cloudconfig.tpl
- modules/dynatrace-private-activegate/variables.tf
- modules/dynatrace-private-activegate/vm.tf
Update reference, =manual not needed
- manual was referenced in documentation but Dynatrace setup in UI says different
```
[ ] Yes
[X] No
```
> Update reference, =manual not needed

- environments/test/test.tfvars
[RIA-4443](https://tools.hmcts.net/jira/browse/RIA-4443)
AIP PerfTest env
```
[ ] Yes
[x] No
```
> RIA-4443 AIP PerfTest env

- modules/dynatrace-activegate/vm.tf
https://tools.hmcts.net/jira/browse/DTSPO-3747
workspaceId protected_settings does not work
```
[ ] Yes
[X] No
```
> workspaceId protected_settings does not work

- environments/prod/backend_lb_config.yaml
Tech Readiness Approval [Immigration+and+Asylum+-+Rel+5.0.0+-+PBA](https://tools.hmcts.net/confluence/display/RSTR/Immigration+and+Asylum+-+Rel+5.0.0+-+PBA)
IA Case Access API release
```
[ ] Yes
[x] No
```
> IA Case Access API release

- environments/ithc/backend_lb_config.yaml
- environments/test/backend_lb_config.yaml
> added case-document-am-api to perftest and ithc

- environments/test/backend_lb_config.yaml
> added CPO to perftest

- environments/test/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/DTSPO-3209
- Will merge when perftest is available, check with Nickin
Update app-gw IP to new cluster for private dns
```
[ ] Yes
[X] No
```
> Update app-gw IP to new cluster for private dns

- components/dynatrace_activegate/prod-private.tf
Add private synthetic active gate for production
```
[ ] Yes
[X] No
```
> Add private synthetic active gate for production

- environments/prod/prod.tfvars
- environments/test/test.tfvars
https://tools.hmcts.net/jira/browse/DTSSE-421
```
[ ] Yes
[ ] No
```
> Update frontend exclusions for cm cookie

- environments/demo/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/RDCC-2790
Create a demo integration environment for RD Professional API
```
[ ] Yes
[X] No
```
> Create demo integration environment

- environments/prod/backend_lb_config.yaml
case-document-am-api on prod. Please find SecOps approval attachment in RDM-11107
https://tools.hmcts.net/jira/browse/RDM-11107
```
[ ] Yes
[ ] No
```
> case-document-am-api on prod

- modules/dynatrace-activegate/variables.tf
https://tools.hmcts.net/jira/browse/DTSPO-3773
Update to read new keyvault secret.
```
[ ] Yes
[ x] No
```
> DTSPO-3773: Deploy Splunk Universal Forwarder on Private Nonprod ActiveGate

- components/cftapps_cluster_lb/local.tf
- components/cftapps_cluster_lb_backend/local.tf
- environments/test/test.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-3210
.tfstate has been updated, PR raised with changes
```
[ ] Yes
[X] No
```
> Update for perftest AKS deployment

- components/dynatrace_activegate/nonprod.tf
https://tools.hmcts.net/jira/browse/DTSPO-3775
Update to enable installation of log analytics agent and splunk universal forwarder install on nonprod activegates.
```
[ ] Yes
[ x] No
```
> DTSPO-3775 Dynatrace ActiveGates NonProd - Splunk UF and Log Analytics Install

- environments/demo/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/RDCC-2790
Add config for RD Profile Sync and UP integration environment.
```
[ ] Yes
[X] No
```
> Add config for RD Profile Sync and UP Int

- components/dynatrace_activegate/prod-private.tf
- components/dynatrace_activegate/prod.tf
https://tools.hmcts.net/jira/browse/DTSPO-3776
**NOTE: PR to be merged during implementation of CHG5005160**
Install Splunk UF and Log Analytics extensions on Prod  ActiveGates
Install Splunk UF extension on Prod Private ActiveGates
```
[ ] Yes
[x ] No
```
> DTSPO-3776 Dynatrace ActiveGates Prod - Splunk UF and Log Analytics Install

- environments/stg/stg.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-4191
removed aat-00 cluster for AKS upgrade / rebuild
```
[ ] Yes
[ X] No
```
> removed aat-00 cluster for rebuild

- environments/ithc/backend_lb_config.yaml
> Update backend_lb_config.yaml (CPO)

- environments/stg/stg.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-4191
re-added aat-00 after aks upgrade
```
[ ] Yes
[ x] No
```
> added aat00 after rebuild

- environments/stg/stg.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-4191
Swap out aat01 for aks rebuild
```
[ ] Yes
[X] No
```
> Swap out aat01 for aks rebuild

- environments/stg/stg.tfvars
Reverts hmcts/azure-platform-terraform#869
- Add aat01 back into AGW
> Add aat01 back into AGW

- environments/prod/backend_lb_config.yaml
case-payment-orders-api on prod. Please find SecOps approval attachment in CPO-58
https://tools.hmcts.net/jira/browse/CPO-58
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[X] No
> CPO-58: case-payment-orders-api on prod

- environments/stg/stg.tfvars
Add AAT00 into AppGW
```
[ ] Yes
[X] No
```
> Add AAT00 into AppGW

- environments/prod/prod.tfvars
[RIA-4262](https://tools.hmcts.net/jira/browse/RIA-4262)
AIP Production env update
```
[ ] Yes
[x] No
```
> RIA-4262 AIP move to the gov.uk subdomain

- environments/stg/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/DTSPO-4308
update private dns AAT to new CFT TF
```
[ ] Yes
[X] No
```
> update private dns AAT to new CFT TF

- modules/shutter_page/cdn_endpoints.tf
> cannot end in special character

- environments/prod/prod.tfvars
N/A
remove AIP configuration for refresh
```
[ ] Yes
[ ] No
```
> remove AIP configuration for refresh

- environments/prod/prod.tfvars
N/A
IA AIP configuration for new url
```
[ ] Yes
[ ] No
```
> IA AIP configuration for new url

- environments/prod/prod.tfvars
N/A
remove AIP configuration
```
[ ] Yes
[ ] No
```
> remove AIP configuration

- environments/prod/prod.tfvars
N/A
IA AIP configuration
```
[ ] Yes
[x] No
```
> IA AIP configuration

- environments/demo/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/RDCC-3178
Add CRD, JRD and LRD integration env
```
[ ] Yes
[X] No
```
> Add CRD, JRD and LRD integration env

- environments/ithc/ithc.tfvars
Removing ITHC-00 from LB due to capacity issues
```
[ ] Yes
[X] No
```
> Removes ithc-00 from lb

- environments/ithc/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/DTSPO-4394
Update app-gw IP to new  ITHC cluster for private dns
```
[ ] Yes
[X] No
```
> Update app-gw IP to new  ITHC cluster for private dns

- environments/demo/backend_lb_config.yaml
- environments/ithc/backend_lb_config.yaml
- environments/stg/backend_lb_config.yaml
- environments/test/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/LAU-94
LAU case-backend LB config for non prod environments.
```
[ ] Yes
[x] No
```
> LAU-94: Updated to add LB config.

- environments/sbox/sbox.tfvars
Add core-api-mgt.sandbox to FD
```
[ ] Yes
[X] No
```
> Add core-api-mgt.sandbox to FD

- environments/sbox/sbox.tfvars
Update to correct backend domain
```
[ ] Yes
[X] No
```
> Update to correct backend domain

- environments/demo/backend_lb_config.yaml
> ac version of data-store-api in demo

- environments/demo/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/DTSPO-4784
Add demo secondary private application gateway
```
[ ] Yes
[X] No
```
> Add demo secondary private application gateway

- environments/demo/demo.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-4784
Add in to get additional public IP
```
[ ] Yes
[X] No
```
> Add in to get additional public IP

- environments/stg/backend_lb_config.yaml
Currently AAT DNS entries are not getting created.
- added FPRL services, `cos` and `dgs`
```
[ ] Yes
[x] No
```
> Add FPRL components

- environments/stg/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/DTSPO-4379
Updated dm-store for staging
```
[ ] Yes
[X] No
```
> Updated dm-store for staging

- environments/prod/prod.tfvars
- environments/stg/stg.tfvars
> Fees register production waf issue fixes

- environments/demo/backend_lb_config.yaml
> Update backend_lb_config.yaml to add ccd test stub

- environments/demo/backend_lb_config.yaml
- environments/stg/backend_lb_config.yaml
- environments/stg/stg.tfvars
Added mapping for adoption-cos-api
> Added mapping for adoption-cos-api

- environments/stg/stg.tfvars
Added adoption-web application mapping
> Added adoption-web application mapping

- environments/sbox/sbox.tfvars
Update from core-api-mgmt to cft-api-mgmt
```
[ ] Yes
[X] No
```
> Update from core-api-mgmt to cft-api-mgmt

- environments/stg/stg.tfvars
Removed adoption from aat front door
> Removed adoption from aat front door

- environments/stg/stg.tfvars
Added adoption-web front door in aat
> Added adoption-web front door in aat

- environments/prod/prod.tfvars
Add the waf exclusions for probate to exclude the rf_ dynatrace calls 
```
[ ] Yes
[X ] No
```
> Add the WAF exclusions for probate

- components/apim/local.tf
- components/apim/main.tf
- environments/sbox/sbox.tfvars
- environments/variables.tf
apim routetable sbox
```
[ ] Yes
[X] No
```
> apim routetable sbox

- environments/stg/stg.tfvars
Had an issue with admin namespace, currently trying to fix - but temp removal of aat-01
```
[ ] Yes
[ x] No
```
> Temp remove aat-01, issue

- environments/demo/backend_lb_config.yaml
- environments/ithc/backend_lb_config.yaml
- environments/ithc/ithc.tfvars
- environments/stg/backend_lb_config.yaml
- environments/stg/stg.tfvars
- environments/test/backend_lb_config.yaml
- environments/test/test.tfvars
https://tools.hmcts.net/jira/browse/LAU-27
Add LAU IdAM Non-Prod config
```
[ ] Yes
[x] No
```
> LAU-27: Add LAU IdAM Non-Prod config

- environments/stg/backend_lb_config.yaml
Backend application is added for Domestic Abuse (da-cos-api)
```
[ ] Yes
[x] No
```
> Added Domestic Abuse (da-cos-api)

- environments/demo/backend_lb_config.yaml
- environments/ithc/backend_lb_config.yaml
- environments/stg/backend_lb_config.yaml
- environments/test/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/RDCC-3636
Add LB config for new RD service Common Data Api
```
[ ] Yes
[X] No
```
> Add LB config on non-prod envs

- environments/demo/backend_lb_config.yaml
Fix to resolve LB config issue
```
[ ] Yes
[X ] No
```
> Fix to resolve LB issue for RD common data api

- components/apim/main.tf
Update apim branch to main
```
[ ] Yes
[X] No
```
> Update apim branch to main

- environments/test/test.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-4829
**Note**: Dependent on completion of custom domain PR - https://github.com/hmcts/azure-public-dns/pull/696
Added Front Door config for Private APIM Perftest
```
[ ] Yes
[x ] No
```
> DTSPO-4829 - Private APIM Perftest Frontdoor Config

- .github/CODEOWNERS
Simplify golden path by not requiring platops to review
> DTSPO-5954 Don't require platops to review sandbox

- components/cftapps_private_dns/main.tf
- environments/sbox/backend_lb_config.yaml
> DTSPO-5506 sbox to sandbox

- environments/test/test.tfvars
Update backend domain name to cftapi perftest
```
[ ] Yes
[X] No
```
> Update backend domain name to cftapi perftest

- environments/ithc/ithc.tfvars
- environments/stg/stg.tfvars
- environments/test/test.tfvars
https://tools.hmcts.net/jira/browse/LAU-216
Add LAU Frontend (Case and IDAM merged)
```
[ ] Yes
[x] No
```
> LAU-216 Add LAU Frontend

- environments/prod/backend_lb_config.yaml
> Update backend_lb_config.yaml for Refunds Production Release

- components/cftapps_cluster_lb_backend/main.tf
Review plan. previous PR renamed aat/test & redeployed app gw
```
[ ] Yes
[X] No
```
> Review plan. previous PR renamed aat/test & redeployed app gw

- environments/sbox/backend_lb_config.yaml
> Create app gateway config for my lab application

- environments/stg/stg.tfvars
> Remove aat-01 for rebuild

- environments/stg/stg.tfvars
Adding aat-001 back after cluster rebuild.
```
[ ] Yes
[x ] No
```
> added aat-01 back

- environments/stg/stg.tfvars
> Remove aat 00 from app gw for rebuild

- environments/stg/stg.tfvars
After rebuild
Reverts hmcts/azure-platform-terraform#951
> Revert "Remove aat 00 from app gw for rebuild"

- environments/demo/backend_lb_config.yaml
- environments/stg/backend_lb_config.yaml
- environments/test/backend_lb_config.yaml
Add Employment Tribunal cos and msg-handler components to non-prod environments
```
[ ] Yes
[x] No
```
> Add et to nonprod environments

- environments/demo/backend_lb_config.yaml
- environments/ithc/backend_lb_config.yaml
- environments/test/backend_lb_config.yaml
> configured demo for ccpay-notifications-service

- environments/sbox/backend_lb_config.yaml
Following golden path tutorial
```
[ ] Yes
[ x ] No
```
> Golden path tutorial - Update backend_lb_config.yaml

- environments/stg/backend_lb_config.yaml
It has been agreed technically that Domestic Abuse and Child arrangement under PrivateLaw project will use the same codebase. Therefore DA specific configuration is no longer required.
```
[ ] Yes
[x] No
```
> Off board Domestic Abuse

- modules/dynatrace-activegate/vm.tf
https://tools.hmcts.net/jira/browse/DTSPO-6420
Fix to unblock pipeline check at dynatrace_ptl stage - https://github.com/hmcts/azure-platform-terraform/pull/962/checks?check_run_id=4843641294
```
[ ] Yes
[x ] No
```
> DTSPO-6420 - Passing value for new upstream module variable

- environments/stg/backend_lb_config.yaml
- environments/stg/stg.tfvars
https://tools.hmcts.net/jira/browse/SIDM-6645
- Added idam-user-dashboard to AAT
```
[ ] Yes
[x] No
```
> SIDM-6645 - Add idam-user-dashboard to AAT

- environments/sbox/backend_lb_config.yaml
> removed myself from labs

- environments/sbox/backend_lb_config.yaml
> Added myself labs for golden path testing

- environments/stg/stg.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-6436
```
[ ] Yes
[ ] No
```
> Switch Divorce FEs to Detect Update stg.tfvars

- environments/stg/stg.tfvars
https://tools.hmcts.net/jira/browse/SIDM-6645
- Enabled detection mode for idam-user-dashboard
```
[ ] Yes
[x] No
```
> SIDM-6645 - Added mode: detection to idam-user-dashboard

- environments/sbox/backend_lb_config.yaml
DTSPO-5507
Added louisehyton-nodejs
```
[ ] Yes
[X] No
```
> added louisehuyton-nodejs

- environments/sbox/sbox.tfvars
DTSPO-5507
added louisehuyton-nodejs to sbox environment
```
[ ] Yes
[X] No
```
> DTSPO-5507 Added louisehuyton-nodejs to sbox environment

- environments/sbox/sbox.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-6241
Removes sbox00 from appgw to enable us to test cluster version upgrade
```
[ ] Yes
[X] No
```
> Remove sbox00 from app-gw

- environments/demo/backend_lb_config.yaml
fix demo The number of BackendAddressPools exceeds the maximum
```
[ ] Yes
[X] No
```
> fix demo The number of BackendAddressPools exceeds the maximum

- environments/stg/backend_lb_config.yaml
Swap idam-user-dashboard to appgw01 - pipeline is failing due to 00 "The number of BackendAddressPools exceeds the maximum allowed value"
```
[ ] Yes
[X] No
```
> Swap idam-user-dashboard to appgw01 - 00 is erroring due to max

- environments/test/backend_lb_config.yaml
Add new backend appgateway for perftest. Current 00 errors: The number of BackendAddressPools exceeds the maximum allowed value
```
[ ] Yes
[X] No
```
> Add new backend appgateway for perftest

- environments/ithc/ithc.tfvars
- environments/stg/stg.tfvars
- environments/test/test.tfvars
https://tools.hmcts.net/jira/browse/CIV-1127
Dependent on https://github.com/hmcts/azure-public-dns/pull/727
> Update citizen-ui config

- environments/stg/stg.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-6436
```
[ ] Yes
[ ] No
```
> Div allow cookies_policy AAT Update stg.tfvars

- environments/stg/stg.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-6436
```
[ ] Yes
[ ] No
```
> Switch divorce FEs back to Prevention mode Update stg.tfvars

- environments/test/test.tfvars
to fix appgw error in pipeline for perftest
```
[ ] Yes
[X] No
```
> to fix appgw error in pipeline for perftest

- environments/sbox/backend_lb_config.yaml
DTSPO-5507
Removing louisehuyton-nodejs. Added to wrong file initially/not needed.
```
[ ] Yes
[X] No
```
> removed louisehuyton-nodejs from labs

- environments/ithc/ithc.tfvars
- environments/prod/prod.tfvars
- environments/stg/stg.tfvars
- environments/test/test.tfvars
> CCD-2331  remove CCD UI

- environments/ithc/ithc.tfvars
- environments/stg/stg.tfvars
- environments/test/test.tfvars
https://tools.hmcts.net/jira/browse/LAU-268
Remove Lau Case and Lau Idam frontend applications. These have been replaced with a single application Lau-Frontend.
```
[ ] Yes
[x] No
```
> LAU-268 Remove lau-case and lau-idam frontend

- environments/ithc/ithc.tfvars
https://tools.hmcts.net/jira/browse/DTSSE-1082
Adding exception to WAF settings for ITHC
```
[ ] Yes
[x] No
```
> DTSSE-1082 - add exception to ithc WAF settings

- environments/sbox/sbox.tfvars
DTSPO-5507
Updated sbox.tfvars with labs-louisehuyton-walkthrough config
```
[ ] Yes
[X] No
```
> DTSPO-5507 - Update sbox.tfvars

- components/apim/main.tf
- environments/sbox/sbox.tfvars
apim to main and sbox developer sku
```
[ ] Yes
[X] No
```
> apim to main and sbox developer sku

- environments/demo/backend_lb_config.yaml
- environments/prod/backend_lb_config.yaml
https://tools.hmcts.net/jira/browse/RDCC-4064
RDCC-4064 Adding Ref data new app rd-commondata-api
```
[ ] Yes
[X] No
```
> RDCC-4064 Adding Ref data new app rd-commondata-api

- environments/demo/backend_lb_config.yaml
CCD-2700
added
```
[ ] Yes
[x] No
```
> add ac-int for mca
