hmcts/azure-platform-terraform

modules/app-gateway-module/main.tf

[AB#698](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/698)
The app gateway is currently overwriting the X-Forwarded-Proto header sent by frontdoor, we need to re-insert it here so that app's that look at the request get the right protocol
https://azure.microsoft.com/en-gb/blog/rewrite-http-headers-with-azure-application-gateway/
```
[ ] Yes
[ ] No
```

Insert X-Forwarded-Proto header = https

---

modules/azure-landing-zone/frontdoor.tf

Currently the health checks are not cached and using /health would mean too many calls to dependant apps.
```
[ ] Yes
[x] No
```

Move to liveness for front door health probes

---

modules/azure-landing-zone/frontdoor.tf

Note that since Front Door have many edge environments globally, health probe requests volume to your backends can be as high as more than one request per second depends on the health probe frequency configured.
https://docs.microsoft.com/en-us/azure/frontdoor/front-door-health-probes
```
[ ] Yes
[x] No
```

Increasing health probe interval for front door

---

environments/ithc.tfvars
environments/prod.tfvars
environments/stg.tfvars
environments/test.tfvars

It seems like this service is accessed on two different urls currently,
1. case-management-web: https://github.com/hmcts/ccd-case-management-web/blob/master/infrastructure/prod.tfvars#L4 (the .platform domain)
2. api-gateway-web: https://github.com/hmcts/ccd-api-gateway/blob/master/infrastructure/main.tf#L20 the .internal domain
```
[ ] Yes
[ ] No
```

Re-add print service to frontdoor

---

environments/stg/stg.tfvars

SIDM-3821
- re-enable aat block mode with previous config
- add query params to whitelist:
- response_type
- client_id
- redirect_uri
- scope
- state
- referer
```
[ ] Yes
[x] No
```

SIDM-3821 - stg.tfvars add idam rules

---

environments/stg/stg.tfvars

SIDM-3821
dtSa cookie is used by DynaTrace and has been flagged on a few requests
```
[ ] Yes
[x] No
```

SIDM-3821 - stg.tfvars: idam: add dtSa cookie

---

environments/prod/prod.tfvars

We would like to disable WAF rule "DefaultRuleSet-1.0-SQLI-942440" on gatewayccdprod and wwwccdprod as there is an ongoing incident caused by the rule blocking hundreds of requests every two minutes.
```
[ ] Yes
[x] No
```

Disable waf rule 942440

---

environments/ithc/ithc.tfvars
environments/prod/prod.tfvars
environments/sbox/sbox.tfvars
environments/stg/stg.tfvars
environments/test/test.tfvars

SIDM-3821
This PR assumes tests in aat are successful, we'll have to wait for the before merging
- Update all `.tvars` to get the idam waf rules updated on all environments.
- Switches off detection mode on aat and aat2
Outsanding questions:
Some environments are still in detection mode, I guess we would like to enable them?
At what point? Should we get it in this PR?
Still in detection mode:
- prod
- perftest
```
[ ] Yes
[x] No
```

SIDM-3821 - idam update waf rules on all envs

---

environments/prod/prod.tfvars

ServiceNow Change Request: CHG5001130
Probate API calls are getting blocked by WAF due to false-positive detection with certain WAF rules.
The request payloads in such calls are coincidentally containing specific sequences of characters (like post codes in addresses) that resemble keywords/commands in some scripting languages, command sets, etc. WAF is then treating them as suspicious and blocking them.
The preferred solution is to design and implement smarter logic in the WAF rules. In the interest of time and subject to IA approval, we can resolve the issue by disabling the following rules identified by DevOps:
932115 - REQUEST-932-APPLICATION-ATTACK-RCE - Remote Command Execution: Windows Command Injection
```
[ ] Yes …
```

disabled rule 932115 for probate

---

environments/stg/backend_lb_config.yaml

Run ia-home-office-mock-api in AAT environment
ia-home-office-integration-api needs a mock server, for testing purpose.
https://tools.hmcts.net/jira/browse/RIA-3074
https://tools.hmcts.net/jira/browse/RIA-3071
ia-home-office-integration-api needs a mock server, for testing purpose. We have generated a server stub in ia-home-office-mock-api, which should be available in AAT
The server in Preview gets stale and is removed after some time.
```
[ ] Yes
[ x] No
```

Add ia-home-office-mock-api to AAT

---

environments/prod/prod.tfvars

#PCQ-520
The WAF mode for the PCQ (Equality and Diversity) is changed to "Prevention" mode in the production environment with a couple of exclusion rules. These rules have been agreed by SecOps. -Agnes Pasca and Andrew Borisevic.
```
[ ] Yes
[X ] No
```

PCQ WAF mode Switched to Prevention mode

---

environments/prod/prod.tfvars

https://tools.hmcts.net/jira/browse/EUI-2383
https://tools.hmcts.net/jira/browse/EUI-2382
Ignore rf query param used by dynatrace when it's doing mysterious things to our app. This is only happening on manage cases.
Also ignore the session cookie now used by manage cases, and ignore the session cookies that will shortly be used by manage org and manage cases.
NOTE: register-org doesn't have it's own session cookie because it's not authenticated
```
[ ] Yes
[x ] No
```

ExUI WAF rule param and cookie exclusions

---

environments/ithc/backend_lb_config.yaml
environments/ldata/backend_lb_config.yaml
environments/sbox/backend_lb_config.yaml
environments/stg/backend_lb_config.yaml
environments/test/backend_lb_config.yaml

https://tools.hmcts.net/jira/browse/SIDM-4430
Disable app gateway session affinity cookie due to stateless sessions being implemented. Non-Prod environments only.
```
[ ] Yes
[x] No
```

chore(idam-nonprod): disable appgw cookie affinity

---

environments/sbox/sbox.tfvars

HMIS-440:
https://tools.hmcts.net/jira/secure/RapidBoard.jspa?rapidView=1442&projectKey=HMIS&view=detail&selectedIssue=HMIS-440
Disable caching on the sbox front door hmi-api routing rule as queries are producing false positives.
```
[ ] Yes
[x] No
```

Disable FD caching for hmi-api

---

environments/test/test.tfvars

This is a valid cookie for pci pal antenna changes and hence we are adding this to the exception list

PAY-3849- PCI Pal antenna cookie exception

---

modules/shutter_page/enable_https.tf
pipeline-templates/terraform.yaml

Part of shutter module currently not working due to requiring az login in local-exec to run az cli (az rest in this instance)
Added AzCLI@2 task to output SPN creds to allow TerraformCLI@0 to use these.
```
[ ] Yes
[X] No
```

Changes for az login with service principal for local-exec

---

environments/test/test.tfvars

On Perftest front door WAF needs to be activated on prevention mode for fees register

PAY-3882- Front door WAF enable to prevention mode

---

environments/prod/prod.tfvars

Exclude "__auth__" cookie from inspection in calls to ccd api gateway.
```
[ ] Yes
[X] No
```

Exclude "__auth__" cookie from inspection

---

environments/stg/backend_lb_config.yaml

Reverts hmcts/azure-platform-terraform#671
`Terraform command 'apply' failed with exit code '1'.:  Error Creating/Updating Application Gateway "aks00-aat-agw" (Resource Group "aks-infra-aat-rg"): network.ApplicationGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="ApplicationGatewayBackendAddressPoolLimitReached" Message="The number of BackendAddressPools exceeds the maximum allowed value. The number of BackendAddressPools is 106 and the maximum allowed is 100." Details=[]`

Revert "Added ccd components from civil damages staging"

---

environments/stg/backend_lb_config.yaml

Reverting the changes again to keep master pipeline green. Will be progressed on https://tools.hmcts.net/jira/browse/DTSPO-1354

Revert civil damages ccd components

---

azure_pipeline.yaml
environments/ithc/backend_lb_config.yaml
environments/ithc/ithc.tfvars

https://tools.hmcts.net/jira/browse/DTSPO-1703
- pipeline step added for ithc private dns.
- private_ip_address added to .yaml for private dns component.
- As part of this, dns_records & dns_zone need to be imported into TF prior to a successful apply (due to records/zone already present in Azure). Have added script for visibility for importing a_records at scale.
```
[ ] Yes
[x ] No
```

Add private dns ithc

---

environments/sbox/sbox.tfvars

https://tools.hmcts.net/jira/browse/DTSPO-2599
Reverting [previous change](https://github.com/hmcts/azure-platform-terraform/pull/801) to Sandbox CDN SKU from Verizon to Microsoft Standard due to inability to use same custom domain across both Azure Front Door and Microsoft CDN (as it is hosted by Front Door).
```
[ ] Yes
[x] No
```

DTSPO-2599 Revert Sandbox change CDN SKU to Microsoft Standard

---

environments/sbox/backend_lb_config.yaml

Update app-gw IP to new cluster for private dns
- App GWs are built using environment/sbox_cft_akstf/sbox.tfvars (not to be considered in this PR)
```
[ ] Yes
[X] No
```

Update app-gw IP to new cluster for private dns

---

components/dynatrace_activegate/prod-private.tf

https://tools.hmcts.net/jira/browse/DTSPO-3910
Add private synthetic active gate for production
PR is required to fix pipeline [issue](https://dev.azure.com/hmcts/CNP/_build/results?buildId=158359&view=logs&j=1f1c515e-fd4c-59cd-570a-8c47feca6bfb&t=4de6fb99-6358-58ed-d8a1-06f5fd0aa74f) after merging issues in [PR-838](https://github.com/hmcts/azure-platform-terraform/pull/838). 
```
[ ] Yes
[x] No
```

DTSPO-3910 Add private synthetic active gate for production

---

environments/ithc/ithc.tfvars
environments/prod/prod.tfvars
environments/sbox/sbox.tfvars
environments/sbox_cft_akstf/sbox_cft_akstf.tfvars
environments/stg/stg.tfvars
environments/test/test.tfvars

* [INC5230074](https://mojcppprod.service-now.com/nav_to.do?uri=%2Fincident.do%3Fsys_id%3Dadbdd6161b513410d5ab8591f54bcb4d%26sysparm_record_target%3Dincident%26sysparm_record_row%3D1%26sysparm_record_rows%3D1%26sysparm_record_list%3Dactive%3Dtrue%5Eassignment_group%3Dec8c03f137ef7f44c21884f643990e24%5Eincident_state!%3D6%5Esys_class_name%3Dincident%5EORDERBYDESCsys_updated_on)
* https://tools.hmcts.net/jira/browse/SIDM-6092
Add the standard OpenID Connect 'nonce' param to WAF exclusion lists for IDAM.
```
[ ] Yes
[x] No
```

SIDM-6092: Add 'nonce' to WAF exclusion list

---

modules/dynatrace-activegate/variables.tf
modules/dynatrace-activegate/vm.tf

https://tools.hmcts.net/jira/browse/DTSPO-3773
Added keyvault secret read for splunk pass4SymmKey and passed value to external module call as required by the [updated external module](https://github.com/hmcts/terraform-module-splunk-universal-forwarder/pull/4).
```
[ ] Yes
[x] No
```

DTSPO-3773: Deploy Splunk Universal Forwarder on Private Nonprod Activegate

---

environments/ithc/ithc.tfvars
environments/stg/stg.tfvars
environments/test/test.tfvars

[SIDM-6433](https://tools.hmcts.net/jira/browse/SIDM-6433)
As the form validation is deemed sufficient this avoid issues with certain character combinations being blocked even though it still is a valid email address
Update: included other non-prod environments

SIDM-6433 Add email to web-public WAF exclusion list

---

environments/stg/stg.tfvars

Follow up to [PR-926](https://github.com/hmcts/azure-platform-terraform/pull/926) Adding aat-01 back into cluster load balancing.
```
[ ] Yes
[x ] No
```

DTSPO-5165 - Add aat-01 back into clusters lb

---

environments/prod/prod.tfvars

https://tools.hmcts.net/jira/browse/SIDM-6667
Whitelist the "rf" parameter as required for Dynatrace monitoring. This will be merged after the change freeze as part of the idam 7.1 release (CHG5006589)
```
[ ] Yes
[X] No
```

SIDM 6667 idam whitelist dynatrace rf parameter

---

environments/stg/backend_lb_config.yaml
environments/stg/stg.tfvars

https://tools.hmcts.net/jira/browse/SIDM-6645
- Re-use idam-web-admin/idam-web-public rules for idam-user-dashboard service.
- Removed detection mode
```
[ ] Yes
[x] No
```

SIDM-6645 - Added WAF rules for idam-user-dashboard

---

environments/ithc/backend_lb_config.yaml
environments/ithc/ithc.tfvars
environments/stg/stg.tfvars
environments/test/backend_lb_config.yaml
environments/test/test.tfvars

https://tools.hmcts.net/jira/browse/SIDM-6645
- Added 'iss' WAF rule to idam-user-dashboard AAT
- Added idam-user-dashboard for ITHC
- Added idam-user-dashboard for PERFTEST
```
[ ] Yes
[x] No
```

SIDM-6645 - Update idam-user-dashboard rules, add to ITHC/PERFTEST

---

modules/dynatrace-activegate/vm.tf

Pipeline is failing, this change has been reverted in module:
https://github.com/hmcts/terraform-module-splunk-universal-forwarder/commit/d2e789a5801af4de76a5678c1896fa0e6bde2140#diff-05b5a57c136b6ff596500bcbfdcff145ef6cddea2a0e86d184d9daa9a65a288e
```
[ ] Yes
[X] No
```

Remove os_type for Dynatrace Activegate splunk-UF

---

environments/test/backend_lb_config.yaml

Update IP as other is in use
- Cannot see this from Portal, HA AppGws didn't look to be using .125
-
```
[ ] Yes
[X] No
```

Update IP as other is in use

---

environments/sbox/sbox.tfvars

https://tools.hmcts.net/jira/browse/DTSPO-5414
Removed cft-sbox-01-aks from AGW load balancing prior to AKS version upgrade
Added cft-sbox-00-aks back to AGW load balancing following AKS version upgrade.
```
[ ] Yes
[x ] No
```

DTSPO-5414 SBOX - Swapped cluster-00/01 in AGW load balancing

---

environments/sbox/sbox.tfvars

https://tools.hmcts.net/jira/browse/DTSPO-5414
Added cft-sbox-01-aks to AGW load balancing following AKS version upgrade
```
[ ] Yes
[x] No
```

DTSPO-5414 - SBOX - Add both clusters back to AGW load balancing

---

environments/ithc/ithc.tfvars

https://tools.hmcts.net/jira/browse/DTSPO-6654
Switch traffic to route through one cluster ithc-01, then commence upgrade of ithc-00.
```
[ ] Yes
[ x] No
```

AKS upgrade switch traffic to be only be routed to ithc-01.

---

environments/stg/stg.tfvars

https://tools.hmcts.net/jira/browse/DTSPO-6658
Remove AAT-00 from AGW load balancer pool prior to rebuild/upgrade
**Note**:  Jenkins currently using [AAT-01.](https://github.com/hmcts/cnp-flux-config/blob/master/apps/jenkins/jenkins/ptl-intsvc/jenkins.yaml#L46) (10.10.159.250)
```
[ ] Yes
[x] No
```

DTPSP-6658 - AAT - Remove cluster-00 from AGW Traffic Routing

---

environments/stg/stg.tfvars

https://tools.hmcts.net/jira/browse/DTSPO-6658
AAT-00 has been rebuilt and adding back into AGW load balancer pool
```
[ ] Yes
[ x] No
```

DTSPO-6658 - AAT - Add aat-00 back into AGW load balancer

---

environments/stg/stg.tfvars

https://tools.hmcts.net/jira/browse/DTSPO-6658
Remove AAT-01 from AGW load balancer pool prior to rebuild/upgrade
Note: Jenkins currently using [AAT-00.](https://github.com/hmcts/cnp-flux-config/blob/master/apps/jenkins/jenkins/ptl-intsvc/jenkins.yaml#L46) (10.10.143.250)
```
[ ] Yes
[X ] No
```

DTPSP-6658 - AAT - Remove cluster-01 from AGW Traffic Routing

---

environments/stg/stg.tfvars

https://tools.hmcts.net/jira/browse/DTSPO-6658
Add AAT-01 back to AGW load balancer pool following rebuild/upgrade completion.
```
[ ] Yes
[x ] No
```

DTPSP-6658 - AAT - Add cluster-01 to AGW Traffic Routing

---

environments/stg/stg.tfvars

https://tools.hmcts.net/jira/browse/DTSPO-7038
Remove AAT-01 from AGW load balancer pool prior to rebuild/upgrade
Note: Jenkins currently using [AAT-00.](https://github.com/hmcts/cnp-flux-config/blob/master/apps/jenkins/jenkins/ptl-intsvc/jenkins.yaml#L46) (10.10.143.250)
```
[ ] Yes
[x] No
```

DTSPO-7038 - AAT - Removed aat-01 from AGW pool for rebuild

---

environments/test/backend_lb_config.yaml
environments/test/test.tfvars

Perfest has an updated 2nd IP from a previous master branch change but this cannot be used [as it is reserved](https://dev.azure.com/hmcts/CNP/_build/results?buildId=215370&view=logs&j=a7933cc5-c4a8-59bf-6fc5-a8f7ae673172&t=e2f986cf-b125-5f7d-afa2-56450cf5b9d2).
Changing to another IP address within the subnet range. 
```
[ ] Yes
[ x] No
```

DTSPO-3187 - Perftest AppGW 2nd Private IP Address Update

---

environments/prod/prod.tfvars

Our requests are getting blocked after uploading files. It looks like false positive.
```
Rule name : DefaultRuleSet-1.0-SQLI-942260
Detects basic SQL authentication bypass attempts 2/3
[ { "matchVariableName": "PostParamValue:applicant1UploadedFiles", "matchVariableValue": "[{\"id\":\"223bd491-7986-4f46-a2e9-5e3723e75ef2\",\"name\":\"Screenshot 2022-03-29 at 16.49.47.png\"}]" } ]
```

Added exclusion for nfdiv civil domain as it looks like false positive

---

environments/ithc/ithc.tfvars
environments/sbox/sbox.tfvars

https://tools.hmcts.net/jira/browse/SIDM-7073
Exclude post_logout_redirect_uri from WAF analysis in ITHC and Sandbox. 
This parameter is used to redirect the user to a page after they have ended their session with the IdP. It is normal for the redirect URI to not match that of the IdP which triggers the FrontDoor WAF to block the request.
```
[ ] Yes
[x] No
```

SIDM-7073: Exclude post_logout_redirect_uri from WAF analysis

---

environments/prod/prod.tfvars

Make end-civil-partnership.service.gov.uk public

Put civil partnership domain into detection to disable IP restriction

---

environments/prod/prod.tfvars

https://tools.hmcts.net/jira/browse/DTSPO-7881
Probate prod service - Users were experiening errors when entering "Union" into the address fields on their application. System treating these inputs ass SQL injections so applying an exlusion
```
[ ] Yes
[x] No
```

DTSPO-7881 exclude probate address fields

---

environments/ithc/ithc.tfvars
environments/prod/prod.tfvars
environments/sbox/sbox.tfvars
environments/stg/stg.tfvars
environments/test/test.tfvars

https://tools.hmcts.net/jira/browse/SIDM-7584
WAF has already been configured to exclude "client_id" from its analyis when used as a query param - it also needs to be excluded when passed as a POST param.
```
[ ] Yes
[x] No
```

SIDM-7584: Exclude client_id from WAF analysis, when sent as a form param

---

environments/prod/prod.tfvars

Add GA and Dynatrace exclusions for PCQ.
The Dynatrace query string arg names used have been pulled from [their documentation](https://www.dynatrace.com/support/help/how-to-use-dynatrace/real-user-monitoring/setup-and-configuration/web-applications/initial-configuration/firewall-constraints-for-rum)
**Does this PR introduce a breaking change?**
```
[ ] Yes
[x] No
```

Add GA and Dynatrace exclusions for PCQ

---

environments/prod/prod.tfvars

[CHG5008426](https://mojcppprod.service-now.com/nav_to.do?uri=%2Fchange_request.do%3Fsys_id%3Dc13a969c1b1cdd906226da88b04bcb4c%26sysparm_view%3D%26sysparm_domain%3Dnull%26sysparm_domain_scope%3Dnull)
WAF has already been configured to exclude "client_id" from its analyis when used as a query param - it also needs to be excluded when passed as a POST param.
```
[ ] Yes
[x] No
```

CHG5008426: Exclude client_id when sent as a form param from WAF analysis

---

components/cftapps_private_dns/provider.tf

https://tools.hmcts.net/jira/browse/DTSPO-8837
Use azurerm v3 provider for private dns
No infrastructure changes related to this component
null_resource.enable_custom_https_cmd["lau"] in prod shutter will be recreated going by latest plan
```
[ ] Yes
[x] No
```

DTSPO-8837 - Azurerm v3 provider private dns

---

azure_pipeline.yaml

https://tools.hmcts.net/jira/browse/DTSPO-9050
Update dependsOn conditions so that sbox must pass before other environments are targeted
Split into different related components. Previously all non-sbox environments had a dependency on sbox_frontendappgateway
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[x] No

DTSPO-9050 - Update dependsOn to sbox non-global

---

environments/ithc/ithc.tfvars

Reverts hmcts/azure-platform-terraform#1215 - Add 00 back to app gateway after cluster rebuild

Revert "Remove 00 from appgw"

---

environments/ithc/ithc.tfvars

Spoke to Harpreet Jhita - causing error currently:
`│ Error: creating Front Door "hmcts-ithc" (Resource Group "lz-ithc-rg"): frontdoor.FrontDoorsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="BadRequest" Message="We couldn't find a DNS record for custom domain et-sya.ithc.platform.hmcts.net that points to Front Door hmcts-ithc.azurefd.net.To map a domain to this Front Door, create a CNAME record with your DNS provider for custom domain that points to Front Door."
`
```
[ ] Yes
[X] No
```

removing et-sya on fd on ithc due to error

---

environments/prod/prod.tfvars

https://tools.hmcts.net/jira/browse/RET-2055
updated the custom domain for the employment claims service to reflect changes in azure-public-dns
```
[ ] Yes
[x] No
```

RET-2055: updated the custom domain for the employment claims service

---

environments/prod/prod.tfvars

https://tools.hmcts.net/jira/browse/RET-2055
Updated custom domain to employment tribunal claim service (not live)
```
[ ] Yes
[x] No
```

RET-2055: Updated custom domain to employment tribunal claim service

---

azure_pipeline-global.yaml

Add pipeline tests to prod global stage
Was previously on hold whilst plum application was enabled on prod clusters
```
[ ] Yes
[x] No
```

DTSPO-10835 - Add pipeline tests to prod global

---

components/global/main.tf
components/global/provider.tf
environments/sbox/sbox.tfvars

- Upgrade azurerm on global (frontdoor) component to 2.99
- On global pipeline, any routing rules with `cache_enabled` set to `false` will have `cache_query_parameter_strip_directive` changed from `StripNone` to `StripAll`. 
- The value of `cache_query_parameter_strip_directive` cannot be `StripNone` when `cache_enabled` is `false` in this updated version of the provider.
- `cache_query_parameter_strip_directive` is not actually used when `cache_enabled` is `false` but this allows us to have one routing rule configuration to cover both scenarios.
- Apply has not yet been ran so this may fail but that is unknown at this point
```
[ ] Yes
[x] No
```

DTSPO-10835 - AzureRM v2.99 - FrontDoor

---

components/frontendappgateway/main.tf
components/frontendappgateway/provider.tf

- Upgrade azurerm provider on frontend appgw component to 3.34
- Branch applied against sbox already. No issues so far - plum still working.
- Health probes and routing rules get shuffled due to changes in the provider. Priority must be explicitly set in routing rules and status codes 200-399 are default for health probes.
- Branch is already in use in SDS
```
[ ] Yes
[x] No
```

DTSPO-10835 - AzureRM 3.34 Frontend AppGW

---

components/backendappgateway/main.tf
components/backendappgateway/provider.tf

Reverts hmcts/azure-platform-terraform#1367
Forgot to apply branch against sbox. Failing due to duplicate priority values. Will revert and test against sbox to rectify.
No changes have been applied to non-sbox backend app gateways

Revert "DTSPO-10835 - AzureRM 3.34 Backend AppGW"

---

components/shutter/provider.tf

Upgrade azurerm provider to 3.34 in shutter component
Applied on sbox already - had to delete deployment to get it passing
```
[ ] Yes
[x] No
```

DTSPO-10835 - AzureRM 3.34 Shutter

---

environments/demo/backend_lb_config.yaml
environments/demo/demo.tfvars

https://tools.hmcts.net/jira/browse/DTSPO-12612
This change:
- Updates backend clusters to include demo00 
- Adds plum-recipes as a backend for demo appgws
Looking to test behaviour for backends in demo in internal URLs and for DNS records existing 
```
[ ] Yes
[ ] No
```

Add second demo cluster, plum backend

---

environments/stg/backend_lb_config.yaml

Dynatrace monitor is failing for http://ccpay-cpo-update-service-aat.service.core-compute-aat.internal/health. As suggested by Dynatrace team, we are adding cpo-update-service to lb_config file.
```
[ ] Yes
[X ] No
```

add cpo-update-service to lb_config

---

environments/prod/prod.tfvars
environments/stg/stg.tfvars

This change:
- Removes a transform that Azure can no longer apply to custom rules of this type, which is causing pipeline stages to fail in this repo.
Transformation is not applied in Azure either currently, hence TF trying to create it on each run 
```
[ ] Yes
[ ] No
```

Remove RUM custom rule transformations

---

environments/demo/demo.tfvars

https://tools.hmcts.net/jira/browse/DTSPO-12612
This change:
- Adds plum as an entry to demo front door
- DNS pointing is handled in https://github.com/hmcts/azure-public-dns/pull/1098
```
[ ] Yes
[ ] No
```

Add plum as front door entry

---

environments/demo/demo.tfvars

Reverts hmcts/azure-platform-terraform#1469 -- frontends are currently stuck in pending state from permanent cname missing during addition (they can't be deleted now and build is failing). 
This change:
- Adds them back using self-managed certs, to unblock frontends
- Will be switched back to front door managed as apps are moved over

Revert "Remove majority to test pipeline timeout"

---

environments/demo/demo.tfvars

This change:
- Adds hmi-apim app to demo front door, backend is to hmi pip
- Dependent on https://github.com/hmcts/azure-public-dns/pull/1112
```
[ ] Yes
[ ] No
```

Add hmi api demo

---

environments/demo/demo.tfvars

This change:
- Adds first batch of demo apps to frontdoor
- dns handled in https://github.com/hmcts/azure-public-dns/pull/1115
- demo flags handled in https://github.com/hmcts/cnp-flux-config/pull/21677
```
[ ] Yes
[ ] No
```

Add first batch of fe apps to demo

---

environments/demo/demo.tfvars

[DTSPO-12614](https://tools.hmcts.net/jira/browse/DTSPO-12614)
This change:
- Migrates a second batch of demo applications over to new setup after successful first batch
- Relies on:
- DNS: https://github.com/hmcts/azure-public-dns/pull/1126
- Flux flags: https://github.com/hmcts/cnp-flux-config/pull/21853
```
[ ] Yes
[ ] No
```

Add second batch of demo apps

---

environments/demo/demo.tfvars

This change:
- Adds remaining IDAM FE apps to demo
- Depends on:
- DNS: https://github.com/hmcts/azure-public-dns/pull/1134
- Flux: https://github.com/hmcts/cnp-flux-config/pull/21931
```
[ ] Yes
[ ] No
```

Add remaining idam apps

---

environments/demo/demo.tfvars

This change:
- Adds remaining FE apps to demo
- Requires:
- DNS: https://github.com/hmcts/azure-public-dns/pull/1140
- Flux: https://github.com/hmcts/cnp-flux-config/pull/21965/files
```
[ ] Yes
[ ] No
```

Add remaining xui fe apps to demo

---

environments/prod/prod.tfvars

https://tools.hmcts.net/jira/browse/ST-1365
Add Special Tribunals Citizen Frontend App and custom domain to Prod Azure Front Door.
DNS zone is already created in this PR: https://github.com/hmcts/azure-public-dns/pull/1213.
Prod Apply check previously failed due to missing key vault certificate in "acmedcdcftappsprod". I don't have access to the vault to check or create a new cert.
I later found out from Louise in PlatOps there is a TLS cert self-service Function App running in Azure here: https://acmedcdcftappsprod.azurewebsites.net/.
This app let me create my TLS cert against my new DNS zone, and after re-running failed PR checks they are now passing.
Please create a new TLS cert as part of this PR review.
```
[ ] Yes …
```

Add Special Tribunals Citizen Frontend App

---

environments/prod/prod.tfvars

https://tools.hmcts.net/jira/browse/SIDM-8732
We're intending to introduce a new OIDC library for idam user dashboard but unfortunately, it necessitates changing the value of the session cookie from `idam-user-dashboard-session` to `idam_user_dashboard_session`. The plan is to allow both variants in the firewall, for now.
```
[ ] Yes
[x] No
```

SIDM-8732: Add new cookie name for idam user dashboard

---

environments/demo/demo.tfvars
environments/ithc/ithc.tfvars
environments/prod/prod.tfvars
environments/sbox/sbox.tfvars
environments/stg/stg.tfvars
environments/test/test.tfvars

[SIDM-8736](https://tools.hmcts.net/jira/browse/SIDM-8736)
User dashboard needs another cookie exclusion from the firewall: `auth_verification`. Also added the updated user dashboard cookie name to other envs besides prod.
```
[ ] Yes
[ x] No
```

SIDM-8736: Add auth_verification cookie to user dashboard

---

environments/ithc/ithc.tfvars

https://tools.hmcts.net/jira/browse/DTSPO-12901
- Remove ithc01 internal LB to allow for AKS patch 1.26
```
[ ] Yes
[x] No
```

ITHC: Remove ithc01 internal LB to allow for AKS patch 1.26

---

environments/ithc/ithc.tfvars

https://tools.hmcts.net/jira/browse/DTSPO-12901
* Remove ithc00 for AKS patching to GA version 1.26
```
[ ] Yes
[x] No
```

ITHC: Remove ithc00 for AKS patching to GA version 1.26

---

environments/ithc/ithc.tfvars

Reverts hmcts/azure-platform-terraform#1639

Revert "ITHC: Remove ithc00 for AKS patching to GA version 1.26"

---

environments/demo/demo.tfvars

Reverts hmcts/azure-platform-terraform#1647 - accidentally the incorrect IP addresses - should be cluster IPs being altered

Revert "Remove Demo01 - AKS upgrades"

---

environments/demo/demo.tfvars

Reverts hmcts/azure-platform-terraform#1649 -- add 01 back into application gateway post-upgrade
Upgrade added as code https://github.com/hmcts/aks-cft-deploy/pull/495#event-9945959019

Revert "Remove demo01 cluster for aks upgrades"

---

environments/stg/stg.tfvars

https://tools.hmcts.net/jira/browse/LAU-707
Adding exclusions to Azure FD to unblock static assets. This will bring AAT in alignment with Production exclusions.
```
[ ] Yes
[x] No
```

LAU-707: Add exclusions to align LAU AAT with Prod and unblock static assets

---

components/apim-appgw/main.tf

SDT-115 (https://tools.hmcts.net/jira/browse/SDT-115)
Changed terraform-module-apim-application-gateway source branch name used in Application Gateway module back to main.  This follows changes made to terraform-module-apim-application-gateway to allow different certificates to be used and the ability to specify rewrite rules in the configuration file.

Update App Gateway module source branch name

---

environments/stg/stg.tfvars

EM team report that chunking is not working for at least some users in production. Works in AAT. To investigate this we want to disable FD caching to see if this is part of the issue
EM-5292

Explicitly disable caching on AAT to match production

---

components/global/main.tf
environments/demo/demo.tfvars
environments/dev/dev.tfvars
environments/ithc/ithc.tfvars
environments/prod/prod.tfvars
environments/sbox/sbox.tfvars
environments/stg/stg.tfvars
environments/test/test.tfvars
environments/variables.tf

We do not need this upgrade_frontdoor field any more as all the frontdoors are now migrated to premium, we have to change the brach to master as well after merging the DTSPO-13992-test-new-version-of-frontdoor to master on the module.

post CFT  frontdoor migration clean up

---

environments/prod/prod.tfvars

* WAF exclusion for tt-pet QueryStringArgNames contains PostParamName instead of equals

tt-pet QueryStringArgNames contains PostParamName

---

environments/prod/prod.tfvars

Reverts hmcts/azure-platform-terraform#1959
adding app gw back for cft prod 01 after upgrade to version 1.28.
https://tools.hmcts.net/jira/browse/DTSPO-15844

Revert "removing app gw for prod 01"

---

components/apim-appgw/main.tf
environments/prod/apim_appgw_config.yaml
environments/sbox/apim_appgw_config.yaml
environments/test/apim_appgw_config.yaml

Switched application gateway component to use backend-http-settings-host-name branch of terraform-module-apim-application-gateway.  The branch will be merged once backend http setting host name changes have been confirmed.
Updated sandbox, perftest and production application gateway configuration files to use new properties added in terraform-module-apim-application-gateway backend-http-settings-host-name branch.  Production application gateway is not currently used by any applications, so changes to configuration will not affect anything.
Removed cft-api-mgmt-appgw entry from perftest application gateway configuration as it is not used.

Configure App Gateway to set backend host name

---

environments/test/apim_appgw_config.yaml

Added missing word to value of backend_host_name_override properties in perftest application gateway config file.

Corrected backend host name in perftest App Gateway config

---

environments/prod/apim_appgw_config.yaml

Temporarily added a test listener to production application gateway configuration.  This will be used to check connectivity to civil-sdt-commissioning service via a testdt.justice.gov.uk CNAME record.  Listener will be removed once check has been completed.

Add test listener to App Gateway config

---

components/shutter_static_webapp/init.tf

https://tools.hmcts.net/jira/browse/DTSPO-17001
to fix this problem,
```
Error: making Read request for app settings on Static Site: (Name "ia-aip" / Resource Group "cft-platform-shutter-webapp-prod-rg"): web.StaticSitesClient#ListStaticSiteAppSettings: Failure sending request: StatusCode=429 -- Original Error: context deadline exceeded
│ 
│   with module.static_webapp.azurerm_static_site.swebapp["ia-aip"],
│   on .terraform/modules/static_webapp/static-webapp.tf line 2, in resource "azurerm_static_site" "swebapp":
│    2: resource "azurerm_static_site" "swebapp" {
```

DTSPO-17001 - hard coding Azurerm provider version

---

environments/dev/dev.tfvars
environments/prod/prod.tfvars
environments/stg/stg.tfvars

Platops have instructed each team to move to mode-Prevention for their web access firewall.
This change moves NFD to Prevention.

Change mode on WAF on nfdiv service from Detection to Prevention

---

environments/test/test.tfvars

https://tools.hmcts.net/jira/browse/CUIRA-282
Enable waf prevention mode on test env. All other envs already have prevention mode

CUIRA-282 enable prevention mode in test env

---

environments/prod/prod.tfvars

There is no Jira link - An update required to bypass Firewall check for et_sya_cookie_preferences (https://moj.enterprise.slack.com/archives/C06R9LR05JQ/p1711617241062239)
et-sya-cookie-preferences added as global exclusion to the following custom domain, dns zone pairs:
1. employmenttribunals.service.gov.uk, employmenttribunals-service-gov-uk
2. admin.employmenttribunals.service.gov.uk, employmenttribunals-service-gov-uk
3. tribunal-response.employmenttribunals.service.gov.uk, employmenttribunals-service-gov-uk
4. claim-employment-tribunals-service-gov-uk, claim-employment-tribunals-service-gov-uk

Added et_sya_cookie_preferences as a global exclusion

---

environments/stg/stg.tfvars

Remove 01 cluster from appgateway for upgrade
The pull request removed one IP address from the `cft_apps_cluster_ips` list in the `stg.tfvars` file and updated the `publisher_email` to \"DTSPlatformOps@HMCTS.NET\". 🔄🔑

DTSPO-16594 - remove 01 cluster to upgrade

---

environments/test/test.tfvars

REmoved 00 cluster for upgrade for perftest environment
- Removed an IP address from the `cft_apps_cluster_ips` list in `test.tfvars`
- Updated the `cft_apps_ag_ip_address` and `frontend_agw_private_ip_address` values in `test.tfvars`
- Changed the value of `hub` to \"nonprod\" and `key_vault_subscription` to \"8a07fdcd-6abd-48b3-ad88-ff737a4b9e3c\" in `test.tfvars`

DTSPO-16594 - perftest 00 cluster remove from appgateway

---

environments/test/test.tfvars

Remove 01 cluster from application gateway
The pull request modifies the `test.tfvars` file in the `test` environment.
- Removed an IP address from `cft_apps_cluster_ips`.
- Updates the values of `cft_apps_ag_ip_address` and `frontend_agw_private_ip_address`.
- Updates the value of `hub`.
- Updates the value of `key_vault_subscription`.
- A single IP address remained in `cft_apps_cluster_ips`.

DTSPO-16594 - perftest 01 cluster remove from appgateway

---

azure_pipeline.yaml
environments/prod/prod.tfvars

https://tools.hmcts.net/jira/browse/DTSPO-16595
Remove prod 00 cluster from application gateway
- Removed one IP address from the cft_apps_cluster_ips array in prod.tfvars
- Updated the frontend_agw_private_ip_address in prod.tfvars from \"10.90.96.15\" to \"10.90.96.12\"

DTSPO-16595 - remove prod 00 cluster from appgateway

---

environments/prod/prod.tfvars

https://tools.hmcts.net/jira/browse/DTSPO-16595
Remove 01 cluster form application gateway
The changes in this pull request are:
- Removed an IP address from the cft_apps_cluster_ips list in prod.tfvars
- Updated the frontend_agw_private_ip_address to \"10.90.96.12\" in prod.tfvars

DTSPO-16595 - remove prod 01 cluster from appgateway

---

environments/ithc/ithc.tfvars

https://tools.hmcts.net/jira/browse/DTSSTCI-260
Revert changes after testing completed for subdomain in ithc env
Original PR: https://github.com/hmcts/azure-platform-terraform/pull/2105/files
The `ithc.tfvars` file in the `environments/ithc` directory has been modified. Specifically, the `custom_domain` for the `sptribs-dss-update-case-web` frontend has been updated from \"update.sptribs-frontend.ithc.platform.hmcts.net\" to \"sptribs-dss-update-case-web.ithc.platform.hmcts.net\".

DTSSTCI-260

---

environments/ithc/ithc.tfvars

https://tools.hmcts.net/jira/browse/DTSPO-17759
changed migration trigger to false to revert apim instance back to original resources
- Changed file: `ithc.tfvars`
- Set `trigger_migration` to `false` instead of `true`
- Updated `trigger_migration_temp_pip` to `true`
- Updated `temp_subnet_address_prefixes` to \"10.11.226.0/24\"

migrate apim back to original resources

---

azure_pipeline.yaml

increase pipeline timeout to 90 min to avoid apim upgrade timeout
md
azure_pipeline.yaml
- Increased the value of the timeoutInMinutes variable from 60 to 90.
```

increase timeout for apim upgrades

---

environments/demo/demo.tfvars
environments/prod/prod.tfvars
environments/stg/stg.tfvars
environments/test/test.tfvars

https://tools.hmcts.net/jira/browse/CUIRA-370
added 2 new cookies. one for cookie preference and the other to allow google analytics
- Added new configurations for matching request cookie names and operators.
- Added selectors for \"cui-ra-cookie-preferences\" and \"_ga_\".
- Added new configurations for matching request cookie names and operators.
- Added selectors for \"cui-ra-cookie-preferences\" and \"_ga_\".
- Added new configurations for matching request cookie names and operators.
- Added selectors for \"cui-ra-cookie-preferences\" and \"_ga_\".
- Added new configurations for matching request cookie names and operators.
- Added selectors for \"cui-ra-cookie-preferences\" and \"_ga_\".

added cookie preferences and ga

---

azure_pipeline.yaml

updated pipeline timeout from 90 -> 60 minutes
md
azure_pipeline.yaml
- Changed the value of timeoutInMinutes variable from 90 to 60
```

revert pipeline timeout back to 60 minutes

---

environments/stg/stg.tfvars

set migration to false
- The `stg.tfvars` file in the `environments/stg` directory has been updated.
- The `trigger_migration_temp_pip` variable has been changed from `true` to `false` within the `migration_variables` block.

clean up cft stg apim

---

environments/test/apim_appgw_config.yaml

revert apim appgw perftest to default
- File **apim_appgw_config.yaml**:
- Removed several lines related to adding SSL profile, verifying client certificate issuer DN, root CA certificate, rewrite rules, and conditions.
- Updated **ssl_enabled** to true.

revert apim appgw perftest to default

---

environments/demo/demo.tfvars

Unblock pcq returnUrl rule for demo.
The rule is not applied to demo only
- The file demo.tfvars``` was modified to include a new global exclusion for QueryStringArgNames matching \"returnUrl\".
- The change adds a new item to the global_exclusions list within the file.

Unblock pcq returnUrl rule for demo.

---

environments/demo/demo.tfvars

The admin for pet-et is not accessible.  This because the cookie isn't allowed.
This changes fixes it
- **demo.tfvars**
- Added global exclusion for \"_super_session\" in the frontends configuration.

Added cookie exclusion to demo admin for et

---

components/apim-appgw/main.tf

- correct apim-appgw module ref to master
- Updated `main.tf`: Changed the source of the module \"app-gw\" from \"allow-multiple-certs-on-listener\" branch to \"main\".

correct apim-appgw module ref to main

---

environments/demo/demo.tfvars
environments/ithc/ithc.tfvars
environments/prod/prod.tfvars
environments/sbox/sbox.tfvars
environments/stg/stg.tfvars
environments/test/test.tfvars

https://tools.hmcts.net/jira/browse/SIDM-9335
Exclude state and nonce as post params
- Updated the `demo.tfvars`, `ithc.tfvars`, `prod.tfvars`, `sbox.tfvars`, `stg.tfvars`, and `test.tfvars` files with the addition of matching rules for `RequestBodyPostArgNames` selector with different states and nonces. 🔄

SIDM-9335 exclude state and nonce

---

components/apim-appgw/root_certs.tf
environments/test/apim_appgw_config.yaml

- add exela root ca to cft-mtls listener for reform scan
- remove iron mountain & duplicate reform-scan-ca from mapping of root ca certs
- Updated the `root_certs.tf` file:
- Removed `dts_bsp_team_ca` and `iron_mountain_ca`.
- Updated the `apim_appgw_config.yaml` file in the test environment:
- Added `exela_uat_ca` to the `rootca_certificates` section.

add exela root ca cert to cft-mtls listener

---

components/apim-appgw/root_certs.tf
environments/test/apim_appgw_config.yaml

- exela cert still invalid and missing CA: True
- Updated `root_certs.tf`: Removed `exela_uat_ca` from the `test` section in the `locals` block.
- Updated `apim_appgw_config.yaml`: Removed `exela_uat_ca` from the `rootca_certificates` list.

perftest: remove exela root ca cert to cft-mtls listener

---

environments/demo/demo.tfvars

https://tools.hmcts.net/jira/browse/DTSCCI-525
Enable Waf changing mode from detection to prevention in Demo for Cmc & Citizen-ui
- Changed mode of \"civil-citizen-ui\" to \"Prevention\" from \"Detection\"
- Added global exclusions for \"cmc\" including match_variable, operator, and selector

Change from detection to prevention mode.

---

environments/prod/prod.tfvars

- The `prod.tfvars` file in the `environments/prod` directory has had changes made to the `frontends` section, specifically in the `disabled_rules` block.
- Two rules have been removed from the `LFI` section: \"930130\" and \"930110\".

DIAC-488 - remove LFI exclusion codes

---

environments/test/test.tfvars

Block CFT APIM requests if reform-scan is in the path, these requests should only go through mtls appgw setup.
- Modified `test.tfvars`: Added a custom rule to block requests containing \"/reform-scan\" for the \"adoption-web\" frontend.

Block requests for CFT APIM if URI contains

---

environments/demo/demo.tfvars
environments/ithc/ithc.tfvars
environments/prod/prod.tfvars
environments/stg/stg.tfvars

Already applied and tested in perftest. Applying to rest of envs. Blocking requests if reform-scan endpoint as all requests should come through the appgw mtls url. 
- Added custom rule to block requests containing \"/reform-scan\" to the firewall configuration.
- Added custom rule to block requests containing \"/reform-scan\" to the firewall configuration.
- Added custom rule to block requests containing \"/reform-scan\" to the firewall configuration.
- Added custom rule to block requests containing \"/reform-scan\" to the firewall configuration.

Block request if reform-scan for CFT APIM

---

environments/demo/demo.tfvars
environments/ithc/ithc.tfvars
environments/stg/stg.tfvars
environments/test/test.tfvars

added missing bits into fact admin
- Modified environments/demo/demo.tfvars, environments/ithc/ithc.tfvars, environments/stg/stg.tfvars, environments/test/test.tfvars:
- Updated multiple instances of the 'selector' attribute values from ending with \"_\" to starting with the same text, and changed the 'operator' from 'Equals' to 'StartsWith' for some 'selector' values. Added new objects for 'additionalLinks' and 'secondaryAddress' with 'StartsWith' operator.

FACT-1846 - added some missing exclusion rules and rule alterations for non prod

---

components/apim-appgw/root_certs.tf
environments/demo/apim_appgw_config.yaml
environments/prod/apim_appgw_config.yaml

https://tools.hmcts.net/jira/browse/DTSPO-18581
Adding PCIPal cert to the prod APIM appGW
- `components/apim-appgw/root_certs.tf` added a new local variable `pcipal_ca` for PCIPal CA.
- `environments/prod/apim_appgw_config.yaml` added `rootca_certificate_name: pcipal_ca` under the gateways section.

Adding PCIPal cert to prod app gateway

---

environments/prod/prod.tfvars

Reverts hmcts/azure-platform-terraform#2224
Reverting PR to update rules for Prod as It is creating issues for Users 
- Updated the disabled_rules for SQL injection and remote code execution for two frontends.
- Removed several global exclusions and modified one to have a different operator for a specific match_variable.

Revert "DTSCCI-525 Update Exclusion rules to match other environments"

---

environments/prod/prod.tfvars

applying changes for production WAF exclusion rules.
These rules are the same as non prod and have been tested in non prod.
**WILL NEED TO BE MERGED VIA RELEASE MANAGEMENT - DO NOT MERGE**
CHG5017661
- Changed the \"mode\" of the \"fact-admin\" frontend from \"Detection\" to \"Prevention\".
- Added several global exclusions for various match variables, operators, and selectors under \"fact-admin\" frontend.

FACT-1846 Detection to Prevention for FaCT Admin PROD [CHG5017661]

---

environments/demo/demo.tfvars
environments/ithc/ithc.tfvars
environments/prod/prod.tfvars
environments/sbox/sbox.tfvars
environments/stg/stg.tfvars
environments/test/test.tfvars

N/A
We have introduced new cookies in HMCTS-Access that are used to story state for user journeys:
* "Idam.Reset"
* "Idam.Registration"
The cookie values are base64 encoded and occasionally get flagged by WAF as malicious. This PR excludes the new cookies from the WAF analysis.
N/A
- Added new match_variable, operator, and selector entries for RequestCookieNames.
- Added new match_variable, operator, and selector entries for RequestCookieNames.
- Added new match_variable, operator, and selector entries for RequestCookieNames.
- Added new match_variable, operator, and selector entries for RequestCookieNames.
- Added new match_variable, operator, and selector entries for RequestCookieNames.
- Added new match_variable, operator, and selector entries for RequestCookieNames.

IDAM: Exclude new cookies from WAF analysis

---

environments/demo/demo.tfvars

re-add demo 01 ip after migration 
- The `demo.tfvars` file in the `demo` environment now includes an additional IP address in the `cft_apps_cluster_ips` list, with the new value being \"10.50.95.221\". Additionally, the `certificate_name_check` field has been set to `false` and `autoShutdown` has been set to `true`.

DTSPO-18669 - Upgrade CFT NonProd AKS Clusters to Kubernetes 1.30  - re-add Demo 01 IP

---

environments/stg/stg.tfvars

Remove cft-aat-00-aks IP for upgrade to 1.30 from app gw temporary 
- Removed \"10.10.143.250\" from the list of `cft_apps_cluster_ips`.

DTSPO-18669 : Upgrade CFT NonProd AKS Clusters to Kubernetes 1.30 remove aat 00 IP for aks upgrade

---

environments/stg/stg.tfvars

Re-add AAT 00 IP after upgrade cluster 
- Changed the `cft_apps_cluster_ips` from `[\"10.10.159.250\"]` to `[\"10.10.143.250\", \"10.10.159.250\"]`.

DTSPO-18669 Upgrade CFT NonProd AKS Clusters to Kubernetes 1.30 - re add aat 00 IP

---

environments/ithc/ithc.tfvars
environments/test/test.tfvars

See [RET-5398](https://tools.hmcts.net/jira/browse/RET-5398)
Deploy et-syr to ITHC and Perf ahead of release testing
- `environments/ithc/ithc.tfvars` 🔄
- Added a new configuration block for \"et-syr\" with specific settings for \"Detection\" mode and global exclusions.
- `environments/test/test.tfvars` 🔄
- Added a new configuration block for \"et-syr\" with specific settings for \"Detection\" mode and global exclusions.

ET-SYR ITHC and perf deployment

---

environments/test/test.tfvars

re-add cft-perftest-00-aks IP after upgrade aks
- Updated `cft_apps_cluster_ips` from `[\"10.48.95.250\"]` to `[\"10.48.79.250\", \"10.48.95.250\"]` 🔄.

Upgrade CFT NonProd AKS Clusters to Kubernetes 1.30 - re-add cft-perftest-00-aks IP

---

environments/prod/prod.tfvars

Reverts hmcts/azure-platform-terraform#2279
- Modified `cft_apps_cluster_ips` from `[\"10.90.95.250\"]` to `[\"10.90.79.250\", \"10.90.95.250\"]` 🔄.

Upgrade CFT Prod AKS Clusters to Kubernetes 1.30 - re-add cft-prod-00-aks IP 

---

environments/prod/prod.tfvars

Reverts hmcts/azure-platform-terraform#2280
- Removed \"10.90.79.250\" from the `cft_apps_cluster_ips` list and added \"10.90.95.250\".
- Updated the `frontend_agw_private_ip_address` to \"10.90.96.12\".
- Updated the `frontend_agw_min_capacity` to 10.
- Updated the `frontend_agw_max_capacity` to 15.

Revert Upgrade CFT Prod AKS Clusters to Kubernetes 1.30 - remove cft-prod-00-aks IP

---

environments/demo/demo.tfvars
environments/ithc/ithc.tfvars
environments/sbox/sbox.tfvars
environments/stg/stg.tfvars
environments/test/test.tfvars

N/A
Exclude cookies_policy cookie in idam-hmcts-access
N/A
- Added a new configuration for `RequestCookieNames` matching the operator \"Equals\" and selector \"cookies_policy\" to the frontends array.
- Added a new configuration for `RequestCookieNames` matching the operator \"Equals\" and selector \"cookies_policy\" to the frontends array.
- Added a new configuration for `RequestCookieNames` matching the operator \"Equals\" and selector \"cookies_policy\" to the frontends array.
- Added a new configuration for `RequestCookieNames` matching the operator \"Equals\" and selector \"cookies_policy\" to the frontends array.
- Added a new configuration for `RequestCookieNames` matching the operator \"Equals\" and selector \"cookies_policy\" to the frontends array.

Exclude cookies_policy cookie in idam-hmcts-access

---

azure_pipeline.yaml

DTSPO-19088
removing cluster selector from precheck as this is not used anymore and this is causing pipeline failures.
Tested in other repo's
- Removed the `cluster` parameter and its value `'00'` from the `stages` section.
- Updated the `environment` value from `'sbox'` to `$environment` in the `stages` section.

DTSPO-19088 - removing cluster selector from precheck

---

environments/demo/demo.tfvars
environments/ithc/ithc.tfvars
environments/sbox/sbox.tfvars
environments/stg/stg.tfvars
environments/test/test.tfvars

https://tools.hmcts.net/jira/browse/SIDM-9508
Exclude Idam.Request cookie in idam-hmcts-access
N/A
- The changes in the pull request involve adding a new block of configuration to the \"demo.tfvars\", \"ithc.tfvars\", \"sbox.tfvars\", \"stg.tfvars\", and \"test.tfvars\" files. 
- The added config block sets \"match_variable\" to \"RequestCookieNames\", \"operator\" to \"Equals\", and \"selector\" to \"Idam.Request\".

Exclude Idam.Request cookie in idam-hmcts-access

---

environments/ithc/ithc.tfvars

[HDPI-48](https://tools.hmcts.net/jira/browse/HDPI-48)
Adding front door configuration for PCS frontend in ITHC
None - configuration change.
- Added a new entry for \"pcs-frontend\" with mode \"Prevention\", custom domain \"pcs.ithc.platform.hmcts.net\", DNS zone name \"ithc.platform.hmcts.net\", backend domain \"firewall-nonprodi-palo-cftithc.uksouth.cloudapp.azure.com\", and an empty global exclusions array.

HDPI-48 - Adding front door configuration for PCS frontend in ITHC

---

environments/demo/demo.tfvars

- Added a new match_variable configuration for RequestBodyPostArgNames with operator \"Equals\" and selector \"CookieValue:dtSa\".

Allow dtSa cookie to accept value on TT Demo

---

components/pubsubappgateway/main.tf

[DTSPO-22820](https://tools.hmcts.net/jira/browse/DTSPO-22820)
adding a condition so the pubsub app gateway uses the correct subnet
- Added support for a new feature `pubsub_subnet` to enable the usage of a subnet for Pub/Sub.

DTSPO-22820 adding condition for pubsub subnet

---

azure_pipeline.yaml
components/pubsubappgateway/main.tf
environments/ithc/ithc.tfvars
environments/prod/prod.tfvars
environments/sbox/sbox.tfvars
environments/stg/stg.tfvars
environments/test/test.tfvars

[DTSPO-22820](https://tools.hmcts.net/jira/browse/DTSPO-22820)
Creating pubsub app gateways for other envs 
- Added deployment configurations for different environments with pubsubappgateway and backendappgateway components.
- Updated the pipeline_tests parameter for each deployment, setting it to true for all environments except prod where it is set to false.
- Updated the count condition to include the pubsubappgateway component only for environments other than \"sbox\".
- Changed the names and labels for app_gateway_name, pip_name, and waf_policy_name based on the environment.
- Added pubsub_endpoint and pubsub_frontends configurations for the \"ithc\" environment.
- Added pubsub_endpoint and pubsub_frontends configurations for the \"prod\" environment.
- Added pubsub_endpoint and …

DTSPO-22820 Adding pubsub settings to other envs

---

environments/demo/demo.tfvars
environments/ithc/ithc.tfvars
environments/prod/prod.tfvars
environments/test/test.tfvars

https://tools.hmcts.net/jira/browse/CUIRA-384
Disable _csrf check
Creating PR to perftest to check, and if it works raise on all other envs
- The changes include adding a new configuration to the terraform variables file for demo, ithc, prod, and test environments. 
- In each file, a new configuration block is added for frontends with \"match_variable\" set to \"RequestBodyPostArgNames\", \"operator\" set to \"Equals\", and \"selector\" set to \"_csrf\".

CUI disable csrf check on perf test

---

environments/stg/stg.tfvars

https://tools.hmcts.net/jira/browse/CUIRA-384
Exclude _csrf value check in aat
- Added a new match condition for the \"RequestBodyPostArgNames\" with operator \"Equals\" and selector \"_csrf\" within the \"frontends\" block.

Exclude csrf from aat env

---

environments/ithc/ithc.tfvars

Reverts hmcts/azure-platform-terraform#2391
- Changed the `operator` value from \"Equal\" to \"Equal\" with `negation_condition` set to false for the `match_conditions` in the frontends.
- Added security rules with IDs \"942260\" and \"942340\" to the SQLI category under `disabled_rules`.

Revert "Platops/dtspo 23355 private law waf2.1ruleset"

---

azure_pipeline.yaml

[DTSPO-23915](https://tools.hmcts.net/jira/browse/DTSPO-23915)
removing ithc pubsub from pipeline so that we can test changes without the pipeline overriding them
- **azure_pipeline.yaml**
- Removed the `ithc_pubsubappgateway` deployment block and its associated parameters and dependencies.
- Removed the `ithc_backendappgateway` deployment block's `service_connection`, `storage_account_rg`, and `storage_account_name` parameters.

DTSPO-23915 removing ithc pubsub from pipeline

---

environments/demo/demo.tfvars
environments/prod/prod.tfvars
environments/stg/stg.tfvars

https://tools.hmcts.net/jira/browse/RST-7155
- Added rules for `RequestBodyPostArgNames` with `selector` values for `online_search[reference]` and `application[deceased_name]` to the `frontends` list at line 3740.
- Added rules for `RequestCookieNames` with `selector` value of `_hwf-publicapp_session` and `RequestBodyPostArgNames` with `selector` value of `application[deceased_name]` to the `frontends` list at line 4005.
- Added rules for `RequestBodyPostArgNames` with `selector` values for `online_search[reference]` and `application[deceased_name]` to the `frontends` list at line 4004.

Adding WAF excepotion for deceased name

---

environments/demo/demo.tfvars
environments/prod/prod.tfvars
environments/stg/stg.tfvars
environments/test/test.tfvars

Reverts hmcts/azure-platform-terraform#2413
- environments/demo/demo.tfvars```
- Changed the \"mode\" from \"Prevention\" to \"Detection\" for the \"privatelaw\" frontend.
- ```environments/prod/prod.tfvars```
- Changed the \"mode\" from \"Prevention\" to \"Detection\" for the \"private-law\" frontend.
- ```environments/stg/stg.tfvars```
- Changed the \"mode\" from \"Prevention\" to \"Detection\" for the \"privatelaw\" frontend.
- ```environments/test/test.tfvars```
- Changed the \"mode\" from \"Prevention\" to \"Detection\" for the \"privatelaw\" frontend.

Revert "FPET-1263 / DTSPO-23355 WAF changes to prevention mode && ITHC issue fix VUL-6219 "

---

environments/sbox/sbox.tfvars

removing golden path entries
- The file `sbox.tfvars` in the `environments/sbox` directory has had significant changes. Specifically, it looks like a large block of configuration related to different products, their custom domains, backend domains, and certificates has been removed. This may indicate a cleanup or refactoring of the configuration.

removing golden path entries

---

environments/sbox/sbox.tfvars

See [DTSPO-25106](https://tools.hmcts.net/jira/browse/DTSPO-25106)
Golden path nodejs app for Dan Alves
Also had to update plum frontend due to this [commit](https://github.com/hmcts/azure-public-dns/commit/404bd1b850c44c5a03c39905537414cb6c55e657)
- In `environments/sbox/sbox.tfvars`, a new configuration block for the `labs-gunnertwin-nodejs` product has been added, with custom domain, DNS zone name, backend domain, and other settings.

Update sbox.tfvars with Dan nodejs frontend

---

environments/sbox/sbox.tfvars

Reverts hmcts/azure-platform-terraform#2450
Adding cft-sbox-01-aks back into load balancer
- Added a new IP address \"10.2.11.250\" to the `cft_apps_cluster_ips` array.

Revert "DTSPO-24310: Temporarily removing cft-sbox-01-aks from load balancer"

---

environments/demo/backend_lb_config.yaml

See [CCD-6206](https://tools.hmcts.net/jira/browse/CCD-6206)
Temporarily increase definition store request timeout , to allow importing Civil definition files.
- Added a `request_timeout` of 180 for the `definition-store-api` component.
- Changed the structure to include the `request_timeout` for the `definition-store-api` component.

Temporarily increase definition store request timeout

---

environments/sbox/sbox.tfvars

Remove Dans goldenlab frontdoor config
- Removed configuration related to the `labs-gunnertwin-nodejs` product and backend.
- Updated the `appgw_cookie_based_affinity` to \"Enabled\".
- Set `cache_enabled` to \"false\".
- Disabled `certificate_name_check_enabled`.
- Removed `custom_domain`, `dns_zone_name`, `shutter_app`, `backend_domain`, `certificate_name`, and `disabled_rules`.

chore: remove dan golden labs

---

environments/sbox/sbox.tfvars

Reverts hmcts/azure-platform-terraform#2455
Cleanup golden-path changes
- Removed a block of configuration for \"labs-abhivan-nodejs\".
- The `labs-abhivan-nodejs` product and its associated configuration were removed from the `sbox.tfvars` file.

Revert "abhivan golden-path test"

---

environments/sbox/sbox.tfvars

https://tools.hmcts.net/jira/browse/DTSPO-25672
Removing cft-sbox-00-aks from the app gateway for upgrading to v1.32 from v1.30
- Removed one IP address from the `cft_apps_cluster_ips` list.
- Updated `cft_apps_cluster_ips` from `[\"10.2.9.250\", \"10.2.11.250\"]` to `[\"10.2.11.250\"]`.

removing sbox-00 from app gateway for upgrade

---

environments/ithc/ithc.tfvars

- Added a new global exclusion for \"QueryStringArgNames\" with the selector \"iss\" using the operator \"Equals\".

ADOP-2484: Add 'iss' exclusion for login /receiver call

---

environments/sbox/sbox.tfvars

https://tools.hmcts.net/jira/browse/DTSPO-25672
Removing sbox-01 from app gateway for upgrade from AKS version 1.30 to 1.32
- Removed the second IP address from the `cft_apps_cluster_ips` list, leaving only one IP address.

removing sbox-01 from app gateway

---

environments/demo/demo.tfvars

https://tools.hmcts.net/jira/browse/DTSPO-25674
Remove cft-demo-01 from app gw for upgrade
- File: `environments/demo/demo.tfvars`
- Removed IP address `10.50.95.221` from the `cft_apps_cluster_ips` list
- Set `certificate_name_check` to `false`
- Enabled `autoShutdown`
- Updated `pubsubappgw_ssl_policy`

Remove cft-demo-01 from app gw for upgrade

---

environments/demo/demo.tfvars

Reverts hmcts/azure-platform-terraform#2480
- environments/demo/demo.tfvars
- The `cft_apps_cluster_ips` array has been updated to include both \"10.50.79.221\" and \"10.50.95.221\" IP addresses.

Revert "Remove demo00 from gateway for Terraform update first"

---

environments/test/test.tfvars

https://tools.hmcts.net/jira/browse/DTSPO-25686
- Removing perftest 00 from app gateway to complete AKS cluster upgrades
- Removed one IP address (10.48.79.250) from the `cft_apps_cluster_ips` list.
- Updated the `cft_apps_ag_ip_address` to \"10.48.96.123\" and `frontend_agw_private_ip_address` to \"10.48.96.113\".

DTSPO-25686: Removing perftest 00 from app gateway

---

environments/stg/stg.tfvars

https://tools.hmcts.net/jira/browse/DTSPO-25686
- Removing aat 00 from app gateway for upgrade.
- Jenkins currently using 01
- Removed one IP address from the `cft_apps_cluster_ips` list, leaving only [\"10.10.159.250\"].
- Updated the `frontend_agw_private_ip_address` to \"10.10.161.102\".

DTSPO-25686: Removing aat-00 from app gateway for upgrade

---

environments/stg/stg.tfvars

Reverts hmcts/azure-platform-terraform#2493
- Changed `stg.tfvars`
- Updated `cft_apps_cluster_ips` from `[\"10.10.159.250\"]` to `[\"10.10.143.250\", \"10.10.159.250\"]`

Revert "DTSPO-25686: Removing aat-00 from app gateway for upgrade"

---

environments/ithc/ithc.tfvars

See [ADOP-2484](https://tools.hmcts.net/jira/browse/ADOP-2484)
- Allow the successful payload of the document uploads to be allowed through. It is currently being blocked as it contains the filename to be linked to the case.
- Currently blocked in the ITHC environment, this is a test to enable the functionality in prevention mode.
- Added a new global exclusion for `RequestBodyPostArgNames` in the `frontends` configuration. 🔄

ADOP-2484: Update rules - allow details of document uploads through firewall

---

environments/stg/stg.tfvars

https://tools.hmcts.net/jira/browse/NFDIV-4717
Excluding the applicant upload doc collection for general apps in staging so that deemed service uploads can be tested
- Two new rules have been added under the \"frontends\" section, matching \"RequestBodyPostArgNames\" to \"applicant1InterimAppsEvidenceDocs\" in three places.

Added waf exclusion for general apps document uploads in aat/preview

---

environments/demo/demo.tfvars

- Added cookie matching rules for Google Analytics cookies. This allows traffic matching based on specific Google Analytics cookies.

ET1 fix to prevent firewall from blocking

---

environments/ithc/ithc.tfvars

https://tools.hmcts.net/jira/browse/FPVTL-421
- Fix the ITHC rules - they were far too expansive in turning off rules - so using normal rules based on other citizen frontends, mostly around cookies being blocked.
- This is for testing in ITHC environment
- Updated global_exclusions with multiple new entries for match_variable, operator, and selector.
- Removed the disabled_rules section and added new global_exclusions for various RequestCookieNames and QueryStringArgNames.

FPVTL-421: changes to ithc rules

---

components/apim-appgw/main.tf
components/backendappgateway/main.tf
components/frontendappgateway/local.tf
components/frontendappgateway/main.tf

DTSPO-26836
Disabling TLS on perftest to keep in line with Microsoft ending support
PoC confirmed on sbox: https://github.com/hmcts/azure-platform-terraform/pull/2546/files
- `components/apim-appgw/main.tf`:
- Updated the logic for setting `ssl_policy` based on environment, excluding \"stg\" and \"prod\" environments from the condition.
- `components/backendappgateway/main.tf`:
- Updated the logic for setting `ssl_policy` based on environment, excluding \"stg\" and \"prod\" environments from the condition.
- `components/frontendappgateway/local.tf`:
- Updated the `env` local variable to set \"stg\" environment as \"aat\", and dynamically update the \"test\" environment based on the `var.env` value.
- `components/frontendappgateway/main.tf`:
- Updated the logic for setting `ssl_policy` …

Adding non-prod environments to the upgraded TLS policy

---

environments/stg/stg.tfvars

https://tools.hmcts.net/jira/browse/ADOP-2707
Testing for https://github.com/hmcts/azure-platform-terraform/pull/2594
- Added multiple new match_variable and operator entries to prevent specific names from being blocked.
- Added comments for the new entries referencing ADOP-2707.

ADOP-2707 test change in AAT

---

environments/demo/backend_lb_config.yaml
environments/ithc/backend_lb_config.yaml
environments/prod/backend_lb_config.yaml
environments/stg/backend_lb_config.yaml
environments/test/backend_lb_config.yaml

https://tools.hmcts.net/jira/browse/FACT-2484
Enabled ssl for new fact api
- `backend_lb_config.yaml`:
- Added `ssl_enabled: true` for the `data-api` component in the demo, ithc, prod, stg, and test environments.

FACT-2484 enable ssl fact
